Rubic 276/widget slippage
Cryptorubic/rubic-app pull request #1005
Opened 2021-12-03 09:36 UTC by vlad3k

2021-12-03 14:13 UTC, siandreev requested changes

2021-12-07 09:01 UTC, siandreev requested changes

2021-12-07 09:01 UTC, siandreev commented on src/app/core/services/query-params/query-params.service.ts
> +      slippageCcr: queryParams.slippageCcr ? parseInt(queryParams.slippageCcr) : null
а если queryParams.slippageIt = '0.2'?
вместо `parseInt` нужно `parseFloat`

2021-12-07 10:15 UTC, vlad3k commented on src/app/features/swaps/services/settings-service/settings.service.ts
>      };
Поправил, только вместо set сделал get, потому что поля defaultItSettings и defaultCcrSettings  readonly

2021-12-07 10:15 UTC, vlad3k commented on src/app/features/swaps/components/swaps-settings/iframe-settings/iframe-settings.component.ts
> +      .pipe(takeUntil(this.destroy$))
Поправил

2021-12-07 10:15 UTC, vlad3k commented on src/app/core/services/query-params/query-params.service.ts
> +  slippageIt: number;
Поправил

2021-12-07 10:15 UTC, vlad3k commented on src/app/core/services/query-params/query-params.service.ts
> +      slippageCcr: queryParams.slippageCcr ? parseInt(queryParams.slippageCcr) : null
Поправил

2021-12-08 15:00 UTC, siandreev approved these changes

2021-12-08 15:00 UTC, merged