Solana v2
Cryptorubic/rubic-app pull request #1014
Opened 2021-12-13 12:44 UTC by axtezy

2021-12-16 16:34 UTC, ottebrut requested changes

2021-12-16 16:34 UTC, ottebrut commented on src/app/core/services/blockchain/blockchain-adapters/eth-like/web3-private/web3-private.service.ts
> +    private readonly providerConnector: WalletConnectorService,
`walletConnectorService`

2021-12-16 16:34 UTC, ottebrut commented on src/app/core/services/blockchain/blockchain-adapters/private-blockchain-adapter.service.ts
> +  public readonly [BLOCKCHAIN_NAME.AVALANCHE_TESTNET]: Web3PrivateService = null;
TESTNET поля для web3Private ненужны, поэтому их нужно удалить и сделать основные поля readonly

2021-12-16 16:34 UTC, ottebrut commented on src/app/core/services/blockchain/blockchain-adapters/private-blockchain-adapter.service.ts
> +    private readonly httpClient: HttpClient,
лишние сервисы

2021-12-16 16:34 UTC, ottebrut commented on src/app/core/services/blockchain/blockchain-adapters/public-blockchain-adapter.service.ts
>      );
`WEB3_SUPPORTED_BLOCKCHAINS.includes(connection.blockchainName)` всегда вернет true, и тогда нет никакой разницы между `this.defaultConnectionLinks` и `this.connectionLinks`

2021-12-16 16:36 UTC, ottebrut requested changes

2021-12-16 16:36 UTC, ottebrut commented on src/app/core/services/backend/instant-trades-api/instant-trades-api.service.ts
> +    const body = { success, ...(isSolana ? { signature: hash } : { hash }) };
используй `getHashObject`

2021-12-16 16:49 UTC, axtezy commented on src/app/core/services/backend/cross-chain-routing-api/cross-chain-routing-api.service.ts
> +      .get('trades/', { user: walletAddress }, BASE_URL)
Да. Для соланы нужно было

2021-12-17 15:04 UTC, ottebrut requested changes

2021-12-17 15:04 UTC, ottebrut commented on src/app/features/cross-chain-routing/services/cross-chain-routing-service/models/cross-chain-contract-reader.ts
> +    }
пустую строку

2021-12-17 15:04 UTC, ottebrut commented on src/app/features/cross-chain-routing/services/cross-chain-routing-service/models/cross-chain-contract-reader.ts
> +    }
пустую строку

2021-12-17 15:04 UTC, ottebrut commented on src/app/features/cross-chain-routing/services/cross-chain-routing-service/models/cross-chain-contract-reader.ts
> +    }
пустую строку

2021-12-17 15:40 UTC, axtezy commented on src/app/features/cross-chain-routing/services/cross-chain-routing-service/cross-chain-contract-executor.facade.ts
> +  }
Раньше они были не статические, исправил

2021-12-17 15:53 UTC, axtezy commented on src/app/features/cross-chain-routing/services/cross-chain-routing-service/models/cross-chain-contract-reader.ts
> +    if (this.blockchainAdapter instanceof SolanaWeb3Public) {
Тайпгвард тогда не сработает

2021-12-17 15:56 UTC, axtezy commented on src/app/features/cross-chain-routing/components/target-network-address/target-network-address.component.ts
> +  ngAfterViewInit() {
Сработает, поправил

2021-12-17 16:01 UTC, axtezy commented on src/app/core/wallets/components/wallets-modal/models/providers.ts
> +    supportsInVerticalIframe: true,
Траст валлет, например не должен

2021-12-20 08:37 UTC, ottebrut requested changes

2021-12-20 08:37 UTC, ottebrut commented on src/app/core/services/blockchain/wallets/wallets-adapters/eth-like/wallet-connect-adapter.ts
> +  public get detailedWalletName(): string {
Конструктор все еще выше

2021-12-20 08:58 UTC, axtezy commented on src/app/core/services/blockchain/wallets/wallets-adapters/eth-like/wallet-connect-adapter.ts
> +  public get detailedWalletName(): string {
Да, не тот файл посмотрел

2021-12-20 09:05 UTC, ottebrut approved these changes

2021-12-20 09:14 UTC, merged