Feature/algebra
Cryptorubic/rubic-app pull request #1019
Opened 2021-12-15 15:13 UTC by ottebrut

2021-12-16 10:41 UTC, siandreev requested changes

2021-12-16 10:41 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/polygon/algebra-service/utils/quoter-controller/AlgebraQuoterController.ts
> +          .filter(route => route !== null);
then в async

2021-12-16 10:41 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/polygon/algebra-service/constants/quoterContractData.ts
> +export const quoterContractAbi = [
давай лишнего поудаляем

2021-12-16 10:41 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/common/uni-v3-algebra/common-service/common-uni-v3-algebra.service.ts
> +export abstract class CommonUniV3AlgebraService implements ItProvider {
а обычный uniswap версии 3, ты не менял пока? Не наследовал его от `CommonUniV3AlgebraService`?

2021-12-16 10:56 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/common/uni-v3-algebra/common-service/common-uni-v3-algebra.service.ts
> +export abstract class CommonUniV3AlgebraService implements ItProvider {
наследовал

2021-12-16 11:22 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/polygon/algebra-service/utils/quoter-controller/AlgebraQuoterController.ts
> +          .filter(route => route !== null);
поправил

2021-12-16 11:22 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/polygon/algebra-service/constants/quoterContractData.ts
> +export const quoterContractAbi = [
поправил в quoter и swapRouter для алегбры и юни в3

2021-12-20 09:04 UTC, siandreev approved these changes

2021-12-20 11:27 UTC, axtezy approved these changes

2021-12-20 11:28 UTC, axtezy approved these changes
названия файлов в kebab-case

2021-12-21 16:02 UTC, axtezy approved these changes

2021-12-21 16:06 UTC, merged