Rubic 288/staking
Cryptorubic/rubic-app pull request #1022
Opened 2021-12-17 16:08 UTC by kolebayevv

все работает с учетом того что я в сервисе use-testing-mode.service.ts удалил на 69 строчке таймаут для вызова this.useTestingMode()

2021-12-20 08:55 UTC, siandreev requested changes

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/components/stake-button-container/stake-button-container.component.ts
> +    if (amount.isNaN()) {
`!amount.isFinite() `

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/components/stake-button-container/stake-button-container.component.ts
> +  public errorType$ = new BehaviorSubject<ErrorTypeEnum | null>(ErrorTypeEnum.EMPTY_AMOUNT);
зачем сабж?

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/components/stake/stake.component.scss
> +@import 'src/scss/vars';
@use

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/components/stake-button-container/stake-button-container.component.scss
> +@import 'src/scss/vars';
@use

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/components/stake-button-container/stake-button-container.component.html
> +    <ng-container [ngSwitch]="errorType">
еще нужна проверка на то, что в ММ выбрана не та сеть

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/components/stake/stake.component.ts
> +    private readonly destroy$: TuiDestroyService,
`@Self`

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/components/staking-container/staking-container.component.scss
> +@import 'src/styles';
тут и дальше @use

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/components/staking-container/staking-container.component.scss
> +
пустая строчка. Стайл линт в вебшторме настроил?

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/components/staking-info/staking-info.component.html
> +      alt="High APY"
APR

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/components/staking-info/staking-info.component.scss
> +        &--top,
у нас модификатор через _ 
блок__элемент_модификатор

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/components/staking-info/staking-info.component.html
> +        {{ userEnteredAmount$ | async | bigNumberFormat }} BRBC of
`userEnteredAmount$ | async` в `*ngLet`

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/components/staking-info/staking-info.component.html
> +      {{ totalRBCEntered$ | async | bigNumberFormat }} BRBC of
*ngLet

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/components/withdraw-button-container/withdraw-button-container.component.ts
> +@Component({
в чем отличие от StakingButton?

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/constants/BRBC_CONTRACT_ABI.ts
> +export const BRBC_CONTRACT_ABI = [
поудаляй лишнее

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/constants/STAKING_TOKENS.ts
> +export const STAKING_TOKENS = [
тестнет?

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/services/staking.service.ts
> +  get userEnteredAmount$(): Observable<number> {
поле, а не геттер

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/services/staking.service.ts
> +  get userEnteredAmount$(): Observable<number> {
ниже аналогично

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/services/staking.service.ts
> +  }
then не используем; почему бы не  сделать это привтным и не вызывать это в конструкторе? Думаю, лучше будет, если этот метод будет просто возвращать Observable/Promise, а загружать данные и пихать их в сабж

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/services/staking.service.ts
> +          .then(userEnteredAmount => this._userEnteredAmount$.next(+userEnteredAmount));
then в подписке

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/services/staking.service.ts
> +          .then(userEnteredAmount => this._userEnteredAmount$.next(+userEnteredAmount));
и опять же, думаю, лучше будет, если метод будет делать одну задачу, например, только возвращать данные

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/services/staking.service.ts
> +  public calculateLeaveReward(amount: string): Observable<number | BigNumber> {
пусть будет принимать BigNumber, либо отформатированную строку; в других методах аналогично

2021-12-20 08:55 UTC, siandreev commented on src/app/features/staking/services/staking.service.ts
> +          .then(userEnteredAmount => this._userEnteredAmount$.next(+userEnteredAmount));
в остальных методах аналогично

2021-12-20 08:55 UTC, siandreev commented on src/assets/i18n/zh.json
> +      "overLimit": "One stake limits 1,000 - 100,000 BRBC",
запроси у Андрея пиарщика переводы

2021-12-20 08:59 UTC, kolebayevv commented on src/app/features/staking/components/staking-container/staking-container.component.scss
> +
тут он сам сделал отступ между ними, тоже подумал странно

2021-12-20 09:00 UTC, kolebayevv commented on src/app/features/staking/constants/STAKING_TOKENS.ts
> +export const STAKING_TOKENS = [
+

2021-12-20 09:27 UTC, axtezy requested changes

2021-12-20 09:27 UTC, axtezy commented on src/app/core/header/components/header/components/rubic-menu/rubic-menu.component.ts
> +  public menuClickHandler(linkType: 'swaps' | 'bridge' | 'cross-chain' | 'staking'): void {
Можем отдельный тип сделать и вместо `else/if `или `switch case `объект заведем, `Record<LinkType, () => {}>`

2021-12-20 09:27 UTC, axtezy commented on src/app/core/services/backend/staking-api/staking-api.service.ts
> +  // public getApr() {}
Лишний коммент

2021-12-20 09:27 UTC, axtezy commented on src/app/features/staking/components/stake/stake.component.ts
> +  public loading$ = new BehaviorSubject<boolean>(false);
readonly

2021-12-20 09:27 UTC, axtezy commented on src/app/features/staking/components/stake/stake.component.ts
> +  public needLogin$ = this.stakingService.needLogin$;
readonly

2021-12-20 09:27 UTC, axtezy commented on src/app/features/staking/components/stake/stake.component.ts
> +  public selectedTokenBalance$ = this.stakingService.selectedTokenBalance$;
readonly

2021-12-20 09:27 UTC, axtezy commented on src/app/features/staking/components/stake/stake.component.ts
> +  public amount = new FormControl('');
readonly

2021-12-20 09:27 UTC, axtezy commented on src/app/features/staking/components/stake/stake.component.ts
> +  public token = new FormControl(STAKING_TOKENS[0]);
readonly

2021-12-20 09:27 UTC, axtezy commented on src/app/features/staking/components/staking-container/staking-container.component.scss
> +
лишняя стркоа

2021-12-20 09:27 UTC, axtezy commented on src/app/features/staking/components/staking-container/staking-container.component.scss
> +  border-radius: 22px;
Вроде глобальная переменная была для бордер-радиуса. Ну и другие магические числа можно в локальные переменные вынести

2021-12-20 09:27 UTC, axtezy commented on src/app/features/staking/components/staking-container/staking-container.component.scss
> +      box-shadow: none !important;
так, так, так, импортант) Лучше другими способами специфичность повысить

2021-12-20 09:27 UTC, axtezy commented on src/app/features/staking/components/staking-container/staking-container.component.scss
> +.calculate-profitability {
Можно и так оставить, но мне кажетсмя, когда у тебя для 1 компоненте в css 3 разных класса, это значит что можно разбить этот компонент на несколько

2021-12-20 09:27 UTC, axtezy commented on src/app/features/staking/components/staking-container/staking-container.component.ts
> +enum StakingNavEnum {
Название `enum` тоже можно в sreaming snake case, а то странно получается когда первая половина в 1 кейсе, а вторая в другом: `StakingNavEnum.STAKE`

2021-12-20 09:27 UTC, axtezy commented on src/app/features/staking/components/staking-info/staking-info.component.scss
> +    border-radius: 22px;
Много повторяющихся элементов стилей, можно вынести в переменные локальные/глобальные

2021-12-20 09:27 UTC, axtezy commented on src/app/features/staking/components/staking-statistics/staking-statistics.component.scss
> +    border-radius: 22px;
Переменные

2021-12-20 09:27 UTC, axtezy commented on src/app/features/staking/components/withdraw/withdraw.component.ts
> +  public amount = new FormControl<string>('');
readonly у полей

2021-12-20 09:27 UTC, axtezy commented on src/app/features/staking/services/staking.service.ts
> +  private _canReceiveAmount$ = new BehaviorSubject<BigNumber>(new BigNumber(0));
readonly поля

2021-12-20 09:27 UTC, axtezy commented on src/app/features/staking/services/staking.service.ts
> +  public enterStake(amount: BigNumber): Observable<TransactionReceipt> {
На методы в сервисах нужно будет JSDoc добавить в финальной версии

2021-12-20 09:27 UTC, axtezy commented on src/app/shared/utils/utils.ts
> +export interface MinimalToken {
Лучше вынести в shared/models тогда, раз интерфейс стал экспортируемым

2021-12-20 09:34 UTC, kolebayevv commented on src/app/features/staking/services/staking.service.ts
> +  public enterStake(amount: BigNumber): Observable<TransactionReceipt> {
принято!

2021-12-20 09:48 UTC, kolebayevv commented on src/app/features/staking/components/staking-container/staking-container.component.scss
> +.calculate-profitability {
да просто не хочется ради простого темплейта еще компоненту заводить, конечно она ресурсов не схавает много но на мой взгляд и так норм

2021-12-20 09:50 UTC, kolebayevv commented on src/app/core/services/backend/staking-api/staking-api.service.ts
> +  // public getApr() {}
да это под реализацию метод, щас с след коммитом будут норм функции

2021-12-20 09:52 UTC, kolebayevv commented on src/app/features/staking/components/stake-button-container/stake-button-container.component.ts
> +  public errorType$ = new BehaviorSubject<ErrorTypeEnum | null>(ErrorTypeEnum.EMPTY_AMOUNT);
чтоб асинк пайп  подхватывал сам в темплейте изменения

2021-12-20 09:55 UTC, kolebayevv commented on src/app/core/header/components/header/components/rubic-menu/rubic-menu.component.ts
>      }
@siandreev  @axtezy это изменение случайно залетело, убрал лишнее и оставил ту-ду

2021-12-20 10:08 UTC, kolebayevv commented on src/app/features/staking/components/staking-container/staking-container.component.scss
> +  border-radius: 22px;
@axtezy а магические числа это какие?) Я так понял тебя удивил бордер-радиус которого нет в переменных? Если да то я бы не стал заводить еще переменные и это косяк диза, надо остальное тоже чекнуть тогда на отклонения

2021-12-23 08:37 UTC, axtezy approved these changes

2021-12-23 08:43 UTC, siandreev approved these changes

2021-12-23 08:47 UTC, merged

2026-09-07 15:37 UTC, 0xka13b commented
легенды @axtezy @siandreev