Updated ccr contracts (only uni v2)
Cryptorubic/rubic-app pull request #1038
Opened 2021-12-22 10:56 UTC by ottebrut

2021-12-27 13:56 UTC, kolebayevv approved these changes

2021-12-27 13:56 UTC, kolebayevv commented on src/app/features/swaps/components/amount-input/components/vertical-iframe-token-amount-input/vertical-iframe-token-amount-input.component.ts
> +    this.amount.setValue(this.selectedToken.amount.toFixed());
.toFixed(0) ?

2021-12-28 08:57 UTC, ottebrut commented on src/app/features/swaps/components/amount-input/components/vertical-iframe-token-amount-input/vertical-iframe-token-amount-input.component.ts
> +    this.amount.setValue(this.selectedToken.amount.toFixed());
Нет, именно toFixed(), чтобы привести к строчке. Метод toString() не подходит, потому что большие числа преобразует в экспоненциальную форму.

2021-12-30 10:20 UTC, axtezy requested changes

2021-12-30 10:20 UTC, axtezy commented on src/app/features/swaps/components/swap-info/styles/styles.scss
> +    margin-bottom: 14px !important;
зачем импортант, это же наш компонент, а не библиотечный, можно просто специфичность повысить

2021-12-30 10:21 UTC, axtezy approved these changes

2021-12-30 12:18 UTC, vlad3k approved these changes

2021-12-30 19:29 UTC, merged