Rubic 288/staking theme
Cryptorubic/rubic-app pull request #1061
Opened 2021-12-24 12:09 UTC by vlad3k

2021-12-24 13:58 UTC, axtezy requested changes

2021-12-24 13:58 UTC, axtezy commented on src/app/features/staking/components/staking-container/staking-container.component.scss
> +  --bg: var(--form-header-color-1);
почитабельнее бы названия переменных)

2021-12-24 13:58 UTC, axtezy commented on src/app/features/staking/components/staking-container/staking-container.component.scss
> +    border-radius: 22px 22px 0 0;
вместо 22px поставь переменную (которая на 20px)

2021-12-24 13:58 UTC, axtezy commented on src/app/features/staking/components/staking-info/staking-info.component.ts
> +    this.stakingService.reloadStakingProgress().pipe(delay(3000)).subscribe();
зачем delay?

2021-12-24 14:08 UTC, vlad3k commented on src/app/features/staking/components/staking-info/staking-info.component.ts
> +    this.stakingService.reloadStakingProgress().pipe(delay(3000)).subscribe();
Ай, забыл убрать...

2021-12-24 14:09 UTC, vlad3k commented on src/app/features/staking/components/staking-container/staking-container.component.scss
> +  --bg: var(--form-header-color-1);
Какие были)

2021-12-24 14:12 UTC, axtezy commented on src/app/features/staking/components/staking-container/staking-container.component.scss
> +  --bg: var(--form-header-color-1);
я про` --bg,` давай `--background-color` сделаем

2021-12-24 14:21 UTC, vlad3k commented on src/app/features/staking/components/staking-container/staking-container.component.scss
> +  --bg: var(--form-header-color-1);
Поправил

2021-12-24 14:21 UTC, vlad3k commented on src/app/features/staking/components/staking-container/staking-container.component.scss
> +    border-radius: 22px 22px 0 0;
Поправил

2021-12-24 14:21 UTC, vlad3k commented on src/app/features/staking/components/staking-info/staking-info.component.ts
> +    this.stakingService.reloadStakingProgress().pipe(delay(3000)).subscribe();
Убрал

2021-12-24 14:31 UTC, axtezy approved these changes

2021-12-27 14:17 UTC, kolebayevv commented
то что в этой ветке уже оттестировали и я подмержил ее себе в hotfix/staking-bugs-v3, так что можно закрывать пр и удалять ветку

2021-12-27 15:48 UTC, merged