Staking module improvements
Cryptorubic/rubic-app pull request #1079
Opened 2021-12-28 13:07 UTC by kolebayevv

ветку случайно назвал rubic-improvements) должно было быть staking-improvements

2021-12-28 13:46 UTC, axtezy requested changes

2021-12-28 13:46 UTC, axtezy commented on src/app/features/staking/components/stake/stake.component.ts
> +    @Inject(Injector) private readonly injector: Injector,
Неисользуемые сервисы?

2021-12-28 13:46 UTC, axtezy commented on src/app/features/staking/components/swap-modal/swap-modal.component.ts
> +
Пустые строки?

2021-12-28 13:46 UTC, axtezy commented on src/app/features/staking/components/withdraw/withdraw.component.ts
> +  public readonly rewardUsdPrice$ = new BehaviorSubject<BigNumber>(new BigNumber(0));
public subjects нежелательно делать. У нас в еслинте даже это правило есть, но оно сломалось

2021-12-28 13:46 UTC, axtezy commented on src/app/features/staking/services/staking.service.ts
> +// services
Имхо, только размер файла увеличивает, в имопрты никто не смотрит

2021-12-28 13:46 UTC, axtezy commented on src/app/features/staking/services/staking.service.ts
> +        this.errorService.catch(error as RubicError<ERROR_TYPE.TEXT>);
в методе `catch()` уже есть `console.debug`

2021-12-28 13:46 UTC, axtezy commented on src/app/features/staking/services/staking.service.ts
>          this.errorService.catch(error as RubicError<ERROR_TYPE.TEXT>);
аналогично

2021-12-28 13:46 UTC, axtezy commented on src/app/features/staking/services/staking.service.ts
> +        this.errorService.catch(error as RubicError<ERROR_TYPE.TEXT>);
консоль дебаг уже есть в методе

2021-12-28 13:46 UTC, axtezy commented on src/app/features/staking/services/staking.service.ts
> +   * @param amount
Параметры бы тоже описать)

2021-12-28 14:01 UTC, ottebrut requested changes

2021-12-28 14:08 UTC, kolebayevv commented on src/app/features/staking/services/staking.service.ts
> +    return interval(this.BRBC_USD_PRICE_UPDATE_TIME).pipe(
мне важно чтобы подписка не подвисала после ухода с стейкинга, для этого я возвращаю обс из метода чтобы в пайпе в компоненте использовать tui destroy service

2021-12-28 14:33 UTC, kolebayevv commented on src/app/features/staking/components/withdraw/withdraw.component.ts
> +  public readonly rewardUsdPrice$ = new BehaviorSubject<BigNumber>(new BigNumber(0));
no-exposed-subjects не относится только к обычным сабжам часом?

2021-12-28 14:33 UTC, siandreev requested changes

2021-12-28 14:33 UTC, siandreev commented on src/app/features/staking/components/withdraw/withdraw.component.ts
>      }),
на всякий случай стоит добавить `share()`, а то в случае 2 подписчиков будет плохо

2021-12-28 14:33 UTC, siandreev commented on src/app/features/staking/services/staking.service.ts
> +    return interval(this.BRBC_USD_PRICE_UPDATE_TIME).pipe(
> Убери return и в конце добавь .subscribe() - это же просто установка таймера

тогда таймер будет работать после того, как юзер покинет страницу стейкинга

2021-12-28 14:33 UTC, siandreev commented on src/app/features/staking/services/staking.service.ts
> +    return interval(this.BRBC_USD_PRICE_UPDATE_TIME).pipe(
> Если ты хочешь оставить эту функцию публичной, то сохрани observable в подписку

лучше в пайпе `share()` сделать

2021-12-28 14:33 UTC, siandreev commented on src/app/features/staking/components/stake/stake.component.ts
>  @Component({
JSDoc описание компонента

2021-12-28 14:33 UTC, siandreev commented on src/app/features/staking/components/stake-button-container/stake-button-container.component.ts
>  @Component({
JSDoc описание компонента

2021-12-28 14:33 UTC, siandreev commented on src/app/features/staking/components/withdraw-button-container/withdraw-button-container.component.ts
>  @Component({
JSDoc описание компонента

2021-12-28 14:33 UTC, siandreev commented on src/app/features/staking/components/withdraw-button-container/withdraw-button-container.component.ts
> +  @Input() maxAmountForWithdraw: BigNumber;
комменты на инпуты/аутпуты

2021-12-28 14:45 UTC, axtezy commented on src/app/features/staking/components/withdraw/withdraw.component.ts
> +  public readonly rewardUsdPrice$ = new BehaviorSubject<BigNumber>(new BigNumber(0));
Нет, лучше приватный сабж делать и public `.asObservable` поле

2021-12-28 14:49 UTC, kolebayevv commented on src/app/features/staking/components/withdraw/withdraw.component.ts
>      }),
это valueChanges стрим, думаю тут не стоит об этом переживать

2021-12-29 09:55 UTC, axtezy requested changes

2021-12-29 09:55 UTC, axtezy commented on src/app/features/staking/components/staking-info/staking-info.component.ts
> + * Component shows total staking progress and for logged-in user.
лишний and или наоборот что-то после and хотел дописать?

2021-12-29 09:55 UTC, axtezy commented on src/app/features/staking/components/staking-tokens/staking-tokens.component.ts
> + * Component for select with custom template of option
Как-то коряво звучит) `Staking tokens dropdown component` понятнее бы было

2021-12-29 09:55 UTC, axtezy commented on src/app/features/staking/components/swap-modal/swap-modal.component.ts
> + * A modal window component allows user to choose how to stake,
window необязательно, модал есть модал. Я бы так сделал:
`The modal which allows user to choose staking method`

2021-12-29 09:55 UTC, axtezy commented on src/app/features/staking/components/swap-modal/swap-modal.component.ts
> +    // this._bridgeSwapButtonLoading$.next(true);
Коменты еще нужны?

2021-12-29 09:55 UTC, axtezy commented on src/app/features/staking/components/withdraw-button-container/withdraw-button-container.component.ts
> + * Withdraw button container component, contains logic of leaving stake,
`which contains` или `.` вместо `,`

2021-12-29 09:55 UTC, axtezy commented on src/app/features/staking/services/staking.service.ts
> +        console.debug(error);
лишний дебаг

2021-12-29 09:57 UTC, kolebayevv commented on src/app/features/staking/components/staking-info/staking-info.component.ts
> + * Component shows total staking progress and for logged-in user.
не тут типа "Общий прогресс сткейкинга и для авторизированного юзера", там же два прогресс-бара

2021-12-29 09:58 UTC, kolebayevv commented on src/app/features/staking/components/staking-tokens/staking-tokens.component.ts
> + * Component for select with custom template of option
soglasen

2021-12-29 09:58 UTC, kolebayevv commented on src/app/features/staking/components/swap-modal/swap-modal.component.ts
> +    // this._bridgeSwapButtonLoading$.next(true);
да , пусть будет, на следущей раунд стеейкинга включу функционал

2021-12-29 10:01 UTC, kolebayevv commented on src/app/features/staking/components/staking-info/staking-info.component.ts
> + * Component shows total staking progress and for logged-in user.
сделал "Component shows total staking progress and progress for logged-in user."

2021-12-29 10:05 UTC, axtezy approved these changes

2021-12-29 10:23 UTC, siandreev requested changes

2021-12-29 10:23 UTC, siandreev commented on src/app/features/staking/components/withdraw/withdraw.component.ts
>      }),
> это valueChanges стрим, думаю тут не стоит об этом переживать

но ты изменил его пайпом. Если у `canReceive$` будет два подписчика, то `this.rewardUsdPrice$.next...` будет выполнено два раза

2021-12-29 11:28 UTC, kolebayevv commented on src/app/features/staking/components/withdraw/withdraw.component.ts
>      }),
справедливо, сделаю

2021-12-29 13:24 UTC, siandreev approved these changes

2021-12-29 13:28 UTC, ottebrut approved these changes

2021-12-30 08:46 UTC, merged