Widget fixes
Cryptorubic/rubic-app pull request #1107
Opened 2022-01-21 14:58 UTC by kolebayevv

2022-01-21 16:16 UTC, siandreev requested changes

2022-01-21 16:16 UTC, siandreev commented on src/app/core/errors/models/provider/wallet-not-installed.ts
> +export class WalletNotInstalled extends RubicError<ERROR_TYPE.TEXT> {
WalletNotInstalledError

2022-01-21 16:17 UTC, siandreev requested changes

2022-01-21 16:17 UTC, siandreev commented on src/assets/i18n/ru.json
> +    "walletNotInstalled": "Wallet is not installed."
переводы

2022-01-21 16:17 UTC, siandreev commented on src/assets/i18n/ru.json
> +    "walletNotInstalled": "Wallet is not installed."
если впадлу маркетологам писать, то просто в гугл транслейте переведи

2022-01-22 16:16 UTC, kolebayevv commented on src/app/core/errors/models/provider/wallet-not-installed.ts
> +export class WalletNotInstalled extends RubicError<ERROR_TYPE.TEXT> {
done

2022-01-22 16:16 UTC, kolebayevv commented on src/assets/i18n/ru.json
> +    "walletNotInstalled": "Wallet is not installed."
done

2022-01-24 09:31 UTC, siandreev approved these changes

2022-01-25 10:35 UTC, axtezy approved these changes

2022-01-25 10:38 UTC, merged