Turkish  languages
Cryptorubic/rubic-app pull request #1118
Opened 2022-01-25 11:36 UTC by zinderud

I hope that will be useful. good work.
note : I could not find turkey.svg file in 32*32 size.

2022-01-25 12:33 UTC, ottebrut requested changes

2022-01-25 12:33 UTC, ottebrut commented on src/app/core/header/models/languages-list.ts
> +    imgSrc: 'assets/images/icons/languages/en.svg'
Must be `...tr.svg`

2022-01-25 12:53 UTC, zinderud commented
.

2022-01-31 10:49 UTC, ottebrut approved these changes

2022-02-01 11:35 UTC, axtezy commented
> I hope that will be useful. good work. note : I could not find turkey.svg file in 32*32 size.

Hello @zinderud, you did really good work!
We would like to reward you for your efforts, can you please contact @renedsaa in telegram in order to get a reward?

2022-02-02 08:00 UTC, kolebayevv approved these changes

2022-02-03 16:28 UTC, merged