Hide transaction info in accordion
Cryptorubic/rubic-app pull request #1127
Opened 2022-01-31 09:41 UTC by kolebayevv

2022-01-31 12:20 UTC, ottebrut requested changes

2022-01-31 12:20 UTC, ottebrut commented on src/app/features/swaps/components/swap-info/components/swap-info-container/swap-info-container.component.ts
> +  public accordionState = false;
переименуй в accordionOpen

2022-02-01 11:13 UTC, kolebayevv commented on src/app/features/swaps/components/swap-info/components/swap-info-container/swap-info-container.component.ts
> +  public accordionState = false;
done

2022-02-01 11:16 UTC, axtezy requested changes

2022-02-01 11:16 UTC, axtezy commented on src/app/features/swaps/components/swap-info/components/swap-info-container/swap-info-container.component.scss
> +      border-radius: 19px;
`$border-radius-2` вместо 19px

2022-02-01 11:24 UTC, kolebayevv commented on src/app/features/swaps/components/swap-info/components/swap-info-container/swap-info-container.component.scss
> +      border-radius: 19px;
done

2022-02-01 11:24 UTC, axtezy approved these changes

2022-02-01 11:53 UTC, ottebrut approved these changes

2022-02-01 12:55 UTC, merged