Feature/turkish language
Cryptorubic/rubic-app pull request #1141
Opened 2022-02-03 16:46 UTC by vlad3k

2022-02-04 12:48 UTC, axtezy requested changes
Надо еще в  query-params добавить tr в список языков

2022-02-04 13:13 UTC, vlad3k commented
> Надо еще в  query-params добавить tr в список языков

Поправил

2022-02-04 14:01 UTC, axtezy approved these changes

2022-02-24 09:31 UTC, axtezy approved these changes

2022-02-24 11:49 UTC, merged