Rubic 253/gtm counter
Cryptorubic/rubic-app pull request #1272
Opened 2022-03-16 09:13 UTC by Doctor-Cyclone

2022-03-16 10:01 UTC, axtezy requested changes

2022-03-16 15:12 UTC, axtezy approved these changes

2022-03-17 15:10 UTC, ottebrut commented on src/app/core/services/google-tag-manager/google-tag-manager.service.ts
> +  create: unknown;
Function

2022-03-17 15:31 UTC, ottebrut approved these changes

2022-03-18 07:14 UTC, merged