call functions in template via pipe, fix scanner links in my trades
Cryptorubic/rubic-app pull request #1297
Opened 2022-03-25 10:28 UTC by kolebayevv

2022-03-25 14:53 UTC, axtezy requested changes

2022-03-25 14:53 UTC, axtezy commented on src/app/core/wallets/components/wallets-modal/wallets-modal.component.ts
> +  public shouldRenderAsLink = (provider: WALLET_NAME): boolean => {
readonly

2022-03-28 07:58 UTC, kolebayevv commented on src/app/core/wallets/components/wallets-modal/wallets-modal.component.ts
> +  public shouldRenderAsLink = (provider: WALLET_NAME): boolean => {
@axtezy done

2022-03-28 09:35 UTC, ottebrut approved these changes

2022-03-28 09:35 UTC, merged