minor fixes
Cryptorubic/rubic-app pull request #1308
Opened 2022-03-31 13:57 UTC by kolebayevv

2022-04-05 12:38 UTC, ottebrut requested changes

2022-04-05 12:38 UTC, ottebrut commented on src/app/features/liquidity-providing/components/deposit-button/deposit-button.component.ts
> +  constructor(private readonly service: LiquidityProvidingService) {}
я бы назвал хотя бы lpService

2022-04-05 12:38 UTC, ottebrut commented on src/app/features/liquidity-providing/components/deposit-button/deposit-button.component.ts
> +      .subscribe();
takeUntil?

2022-04-05 12:38 UTC, ottebrut commented on src/app/features/liquidity-providing/components/deposit-card/deposit-card.component.ts
> +  onRemoveDeposit = new EventEmitter<void>();
давай в одном стиле будем писать @Input() ... в одну строчку

2022-04-05 12:38 UTC, ottebrut commented on src/app/features/liquidity-providing/components/deposit-form/deposit-form.component.ts
> +      // const amountUsdPrice = await this.service.calculateUsdPrice(new BigNumber(amount), 'brbc');
добавляй TODO чтобы не забыть

2022-04-05 12:38 UTC, ottebrut commented on src/app/features/liquidity-providing/components/deposit-form/deposit-form.component.ts
> +    private readonly service: LiquidityProvidingService,
опять же lpService

2022-04-05 12:38 UTC, ottebrut commented on src/app/features/liquidity-providing/components/deposits/deposits.component.ts
> +    private readonly service: LiquidityProvidingService,
lpService

2022-04-05 12:38 UTC, ottebrut commented on src/app/features/liquidity-providing/components/lp-landing/lp-landing.component.ts
> +      this.cdr.detectChanges();
markForChanges
и не очень понимаю, зачем тут этот сабскрайб

2022-04-05 12:38 UTC, ottebrut commented on src/app/features/liquidity-providing/components/lp-landing/lp-landing.component.ts
> +    alert('deposit type - ' + depositType);
TODO

2022-04-06 12:24 UTC, kolebayevv commented on src/app/features/liquidity-providing/components/deposit-button/deposit-button.component.ts
> +      .subscribe();
brbcAmount$ прокидывается инпутом сюда, там уже есть тэйк антил

2022-04-06 12:24 UTC, kolebayevv commented on src/app/features/liquidity-providing/components/deposit-card/deposit-card.component.ts
> +  onRemoveDeposit = new EventEmitter<void>();
done

2022-04-06 12:24 UTC, kolebayevv commented on src/app/features/liquidity-providing/components/deposit-form/deposit-form.component.ts
> +      // const amountUsdPrice = await this.service.calculateUsdPrice(new BigNumber(amount), 'brbc');
добавил подтягивание баланса

2022-04-06 12:29 UTC, kolebayevv commented on src/app/features/liquidity-providing/components/lp-landing/lp-landing.component.ts
> +    alert('deposit type - ' + depositType);
ubral vashe eto

2022-04-06 12:35 UTC, kolebayevv commented on src/app/features/liquidity-providing/components/lp-landing/lp-landing.component.ts
> +      this.cdr.detectChanges();
для обновления темплейта, там много проверок на вайтлист/не вайтлист, залогинен/не залогинен, вскоре еще наверно добавится проверка на кошелек, если у юзера подключен солана или ниар кошельки то рисовать другой темплейт. Вообще в чем суть тут обсерваблов везде - интерфейс должен реагировать на 1) подключение кошелька 2) отключение кошелька 3) смена адреса, поэтому много подписок на этот сабж

2022-04-14 08:12 UTC, axtezy requested changes

2022-04-14 08:12 UTC, axtezy commented on src/app/features/staking-lp/services/staking-lp.service.ts
> +  private readonly stakingContracts: { address: string; abi: AbiItem[]; active?: boolean }[] = [
лучше в интерфейс на уровня файла тип вынести, а сам массив в метод типа getStakingContracts. Получится гораздо красивее, а когда во много строчек присвоение происходит, рушится структура класса, как по мне.
`private readonly stakingContracts: Contract = this.getStakingContracts();`

2022-04-14 08:12 UTC, axtezy commented on src/app/features/staking-lp/services/staking-lp.service.ts
> +    this.tokensService
В отдельный метод

2022-04-14 08:12 UTC, axtezy commented on src/app/shared/components/chips/chips.component.ts
> +  set initialValue(value: Chip) {
`value` переименовать на `chip`, а то `value.value` звучит странно)

2022-04-14 08:12 UTC, axtezy commented on src/app/shared/components/chips/chips.component.ts
> +  value: unknown;
Точнее тип не получится указать?

2022-04-14 08:12 UTC, axtezy commented on src/app/shared/guards/until-time.guard.ts
> +  // private readonly expireDateUTC = Date.UTC(2022, 2, 1, 14, 0, 0, 0);
Тут что-то непонятное с гвардом произошло

2022-04-14 10:44 UTC, kolebayevv commented on src/app/shared/components/chips/chips.component.ts
> +  value: unknown;
не, тут как раз анкноун, суть в том чтоб на интерфейсе отрисовывать только лейблы, а эмитить этот компонент сможет любое значение

2022-04-14 10:45 UTC, kolebayevv commented on src/app/shared/guards/until-time.guard.ts
> +  // private readonly expireDateUTC = Date.UTC(2022, 2, 1, 14, 0, 0, 0);
да я для лп модуля отдельный сделал. Этот вообще можно удалить

2022-04-14 13:02 UTC, kolebayevv commented on src/app/features/liquidity-providing/components/deposit-button/deposit-button.component.ts
> +    combineLatest([this.brbcAmount$, this.lpService.brbcBalance$])
done

2022-04-14 13:03 UTC, kolebayevv commented on src/app/features/liquidity-providing/components/deposit-card/deposit-card.component.scss
> +    color: #fff;
done

2022-04-14 13:03 UTC, kolebayevv commented on src/app/features/liquidity-providing/components/deposit-card/deposit-card.component.ts
> +  @Output() onCollectRewards = new EventEmitter<void>();
done

2022-04-14 13:05 UTC, kolebayevv commented on src/app/features/staking-lp/services/staking-lp.service.ts
> +  private readonly stakingContracts: { address: string; abi: AbiItem[]; active?: boolean }[] = [
done

2022-04-14 13:08 UTC, kolebayevv commented on src/app/features/staking-lp/services/staking-lp.service.ts
> +  private readonly stakingContracts: { address: string; abi: AbiItem[]; active?: boolean }[] = [
вынес в константы эти массивы и отдельно тип специфичный в рамках модуля - `interface RoundContract {...}`

2022-04-14 13:09 UTC, kolebayevv commented on src/app/features/staking-lp/services/staking-lp.service.ts
> +    this.tokensService
done

2022-04-14 13:10 UTC, kolebayevv commented on src/app/shared/components/chips/chips.component.ts
> +  set initialValue(value: Chip) {
done

2022-04-14 13:11 UTC, kolebayevv commented on src/app/features/liquidity-providing/components/deposit-button/deposit-button.component.html
> +        <ng-container *ngSwitchCase="errors.POOL_FULL"> Pool Fool </ng-container>
надо подумать как сделать его

2022-04-27 09:50 UTC, kolebayevv commented on src/app/features/liquidity-providing/components/deposit-form/deposit-form.component.html
> +        [formControl]="brbcAmountCtrl"
done

2022-04-27 09:50 UTC, kolebayevv commented on src/app/features/liquidity-providing/components/deposit-form/deposit-form.component.scss
> +
done

2022-04-27 09:52 UTC, kolebayevv commented on src/app/features/liquidity-providing/components/deposit-form/deposit-form.component.ts
> +    this.brbcAmount$.pipe(skip(1)).subscribe(value => {
done

2022-04-27 09:53 UTC, kolebayevv commented on src/app/features/liquidity-providing/components/deposits/deposits.component.ts
> +        this.cdr.detectChanges();
я бы оставил это на после релиза чтоб не ломать ничего, т.к. хз что за оператор и как он отработает

2022-04-27 09:55 UTC, kolebayevv commented on src/app/features/liquidity-providing/components/lp-page/lp-page.component.ts
> +    this.walletConnectorService.addressChange$
done

2022-04-27 10:01 UTC, kolebayevv commented on src/app/features/liquidity-providing/components/lp-statistics/lp-statistics.component.ts
> +    this.walletConnectorService.addressChange$
done

2022-04-27 10:02 UTC, kolebayevv commented on src/app/features/liquidity-providing/components/transfer-modal/transfer-modal.component.html
> +    is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
логику с трансфером пока убрали - но возможно она вернется, удалять компоненту не хочется а текстов так и не завезли)

2022-04-27 10:03 UTC, kolebayevv commented on src/app/features/liquidity-providing/components/transfer-modal/transfer-modal.component.ts
> +    return undefined;
removed

2022-04-27 10:03 UTC, kolebayevv commented on src/app/features/liquidity-providing/services/liquidity-providing-modals.service.ts
> +  showDepositModal(amount: BigNumber): Observable<boolean> {
done

2022-04-27 10:05 UTC, kolebayevv commented on src/app/features/liquidity-providing/services/liquidity-providing-notification.service.ts
> +      status: TuiNotification.Success,
done

2022-04-27 10:09 UTC, kolebayevv commented on src/app/features/staking-lp/components/lp-card/lp-card.component.ts
> +  @Output() onNavigate = new EventEmitter<number>();
done

2022-04-27 10:09 UTC, kolebayevv commented on src/app/features/staking-lp/components/staking-card/staking-card.component.ts
> +  @Output() onNavigate = new EventEmitter<number>();
done

2022-04-27 10:09 UTC, kolebayevv commented on src/app/features/staking-lp/components/staking-card/staking-card.component.ts
> +    return undefined;
removed

2022-04-27 10:10 UTC, kolebayevv commented on src/app/features/staking-lp/components/staking-lp-page/staking-lp-page.component.ts
> +    this.walletConnectorService.addressChange$
done

2022-04-27 10:11 UTC, kolebayevv commented on src/app/features/staking-lp/components/statistics/statistics.component.ts
> +    this.walletConnectorService.addressChange$
done

2022-04-27 10:11 UTC, kolebayevv commented on src/app/features/staking-lp/components/statistics/statistics.component.ts
> +        this.cdr.detectChanges();
TODO оставил в одном месте с таким вызовом

2022-04-27 10:16 UTC, axtezy approved these changes

2022-04-27 10:49 UTC, ottebrut approved these changes

2022-04-27 11:27 UTC, merged