Feature/perfomance updates
Cryptorubic/rubic-app pull request #1318
Opened 2022-04-08 13:03 UTC by ottebrut

2022-04-08 14:51 UTC, axtezy requested changes

2022-04-08 14:51 UTC, axtezy commented on src/app/core/header/components/header/components/user-profile/user-profile.component.ts
>      this._onNetworkChanges$ = this.walletConnectorService.networkChange$.subscribe(network => {
destroy$ заинжектил но не использовал

2022-04-08 14:51 UTC, axtezy commented on src/app/core/services/notifications/notifications.service.ts
> +      autoClose: options?.autoClose ?? 15000
Давай все тайминги по нотификациям в константы выделим.
У нас их всего 2 вроде, 5000 и 15000

2022-04-08 14:51 UTC, axtezy commented on src/app/features/instant-trade/components/instant-trade-bottom-form/instant-trade-bottom-form.component.html
> +                wrapProvider ? getUsdPriceOfToAmount(fromAmount) : getUsdPriceOfToAmount()
`FunctionCallPipe`

2022-04-08 14:51 UTC, axtezy commented on src/app/features/instant-trade/components/instant-trade-bottom-form/instant-trade-bottom-form.component.html
> +                wrapProvider ? getUsdPriceOfToAmount(fromAmount) : getUsdPriceOfToAmount()
`FunctionCallPipe`

2022-04-08 14:51 UTC, axtezy commented on src/app/features/instant-trade/components/providers-panels/components/provider-panel/panel-content/panel-content.component.html
> +        {{ tradePanelData.gasFeeInEth.toFixed(5) }} ETH
`FunctionCallPipe`

По идее нам надо вообще везде перестать использовать и геттеры и функции и методы объектов в темплейтах, так как даже при `onPush` стратегии, все метода/гетеры вызываются еще раз при каждом `changeDetection`.  Либо в `ngOnChanges` вычислять свойство, либо `FunctionCallPipe` использовать

2022-04-08 14:51 UTC, axtezy commented on src/app/features/instant-trade/components/providers-panels/components/providers-panels-container/providers-panels-container.component.html
> +    *ngFor="let providerData of providersData.slice(0, 3); let i = index"
`FunctionCallPipe` на slice, `trackBy` можно повесить

2022-04-08 14:51 UTC, axtezy commented on src/app/features/instant-trade/services/instant-trade-service/instant-trade-providers.service.ts
> +  providedIn: 'root'
В instant-trades модуль не получится?

2022-04-11 09:23 UTC, ottebrut commented on src/app/features/instant-trade/components/instant-trade-bottom-form/instant-trade-bottom-form.component.html
> +                wrapProvider ? getUsdPriceOfToAmount(fromAmount) : getUsdPriceOfToAmount()
Если добавить, то цена в долларах перестанет обновляться

2022-04-11 09:26 UTC, ottebrut commented on src/app/features/instant-trade/components/providers-panels/components/providers-panels-container/providers-panels-container.component.html
> +    *ngFor="let providerData of providersData.slice(0, 3); let i = index"
на 5 элементов не нужен trackBy

2022-04-11 09:34 UTC, ottebrut commented on src/app/features/instant-trade/components/instant-trade-bottom-form/instant-trade-bottom-form.component.html
> +                wrapProvider ? getUsdPriceOfToAmount(fromAmount) : getUsdPriceOfToAmount()
Можно отдельно завести переменную toUsdPrice, но в следующий раз

2022-04-11 11:36 UTC, ottebrut commented on src/app/features/instant-trade/components/instant-trade-bottom-form/instant-trade-bottom-form.component.html
> +                wrapProvider ? getUsdPriceOfToAmount(fromAmount) : getUsdPriceOfToAmount()
выше написал

2022-04-11 11:41 UTC, axtezy approved these changes

2022-04-11 13:30 UTC, merged