Add near stable pools
Cryptorubic/rubic-app pull request #1337
Opened 2022-04-15 10:26 UTC by axtezy

2022-04-15 11:53 UTC, ottebrut requested changes

2022-04-15 11:53 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/near/ref-finance-service/ref-finance.service.ts
> +      setTimeout(() => resolve(''), 5000);
Почему 5? Зачем вообще какое то время устанавливать?

2022-04-15 12:28 UTC, axtezy commented on src/app/features/instant-trade/services/instant-trade-service/providers/near/ref-finance-service/ref-finance.service.ts
> +      setTimeout(() => resolve(''), 5000);
Так то да, поправил

2022-04-15 12:30 UTC, ottebrut approved these changes

2022-04-18 14:06 UTC, kolebayevv approved these changes

2022-04-19 13:03 UTC, merged