Feature/new analytics
Cryptorubic/rubic-app pull request #1365
Opened 2022-04-25 14:25 UTC by Doctor-Cyclone

Поправил аналитику после успешного совершения одного из действий - swap, bridge, multi-chain swap.
Добавил код для аналитики по клику на кнопку “Buy RBC” и при создании партнерской ссылки на странице приложения /promotion.

2022-04-25 15:12 UTC, ottebrut requested changes

2022-04-25 15:12 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/near/ref-finance-service/ref-finance.service.ts
> +            this.gtmService.fireTxSignedEvent(
```
// @TODO fix revenue near
this.gtmService.fireTxSignedEvent(
```

2022-04-25 15:30 UTC, Doctor-Cyclone commented on src/app/features/bridge/components/bridge-bottom-form/bridge-bottom-form.component.ts
> +        price
Исправил.

2022-04-25 15:30 UTC, Doctor-Cyclone commented on src/app/features/cross-chain-routing/services/cross-chain-routing-service/cross-chain-routing.service.ts
> +      ),
Исправил.

2022-04-25 15:30 UTC, Doctor-Cyclone commented on src/app/features/instant-trade/services/instant-trade-service/providers/near/ref-finance-service/ref-finance.service.ts
> +            this.gtmService.fireTxSignedEvent(
Исправил.

2022-04-26 09:25 UTC, ottebrut approved these changes

2022-04-27 11:09 UTC, axtezy approved these changes

2022-04-27 15:31 UTC, merged