cbridge integration
Cryptorubic/rubic-app pull request #1376
Opened 2022-04-28 07:25 UTC by kolebayevv

Integration of cbridge into current cross-chain for two networks

2022-04-29 10:10 UTC, axtezy requested changes

2022-04-29 10:10 UTC, axtezy commented on src/app/features/cross-chain-routing/services/cross-chain-routing-service/cross-chain-routing.service.ts
> +export interface IndexedTradeAndToAmount {
Надо вынести в отдельный файл, если интерфейс стал экспортируемым

2022-04-29 10:10 UTC, axtezy commented on src/app/features/cross-chain-routing/services/cross-chain-routing-service/cross-chain-routing.service.ts
> +        spenderAddress: this.shouldSwapViaCeler ? celerContractAddress : ccrContractAddress
В нескольких местах используется, можно геттер сделать `contractAddress` и в нем уже проверять `this.shouldSwapViaCeler` и правильный адрес контракта возвращать

2022-04-29 10:10 UTC, axtezy commented on src/app/features/cross-chain-routing/services/cross-chain-routing-service/cross-chain-routing.service.ts
> +    const toAmountWithoutSlippage1 = compareAddresses(fromToken.address, fromTransitToken.address)
1 убрать

2022-04-29 10:10 UTC, axtezy commented on src/app/features/cross-chain-routing/services/cross-chain-routing-service/cross-chain-routing.service.ts
> +          return !this.contracts[blockchain].isProviderOneinch(providerIndex);
Тудашку добавить про инч

2022-04-29 12:50 UTC, kolebayevv commented on src/app/features/cross-chain-routing/services/cross-chain-routing-service/celer/celer.service.ts
> +export interface CelerTrade {
removed export

2022-04-29 12:51 UTC, kolebayevv commented on src/app/features/cross-chain-routing/services/cross-chain-routing-service/celer/celer.service.ts
> +const EMPTY_DATA = '0x';
done

2022-04-29 12:52 UTC, kolebayevv commented on src/app/features/cross-chain-routing/services/cross-chain-routing-service/celer/celer.service.ts
> +    return CELER_CONTRACT[blockchain];
getter cannot have input arguments

2022-04-29 12:52 UTC, kolebayevv commented on src/app/features/cross-chain-routing/services/cross-chain-routing-service/cross-chain-routing.service.ts
> +          return !this.contracts[blockchain].isProviderOneinch(providerIndex);
done

2022-04-29 12:55 UTC, kolebayevv commented on src/app/features/cross-chain-routing/services/cross-chain-routing-service/celer/celer-api.service.ts
> +    let params = new HttpParams()
done

2022-04-29 12:55 UTC, kolebayevv commented on src/app/features/cross-chain-routing/services/cross-chain-routing-service/celer/celer-api.service.ts
> +      .append('src_chain_id', src_chain_id)
done

2022-04-30 12:10 UTC, kolebayevv commented on src/app/features/cross-chain-routing/services/cross-chain-routing-service/cross-chain-routing.service.ts
> +    const toAmountWithoutSlippage1 = compareAddresses(fromToken.address, fromTransitToken.address)
done

2022-04-30 14:28 UTC, axtezy approved these changes

2022-04-30 15:59 UTC, merged