Check for enough liquidity f
Cryptorubic/rubic-app pull request #1398
Opened 2022-05-11 09:06 UTC by kolebayevv

2022-05-13 08:38 UTC, axtezy requested changes

2022-05-13 08:38 UTC, axtezy commented on src/app/features/swaps/features/cross-chain-routing/services/cross-chain-routing-service/cross-chain-routing.service.ts
> +          throw new CustomError('Increase slippage tolerance');
Можно в ошибке вывести сколько именно слипаги лучше поставить. т.е. что-то типа ``Slippage tolerance is too low. Minimum value for the trade is ${(celerBridgeSlippage + this.slippageTolerance) * 100 }%``

2022-05-14 15:06 UTC, kolebayevv commented on src/app/features/swaps/features/cross-chain-routing/services/cross-chain-routing-service/cross-chain-routing.service.ts
> +          throw new CustomError('Increase slippage tolerance');
done

2022-05-14 15:32 UTC, axtezy approved these changes

2022-05-14 15:57 UTC, merged