Rubic 382: my trades refactoring
Cryptorubic/rubic-app pull request #1485
Opened 2022-06-09 11:16 UTC by kolebayevv

2022-06-09 11:57 UTC, axtezy commented
> В этом PR:
> 
> * компонент `RecentCrosschainTxComponent`: рендерится внутри модалки, является частью `HeaderModule`
> * рутовый сервис `RecentTradesService`: хранит у себя трейды для текущего подключенного адреса
>   основное публичное API:
>   - `saveTrade()` - функция которая вызывается внутри onTransactionHash колбэка в кросс-чейн сервисе и сохраняет трейд в local storage
>   - `initiateStatusPolling()` - вызывается на инициализации модалки. Возвращает rxjs interval в пайпе которого берутся данные из local storage, преобразуются и сохраняются в `_usersTrades$ `
>   - `usersTrades$` - публичный observable для отрисовки данных в компоненте
>   - `openRecentTradesModal()`
> 
> вопрос который хотелось бы обсудить: `RecentTradesService` сейчас является частью shared модуля, т.к. его апи необходимо вызывать в `cross-chain-routing.service.ts` а также в будущем в шапке платформы для вывода нотификашки с непрочитанными трейдами. Также `RecentCrosschainTxComponent` - декларирован в `HeaderModule`. При этом `recentTradesService` имеет метод `openRecentTradesModal` использует этот компонент и неразрывно с ним связан. В общем вопрос в том как было бы максимально правильно разрулить тут архитектуру, вынести ли это все в отдельный модуль или оставить так - предлагайте

В Shared он не должен быть, все `forRoot` сервисы лежат в `core`, там  `RecentTradesService` лучше и оставить

2022-06-09 11:57 UTC, axtezy requested changes

2022-06-09 11:57 UTC, axtezy commented on src/app/app-routing.module.ts
> +  // {
remove или пояснение когда раскомитить

2022-06-09 11:57 UTC, axtezy commented on src/app/core/header/components/recent-crosschain-tx/recent-crosschain-tx.component.html
> +<div class="title">Recent Crosschain Tx</div>
Переврды бы

2022-06-09 11:57 UTC, axtezy commented on src/app/core/header/components/recent-crosschain-tx/recent-crosschain-tx.component.scss
> +
Лишняя строка

2022-06-09 11:57 UTC, axtezy commented on src/app/core/header/components/recent-crosschain-tx/recent-crosschain-tx.component.ts
> +  public readonly recentTrades$ = this.recentTradesService.usersTrades$.pipe(
Если хочется подождать пока загрузится `initialLoading`, то лучше что-то вроде такого  
```
initialLoading$.pipe(
	first(loading => loading === false)
).switchMap(
	() => this.recentTradesService.usersTrades$
)
```

2022-06-09 11:57 UTC, axtezy commented on src/app/features/swaps/features/cross-chain-routing/services/cross-chain-routing-service/cross-chain-routing.service.ts
> +  private readonly disableRubicCcrForCelerSupportedBlockchains = false;
Почему `false`  стало?

2022-06-09 11:57 UTC, axtezy commented on src/app/shared/services/decode-logs.ts
> +): { name: string; address: string; params: { name: string; type: string; value?: string }[] }[] {
Вынести в тип

2022-06-09 11:57 UTC, axtezy commented on src/app/shared/services/decode-logs.ts
> +  const m = logs.map(logItem => {
Нужны более понятные имена переменных во всей функции

2022-06-09 11:57 UTC, axtezy commented on src/app/shared/services/recent-trades.service.ts
> +  get recentTradesLS(): { [address: string]: RecentTrade[] } {
модификаторы доступа для аксессоров

2022-06-09 11:57 UTC, axtezy commented on src/app/shared/services/recent-trades.service.ts
> +    let currentUsersTrades = [...(this.recentTradesLS?.[address] || [])];
можно const

2022-06-09 11:57 UTC, axtezy commented on src/app/shared/services/recent-trades.service.ts
> +          ? await asyncMap<RecentTrade, UiRecentTrade>(
можно без async/await

2022-06-09 11:58 UTC, kolebayevv commented on src/app/features/swaps/features/cross-chain-routing/services/cross-chain-routing-service/cross-chain-routing.service.ts
> +  private readonly disableRubicCcrForCelerSupportedBlockchains = false;
для тестов рубик трейдов включил его

2022-06-23 14:53 UTC, axtezy requested changes

2022-06-23 14:53 UTC, axtezy commented on src/app/core/recent-trades/components/celer-trade/celer-trade.component.ts
> +export class CelerTradeComponent implements OnInit, OnDestroy {
Логика почти 1 в 1 как rubic-trade, нужно родительский абстрактный класс сделать

2022-06-23 14:53 UTC, axtezy commented on src/app/core/recent-trades/components/celer-trade/celer-trade.component.ts
> +    interval(30000)
Код в хуков лучше в отдельный метод выносить, если там больше пары строк

2022-06-23 14:53 UTC, axtezy commented on src/app/core/recent-trades/components/recent-crosschain-tx/recent-crosschain-tx.component.html
> +<div class="title">Recent Crosschain Tx</div>
Переводов не будет?

2022-06-23 14:53 UTC, axtezy commented on src/app/core/recent-trades/components/rubic-trade/rubic-trade.component.html
> +<ng-container *ngIf="mode === 'table-row'; else mobile">
у селера и рубика шаблоны тоже почти одинаковые, надо бы какой-то дженерик компонент сделать и различия уже в него проецировать, через ngContent/PolymorpheusContent

2022-06-23 14:53 UTC, axtezy commented on src/app/core/recent-trades/services/recent-trades.service.ts
> +    if (statusFrom === RecentTradeStatus.PENDING) {
По строчкам не сравнивал, но есть ощущение, что у рубика и селера эти методы во многом совпадают, если так то лучше в общий метод вынести

2022-06-23 14:53 UTC, axtezy commented on src/app/core/services/symbiosis/symbiosis.service.ts
> +import { Injectable } from '@angular/core';
Почему то файл подтянулся как полностью новый, там что-то менялось?

2022-06-23 14:53 UTC, axtezy commented on src/app/features/swaps/features/cross-chain-routing/components/swap-scheme-modal/swap-scheme-modal.component.html
> +        Transaction completed successfully!
Вроде на такие фразы уже есть переводы

2022-06-23 15:23 UTC, kolebayevv commented on src/app/core/services/symbiosis/symbiosis.service.ts
> +import { Injectable } from '@angular/core';
я его утащил в кор, т.к он рутовый

2022-06-23 15:23 UTC, kolebayevv commented on src/app/core/recent-trades/components/recent-crosschain-tx/recent-crosschain-tx.component.html
> +<div class="title">Recent Crosschain Tx</div>
будут) последним делом добавлю

2022-06-24 09:56 UTC, axtezy requested changes

2022-06-24 09:56 UTC, axtezy commented on src/app/core/recent-trades/components/common-trade/common-trade.component.ts
> +  initTradeDataPolling(): void {
Модификатор доступа

2022-06-24 09:56 UTC, axtezy commented on src/app/core/recent-trades/components/common-trade/common-trade.component.ts
> +  setUiTrade(uiTrade: UiRecentTrade): void {
модификатор доступа

2022-06-24 09:56 UTC, axtezy commented on src/app/core/recent-trades/components/common-trade/common-trade.component.ts
> +    switch (this.trade.crossChainProviderType) {
Лучше все-таки не использовать switch-case
можно сделать `protected abstract getTradeData(): Promise<UiRecentTrade>`, и в каждом дочернем компоненте реализовать метод. Для Rubic он будет возвращать `this.recentTradesService.getCelerTradeData(this.trade);`

Тогда когда у нас добавится новый провайдер, не надо будет в switch че то писать (потому что можно и забыть), тебе сразу IDE скажет, что ты должен для нового провайдера реализовать метод `getTradeData`

2022-06-24 09:56 UTC, axtezy commented on src/app/core/recent-trades/components/symbiosis-trade/symbiosis-trade.component.ts
> +  setUiTrade(uiTrade: UiRecentTrade): void {
Модификатор

2022-06-24 09:56 UTC, axtezy commented on src/app/features/my-trades/constants/blockchains.ts
> +    name: 'BNB',
Он же не BNB, BNB Chain

2022-06-24 09:56 UTC, axtezy commented on src/app/features/swaps/features/cross-chain-routing/components/cross-chain-routing-bottom-form/cross-chain-routing-bottom-form.component.html
> +    <!-- <button (click)="openSwapSchemeModal()">open modal</button> -->
Почему закоментирован?

2022-06-24 10:13 UTC, kolebayevv commented on src/app/features/swaps/features/cross-chain-routing/components/cross-chain-routing-bottom-form/cross-chain-routing-bottom-form.component.html
> +    <!-- <button (click)="openSwapSchemeModal()">open modal</button> -->
а это для тестов чисто

2022-06-24 13:00 UTC, ottebrut commented on src/app/core/recent-trades/models/common-trade.ts
> +      });
кажется должно быть protected

2022-06-24 13:02 UTC, ottebrut commented on src/app/core/services/blockchain/blockchain-adapters/eth-like/web3-public/eth-like-web3-public.ts
> +    return await this.web3.eth.getTransactionReceipt(hash);
await лишний

2022-06-24 13:02 UTC, ottebrut commented on src/app/core/services/blockchain/blockchain-adapters/eth-like/web3-public/eth-like-web3-public.ts
> +    return await this.web3.eth.getBlockNumber();
await лишний

2022-06-24 13:07 UTC, ottebrut commented on src/app/shared/utils/decode-logs.ts
> +export function decodeLogs(abi: AbiItem[], receipt: TransactionReceipt): DecodedLog[] {
добавь tsdoc

2022-06-27 06:41 UTC, axtezy requested changes

2022-06-27 06:41 UTC, axtezy commented on src/app/core/recent-trades/models/common-trade.ts
> +  }
Можно добавить protected хуки прям в абстрактный класс, тогда не придется делать отдельный реализации хуков в дочерних методах и имплементировать интерфейсы

```
ngOnInit {
  this.initTradeDataPolling()
}
```

```
ngOnDestroy {
  this.saveTradeOnDestroy();
}
```

2022-06-27 06:41 UTC, axtezy commented on src/app/features/swaps/features/cross-chain-routing/components/swap-scheme-modal/swap-scheme-modal.component.ts
> +            return this.getSymbiosisDstTxStatus();
Лучше сделать фабрику, которая будет возвращать класс, с методом `getDstTxStatus()`
![2022-06-27 09 39 16](https://user-images.githubusercontent.com/26143325/175875418-2c63b974-af7e-4662-b67e-303d48b13a3f.jpg)
Если не оч понятно - подходи)

2022-06-28 08:13 UTC, kolebayevv commented on src/app/core/recent-trades/models/common-trade.ts
> +  }
если реализовать такие методы внутри общего класса - приложение не сбилдится с ошибкой _"Class is using Angular features but is not decorated. Please add an explicit Angular decorator."_

2022-06-28 08:42 UTC, kolebayevv commented on src/app/core/recent-trades/services/recent-trades.service.ts
> +    if (statusFrom === RecentTradeStatus.PENDING) {
во многом похожи, но в самом важном моменте получения статуса целевой транзы - отличаются. даже если бы они были полностью одинаковые - я бы пока оставил два разных метода, т.к они могут в будущем начать развиваться каждый по-своему или какой-то станет вообще не нужным, поэтому чтоб раньше времени не смешивать две функциональности и не делать методов типа "getRubicOrCelerTradeData"

2022-06-28 09:03 UTC, axtezy commented on src/app/core/recent-trades/models/common-trade.ts
> +  }
Можно пометить как `@Directive`/`@Injectable`/`@Component`
`@Directive` предпочтительнее

2022-06-28 11:11 UTC, axtezy approved these changes

2022-06-28 11:32 UTC, ottebrut approved these changes

2022-06-28 11:32 UTC, merged