Add Rubic SDK to platform
Cryptorubic/rubic-app pull request #1514
Opened 2022-06-24 15:27 UTC by axtezy

Hotfix/fix total value

2022-06-29 09:19 UTC, kolebayevv commented on src/app/features/swaps/features/bridge/services/bridge-service/bridge.service.ts
`const blockchains = Object.values(BLOCKCHAIN_NAME)`

2022-06-29 09:28 UTC, kolebayevv commented on src/app/features/swaps/shared/tokens-select/components/tokens-select/tokens-select.component.ts
> +      [BLOCKCHAIN_NAME.AVALANCHE]: 'avalanchec',
typo avalanche_c_

2022-06-29 09:30 UTC, kolebayevv commented on src/app/shared/utils/utils.ts
> +export function getItSwapParams(trade: InstantTrade | WrapTrade): {
мб это поближе к swaps модулю утащить?

2022-06-29 12:53 UTC, ottebrut requested changes

2022-06-29 12:53 UTC, ottebrut commented on src/app/features/swaps/features/cross-chain-routing/services/cross-chain-routing-service/cross-chain-routing.service.ts
> +  private parseCalculcationError(error: RubicSdkError): RubicError<ERROR_TYPE> {
опечатка

2022-06-30 08:48 UTC, axtezy commented on src/app/shared/utils/utils.ts
> +export function getItSwapParams(trade: InstantTrade | WrapTrade): {
Перенес в it/utils/trade-parser.ts

2022-06-30 08:48 UTC, axtezy commented on src/app/features/swaps/features/cross-chain-routing/services/cross-chain-routing-service/cross-chain-routing.service.ts
>          }
Нужно было в качестве костыля, убрал

2022-07-05 04:47 UTC, kolebayevv approved these changes

2022-07-05 04:49 UTC, kolebayevv approved these changes

2022-07-05 08:05 UTC, ottebrut approved these changes

2022-07-05 10:14 UTC, closed without merging