add staking 3 round statistics
Cryptorubic/rubic-app pull request #1604
Opened 2022-07-24 15:17 UTC by Doctor-Cyclone

2022-07-25 09:37 UTC, axtezy requested changes

2022-07-25 09:37 UTC, axtezy commented on src/app/features/staking-lp/components/stake-form/stake-form.component.html
> +            formControlName="testValue1"
testValue заменить на нормальное название

2022-07-25 09:37 UTC, axtezy commented on src/app/features/staking-lp/components/stake-form/stake-form.component.html
> +            [item]="items[0]"
В компоненте лучше сделать массив

```
durations = [
{
  value: number; // 1,6, ... n
  name: string; // 1 M, 6 M, ... 
}
```

Потом в шаблоне

```
<tui-radio-labeled
  *ngFor="let duration of durations"
  formControlName="..."
  [item]="duration.value"
  (click)="setDuration(duration.value)"
>
  {{ duration.name }}
<tui-radio-labeled>
```

2022-07-25 09:37 UTC, axtezy commented on src/app/features/staking-lp/components/stake-form/stake-form.component.ts
> +  testForm = new FormGroup({
Переименовать и выставить везде модификаторы доступа

2022-07-25 09:37 UTC, axtezy commented on src/app/features/staking-lp/components/stake-form/stake-form.component.ts
> +  readonly min = 1;
Все readonly переменные для слайдера можно в 1 поле вынести, sliderConfig

2022-07-25 09:37 UTC, axtezy commented on src/app/features/staking-lp/components/staking-lp-page/staking-lp-page.component.ts
> +  public showPastStaking(isShow: boolean): void {
если передается `isShow: false` название методо нелогично звучит, нужно toggle

2022-07-25 09:37 UTC, axtezy commented on src/app/features/staking-lp/components/statistics/statistics.component.html
> +              lockedRBC && lockedRBC?.isFinite() ? (lockedRBC | bigNumberFormat: 0:true) : '--.--'
lockedRBC необязательно при optional сhaining (здесь и ниже)

2022-07-25 09:37 UTC, axtezy commented on src/app/features/staking-lp/services/statistics.service.ts
> +  private readonly _updateStatistics$ = new BehaviorSubject<void>(null);
Можно просто Subject

2022-07-25 09:37 UTC, axtezy commented on src/app/features/staking-lp/services/statistics.service.ts
> +      combineLatest([this.lockedRBC$, this.getRBCPrice()]).pipe(
`forkJoin([this.lockedRBC$.pipe(first()), this.getRBCPrice()])`

2022-07-25 09:37 UTC, axtezy commented on src/app/features/staking-lp/services/statistics.service.ts
> +          return lockedRbcAmount.multipliedBy(rbcPrice as number);
При одном return фигурные скобки не нужны (Здесь и ниже)

2022-07-25 09:37 UTC, axtezy commented on src/app/features/staking-lp/services/statistics.service.ts
> +          return lockedRbcAmount.multipliedBy(rbcPrice as number);
Зачем идет приведение к number, если rbcPrice и так должно быть number?

2022-07-25 09:37 UTC, axtezy commented on src/app/features/staking-lp/services/statistics.service.ts
> +          return Web3Pure.fromWei(epochInfo.rewardPerSecond).multipliedBy(604_800);
Что за магические число 604_800?

2022-07-25 09:37 UTC, axtezy commented on src/app/features/staking-lp/services/statistics.service.ts
> +        map(value => value.multipliedBy(new BigNumber(52).dividedBy(this.TOTAL_SUPPLY)))
Что за магическое число 52?

2022-07-25 09:37 UTC, axtezy commented on src/app/features/staking-lp/services/statistics.service.ts
> +    const blockchainAdapter = Injector.web3PublicService.getWeb3Public(
Вынести blockchainAdapter в getter чтобы постоянно не создавать константу

2022-07-25 10:14 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/components/stake-form/stake-form.component.html
> +            formControlName="testValue1"
Готово.

2022-07-25 10:14 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/components/stake-form/stake-form.component.html
> +            [item]="items[0]"
Готово.

2022-07-25 10:14 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/components/stake-form/stake-form.component.ts
> +  testForm = new FormGroup({
Готово.

2022-07-25 10:14 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/components/stake-form/stake-form.component.ts
> +  readonly min = 1;
Готово.

2022-07-25 10:15 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/components/staking-lp-page/staking-lp-page.component.ts
> +  public showPastStaking(isShow: boolean): void {
Готово.

2022-07-25 10:15 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/services/statistics.service.ts
> +          return lockedRbcAmount.multipliedBy(rbcPrice as number);
Готово.

2022-07-25 10:15 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/services/statistics.service.ts
> +          return Web3Pure.fromWei(epochInfo.rewardPerSecond).multipliedBy(604_800);
Готово.

2022-07-25 10:15 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/services/statistics.service.ts
> +        map(value => value.multipliedBy(new BigNumber(52).dividedBy(this.TOTAL_SUPPLY)))
В документации это просто число, без пояснений.

2022-07-25 10:15 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/services/statistics.service.ts
> +    const blockchainAdapter = Injector.web3PublicService.getWeb3Public(
Готово.

2022-07-26 09:43 UTC, axtezy commented on src/app/features/staking-lp/services/statistics.service.ts
> +        map(value => value.multipliedBy(new BigNumber(52).dividedBy(this.TOTAL_SUPPLY)))
Это количество недель в году
Надо вынести в константу

2022-07-26 10:44 UTC, axtezy requested changes

2022-07-26 10:44 UTC, axtezy commented on src/app/features/staking-lp/components/statistics/statistics.component.ts
>    public readonly stakingRewards$ = this.stakingLpService.stakingRewards$;
Удалить ненужные поля

2022-07-26 10:44 UTC, axtezy commented on src/app/features/staking-lp/components/statistics/statistics.component.ts
> +    // this.stakingLpService
удалтиь коменты

2022-07-26 10:44 UTC, axtezy commented on src/app/features/staking-lp/services/statistics.service.ts
> +  private readonly TOTAL_SUPPLY = new BigNumber(124_000_000);
поля в обычном начертании

2022-07-26 10:44 UTC, axtezy commented on src/app/features/staking-lp/components/stake-form/stake-form.component.ts
> +    durationForm: new FormControl(this.durations[1].name)
durationForm переименовать на duration, потому что ёто не форма, а control
+ Прочитать вот это https://angular.io/guide/reactive-forms

2022-07-26 11:46 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/components/deposits/components/deposit/deposit.component.scss
> +    background: #202622;
Готово.

2022-07-26 11:46 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/components/stake-form/stake-form.component.ts
> +    durationForm: new FormControl(this.durations[1].name)
Готово.

2022-07-26 11:46 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/services/statistics.service.ts
> +  private readonly TOTAL_SUPPLY = new BigNumber(124_000_000);
Готово.

2022-07-26 11:46 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/components/statistics/statistics.component.ts
> +    // this.stakingLpService
Готово.

2022-07-26 11:46 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/components/statistics/statistics.component.ts
>    public readonly stakingRewards$ = this.stakingLpService.stakingRewards$;
Готово.

2022-07-26 11:46 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/components/stake-form/stake-form.component.ts
> +  readonly steps = (this.sliderConfig.max - this.sliderConfig.min) / this.sliderConfig.sliderStep;
Готово.

2022-07-26 11:46 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/components/stake-form/stake-form.component.ts
> +    control: new FormControl(this.duration.month)
Готово.

2022-07-26 11:46 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/components/stake-form/stake-form.component.ts
> +  readonly sliderConfig = {
Готово.

2022-07-26 11:46 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/components/stake-form/stake-form.component.ts
> +  public durations: { value: number; name: string; selected: boolean }[] = [
Готово.

2022-07-26 11:46 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/components/deposits/deposits.component.scss
> +  border-radius: 24px;
Готово.

2022-07-26 11:46 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/components/deposits/deposits.component.scss
> +.deposits__wrapper {
Готово.

2022-07-26 11:46 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/components/deposits/deposits.component.html
> +      <span class="deposits__title-text">Your Deposits</span>
Готово.

2022-07-26 11:47 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/components/deposits/components/deposit/deposit.component.scss
> +    border-radius: 100px;
Готово.

2022-07-26 11:47 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/components/deposits/components/deposit/deposit.component.scss
> +    //@include b(410) {
Готово.

2022-07-26 11:47 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/components/deposits/components/deposit/deposit.component.scss
> +    @include b(850) {
Часть заменил, в остальных ни как без них.

2022-07-28 06:04 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/components/statistics/statistics.component.html
> +              lockedRBC && lockedRBC?.isFinite() ? (lockedRBC | bigNumberFormat: 0:true) : '--.--'
Готово.

2022-07-28 06:05 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/services/statistics.service.ts
> +  private readonly _updateStatistics$ = new BehaviorSubject<void>(null);
Оставили как есть.

2022-07-28 06:05 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/services/statistics.service.ts
> +      combineLatest([this.lockedRBC$, this.getRBCPrice()]).pipe(
Готово.

2022-07-28 06:05 UTC, Doctor-Cyclone commented on src/app/features/staking-lp/services/statistics.service.ts
> +        map(value => value.multipliedBy(new BigNumber(52).dividedBy(this.TOTAL_SUPPLY)))
Готово.

2022-08-04 12:04 UTC, axtezy requested changes

2022-08-04 12:36 UTC, kolebayevv commented on src/app/features/earn/components/withdraw-modal/withdraw-modal.component.ts
> +    this.amount = this.context.data.amount;
done

2022-08-04 12:36 UTC, kolebayevv commented on src/app/features/earn/components/stake-form/stake-form.component.ts
> +  public onAmountChange(rbcAmount: string): void {
done

2022-08-04 12:36 UTC, kolebayevv commented on src/app/features/earn/components/new-position-modal/new-position-modal.component.ts
> +    this.amount = this.context.data.amount;
done

2022-08-04 12:36 UTC, kolebayevv commented on src/app/features/earn/components/deposits/deposits.component.html
> +                <th class="tui-table__th">NFT ID</th>
done

2022-08-04 12:36 UTC, kolebayevv commented on src/app/features/earn/components/claim-modal/claim-modal.component.ts
> +    this.rewards = this.context.data.rewards;
done

2022-08-05 06:19 UTC, kolebayevv commented on src/app/features/earn/components/stake-form/stake-form.component.ts
> +      Math.trunc((blockTimestamp * 1000 + duration * 30 * 86400 * 1000) / 604800000) * 604800 * 1000
done

2022-08-05 06:41 UTC, kolebayevv commented on src/app/features/earn/constants/REWARDS_CONTRACT_ABI.ts
> +    type: 'constructor'
done

2022-08-05 08:08 UTC, kolebayevv commented on src/app/features/earn/components/deposits/deposits.component.html
> +<ng-container *ngLet="deposits$ | async as deposits">
done

2022-08-05 08:09 UTC, kolebayevv commented on src/app/features/earn/components/deposits/deposits.component.scss
> +@use 'src/scss/core' as *;
done

2022-08-05 11:09 UTC, kolebayevv commented on src/app/features/earn/components/deposits/deposits.component.html
> +              <ng-container *ngFor="let deposit of deposits">
done

2022-08-05 11:19 UTC, axtezy approved these changes

2022-08-05 11:21 UTC, merged