Rubic 627/staking backlog
Cryptorubic/rubic-app pull request #1645
Opened 2022-08-09 11:22 UTC by Doctor-Cyclone

2022-08-09 12:01 UTC, axtezy requested changes

2022-08-09 12:01 UTC, axtezy commented on src/app/features/earn/components/desktop-deposits/desktop-deposits.component.html
> +              !deposit.totalNftRewards.isZero()
Вложенных тернарников быть не должно, лучше какой-то геттер сделать

2022-08-10 08:02 UTC, kolebayevv reviewed
remove console

2022-08-10 14:11 UTC, Doctor-Cyclone commented on src/app/app-routing.module.ts
> +    canActivate: [TimeGuard]
Готово.

2022-08-10 14:11 UTC, Doctor-Cyclone commented on src/app/features/earn/components/desktop-deposits/desktop-deposits.component.html
> +              !deposit.totalNftRewards.isZero()
Готово.

2022-08-11 10:28 UTC, axtezy requested changes

2022-08-11 10:28 UTC, axtezy commented on src/app/features/earn/services/staking.service.ts
> -        console.log('allowance', allowance.toNumber());
Можно без фигурных скобок

2022-08-11 10:33 UTC, axtezy approved these changes

2022-08-11 11:03 UTC, merged