RUBIC-427 & RUBIC-572: handle lowercase token param & filter already selected token in tokens search query result
Cryptorubic/rubic-app pull request #1672
Opened 2022-08-25 12:51 UTC by kolebayevv

2022-08-26 13:41 UTC, axtezy requested changes

2022-08-26 13:41 UTC, axtezy commented on src/app/features/swaps/features/instant-trade/components/instant-trade-bottom-form/instant-trade-bottom-form.component.ts
> +              console.log({ instantTrades });
убрать

2022-08-26 13:42 UTC, kolebayevv commented on src/app/features/swaps/features/instant-trade/components/instant-trade-bottom-form/instant-trade-bottom-form.component.ts
> +              console.log({ instantTrades });
done

2022-08-29 06:18 UTC, axtezy requested changes

2022-08-29 06:18 UTC, axtezy commented on src/app/features/swaps/shared/tokens-select/components/tokens-select/tokens-select.component.ts
> +                  ? oppositeSelectedToken.address.toLocaleLowerCase() !==
Можно проще
`this.isCrossChainSwap() || oppositeSelectedToken.address.toLocaleLowerCase() !== el.address.toLocaleLowerCase()`

В целом, лучше проверки через отрицание не проводить, а на основе правдивого условия проверки строить

2022-08-29 06:23 UTC, kolebayevv commented on src/app/features/swaps/shared/tokens-select/components/tokens-select/tokens-select.component.ts
> +                  ? oppositeSelectedToken.address.toLocaleLowerCase() !==
done

2022-08-29 06:24 UTC, axtezy approved these changes

2022-08-29 14:12 UTC, merged