dev -> master bugfixes
Cryptorubic/rubic-app pull request #1676
Opened 2022-08-29 14:13 UTC by kolebayevv

2022-08-29 15:09 UTC, ottebrut requested changes

2022-08-29 15:09 UTC, ottebrut commented on src/app/features/swaps/shared/tokens-select/components/tokens-select/tokens-select.component.ts
> +                    el.address.toLocaleLowerCase()
!compareAddress

2022-08-30 09:36 UTC, kolebayevv commented on src/app/features/swaps/shared/tokens-select/components/tokens-select/tokens-select.component.ts
> +                    el.address.toLocaleLowerCase()
done

2022-08-31 08:14 UTC, ottebrut approved these changes

2022-08-31 09:01 UTC, merged