add show receiver address toggle for CCr
Cryptorubic/rubic-app pull request #1709
Opened 2022-09-07 10:38 UTC by Doctor-Cyclone

2022-09-07 10:41 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/cross-chain-routing/components/cross-chain-routing-bottom-form/cross-chain-routing-bottom-form.component.ts
> +    this.settingsService.crossChainRoutingValue.showReceiverAddress;
Удалил в следующем коммите.

2022-09-07 10:58 UTC, axtezy requested changes

2022-09-07 10:58 UTC, axtezy commented on src/app/features/swaps/features/main-form/components/swaps-settings/settings-ccr/settings-ccr.component.ts
> +      this.targetNetworkAddressService.showReceiverAddressToggle(settings.showReceiverAddress);
Зачем?

2022-09-07 10:58 UTC, axtezy commented on src/app/features/swaps/features/cross-chain-routing/components/target-network-address/services/target-network-address.service.ts
> +  public showReceiverAddressToggle(showReceiverAddress: boolean): void {
Зачем?

2022-09-16 12:34 UTC, kolebayevv commented on src/app/features/swaps/features/cross-chain-routing/components/cross-chain-routing-bottom-form/cross-chain-routing-bottom-form.component.ts
> +          if (curr.showReceiverAddress === prevToggleValue) {
`curr` нужно переименовать в `settings`
`return settings.showReceiverAddress === prevToggleValue`

2022-09-16 12:36 UTC, kolebayevv commented on src/app/features/swaps/features/cross-chain-routing/components/target-network-address/services/target-network-address.service.ts
>      this.formService.input.valueChanges
нужна отписка по-хорошему

2022-09-16 13:11 UTC, axtezy approved these changes

2022-09-16 13:18 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/cross-chain-routing/components/cross-chain-routing-bottom-form/cross-chain-routing-bottom-form.component.ts
> +          if (curr.showReceiverAddress === prevToggleValue) {
Done.

2022-09-16 13:18 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/cross-chain-routing/components/target-network-address/services/target-network-address.service.ts
>      this.formService.input.valueChanges
Done.

2022-09-16 13:21 UTC, merged