RUBIC-714: change refresh button flow
Cryptorubic/rubic-app pull request #1718
Opened 2022-09-09 13:59 UTC by kolebayevv

2022-09-12 10:31 UTC, axtezy requested changes

2022-09-12 10:31 UTC, axtezy commented on src/app/shared/components/rubic-refresh-button/rubic-refresh-button.component.html
> -    [tuiHint]="refreshIconTooltip"
Тултип можно оставить, но другой какой-то вписать

2022-09-12 10:31 UTC, axtezy commented on src/app/shared/components/rubic-refresh-button/rubic-refresh-button.component.html
> -    [ngClass]="{ autoRefresh: autoUpdate && !stopAnimation }"
а stopAnimation куда делась? Или не нужна сейчас

2022-09-12 16:32 UTC, kolebayevv commented on src/app/shared/components/rubic-refresh-button/rubic-refresh-button.component.html
> -    [ngClass]="{ autoRefresh: autoUpdate && !stopAnimation }"
да она использовалась чтобы остановить анимацию таймера который показывает сколько осталось до следущего обновления при наведении чтоб показать кнопку play/pause

2022-09-13 13:44 UTC, axtezy approved these changes

2022-09-13 14:49 UTC, merged