Feature/add qp for landing providers
Cryptorubic/rubic-app pull request #1744
Opened 2022-09-20 12:59 UTC by Doctor-Cyclone

2022-09-22 14:07 UTC, axtezy requested changes

2022-09-22 14:07 UTC, axtezy commented on src/app/core/services/query-params/query-params.service.ts
> +        await this.rubicSdkService.SDK.updateConfiguration({
patchConfig использовать

2022-09-22 14:07 UTC, axtezy commented on src/app/features/swaps/core/services/rubic-sdk-service/rubic-sdk.service.ts
> +  public get SDK(): SDK {
вернуть private

2022-09-22 14:07 UTC, axtezy commented on src/app/features/swaps/features/instant-trade/components/instant-trade-bottom-form/instant-trade-bottom-form.component.ts
> +    // if (this.queryParamsService.enabledBlockchains) {
удалить комменты

2022-09-22 14:51 UTC, Doctor-Cyclone commented on src/app/core/services/query-params/models/query-params.ts
> +  enableBlockchains: BlockchainName[];
Поправил.

2022-09-22 14:51 UTC, Doctor-Cyclone commented on src/app/core/services/query-params/query-params.service.ts
> +        await this.rubicSdkService.SDK.updateConfiguration({
Поправил.

2022-09-22 14:51 UTC, Doctor-Cyclone commented on src/app/features/swaps/core/services/rubic-sdk-service/rubic-sdk.service.ts
> +  public get SDK(): SDK {
Поправил.

2022-09-22 14:51 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/instant-trade/components/instant-trade-bottom-form/instant-trade-bottom-form.component.ts
> +    // if (this.queryParamsService.enabledBlockchains) {
Поправил.

2022-09-23 13:39 UTC, axtezy approved these changes

2022-09-23 14:00 UTC, merged