Feature/cross chain form update
Cryptorubic/rubic-app pull request #1869
Opened 2022-10-31 07:58 UTC by ottebrut

2022-11-09 12:22 UTC, axtezy requested changes

2022-11-09 12:22 UTC, axtezy commented on src/app/features/swaps/features/swaps-form/components/swaps-settings/settings-it/settings-it.component.html
> +      <dive
div

2022-11-09 12:22 UTC, axtezy commented on src/app/features/swaps/shared/components/token-amount-estimated/to-amount-estimated.component.ts
> +    startWith(this.swapFormService.inputValue),
На 1 и тот же обсерверер дважды лучше не подписываться в компоненте, можно 1 подписку `toTokenData$` сделать, где будет и децималс и блокчейн

2022-11-09 21:46 UTC, ottebrut commented on src/app/features/swaps/core/services/refresh-service/refresh.service.ts
> +  providedIn: 'root'
исправил

2022-11-09 21:46 UTC, ottebrut commented on src/app/features/swaps/features/swaps-form/components/swaps-settings/settings-it/settings-it.component.html
> +      <dive
исправил

2022-11-09 21:47 UTC, ottebrut commented on src/app/features/swaps/shared/components/token-amount-estimated/to-amount-estimated.component.ts
> +    startWith(this.swapFormService.inputValue),
исправил

2022-11-10 09:14 UTC, axtezy approved these changes

2022-11-10 09:19 UTC, merged