fetch imported token balance after confirm
Cryptorubic/rubic-app pull request #1879
Opened 2022-11-02 11:27 UTC by kolebayevv

2022-11-08 11:00 UTC, ottebrut commented on src/app/features/swaps/features/cross-chain-routing/components/cross-chain-routing-bottom-form/cross-chain-routing-bottom-form.component.ts
> +    // }
Вернешь?

2022-11-08 15:59 UTC, kolebayevv commented on src/app/features/swaps/features/cross-chain-routing/components/cross-chain-routing-bottom-form/cross-chain-routing-bottom-form.component.ts
> +    // }
da

2022-11-10 15:15 UTC, axtezy requested changes

2022-11-10 15:15 UTC, axtezy commented on src/app/features/swaps/shared/components/tokens-select/components/custom-token/custom-token.component.ts
> +      .subscribe(async confirm => {
лучше в switchTap добавить, async в подписке не оч выглядит

2022-11-10 15:15 UTC, axtezy commented on src/app/features/swaps/shared/settings-warning-modal/settings-warning-modal.component.scss
> +}
Нет новой строчки, странно что линтер пропустил

2022-11-11 06:35 UTC, kolebayevv commented on src/app/features/swaps/shared/settings-warning-modal/settings-warning-modal.component.scss
> +}
done

2022-11-11 06:36 UTC, kolebayevv commented on src/app/features/swaps/shared/components/tokens-select/components/custom-token/custom-token.component.ts
> +      .subscribe(async confirm => {
сделал обычным свичмапом

2022-11-11 08:23 UTC, axtezy approved these changes

2022-11-11 08:24 UTC, axtezy approved these changes

2022-11-11 08:28 UTC, merged