RUBIC-837: add default tokens
Cryptorubic/rubic-app pull request #1895
Opened 2022-11-08 09:32 UTC by kolebayevv

2022-11-15 09:09 UTC, axtezy requested changes

2022-11-15 09:09 UTC, axtezy commented on src/app/core/services/backend/tokens-api/tokens-api.service.ts
> +              .filter(i => i.length > 0)
i на tokens

2022-11-15 09:09 UTC, axtezy commented on src/app/core/services/backend/tokens-api/tokens-api.service.ts
> +              .flatMap(el => el)
просто flat

2022-11-15 09:33 UTC, kolebayevv commented on src/app/core/services/backend/tokens-api/tokens-api.service.ts
> +              .filter(i => i.length > 0)
done

2022-11-15 09:33 UTC, kolebayevv commented on src/app/core/services/backend/tokens-api/tokens-api.service.ts
> +              .flatMap(el => el)
done

2022-11-16 11:15 UTC, ottebrut approved these changes

2022-11-16 11:18 UTC, ottebrut commented on src/app/core/services/backend/tokens-api/tokens-api.service.ts
> +  public needRefetchTokens: boolean;
по хорошему, нужно сделать ее private, и перенести в сервис функцию `checkAndRefetchTokenList`, которая внутри будет проверять значение этой переменной

2022-11-16 12:20 UTC, merged