Add oasis and metis networks
Cryptorubic/rubic-app pull request #1905
Opened 2022-11-09 14:10 UTC by Doctor-Cyclone

2022-11-10 12:42 UTC, axtezy requested changes

2022-11-10 12:42 UTC, axtezy commented on src/app/core/services/wallets/wallet-connector-service/constants/default-blockchain-data.ts
> +    rpc: 'https://andromeda.metis.io/?owner=1088'
точно ?owner=1088 должно быть?

2022-11-10 13:12 UTC, axtezy approved these changes

2022-11-15 10:03 UTC, axtezy requested changes

2022-11-15 10:03 UTC, axtezy commented on src/app/features/swaps/features/instant-trade/constants/providers.ts
> +export type NonOnChainNetworks = 'OASIS' | 'METIS' | 'BITGERT' | 'ASTAR' | 'BITCOIN';
В отдельный файл экспортируемые типы

2022-11-15 10:10 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/instant-trade/constants/providers.ts
> +export type NonOnChainNetworks = 'OASIS' | 'METIS' | 'BITGERT' | 'ASTAR' | 'BITCOIN';
Готово.

2022-11-15 10:31 UTC, axtezy approved these changes

2022-11-15 10:40 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/instant-trade/components/instant-trade-bottom-form/instant-trade-bottom-form.component.ts
> +  private isSupportedITNetworks(blockchain: SupportedOnChainNetworks): boolean {
готово.

2022-11-15 10:40 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/instant-trade/components/instant-trade-bottom-form/instant-trade-bottom-form.component.ts
> +      !Object.keys(INSTANT_TRADE_PROVIDERS).includes(this.currentBlockchain) ||
готово.

2022-11-15 10:54 UTC, ottebrut approved these changes

2022-11-15 11:27 UTC, merged