Feature/tokens selector blockchains list
Cryptorubic/rubic-app pull request #1977
Opened 2022-12-05 13:29 UTC by ottebrut

2022-12-06 08:12 UTC, ottebrut commented on src/app/features/swaps/shared/components/tokens-selector/services/blockchains-list-service/blockchains-list.service.ts
> +    let blockchains = blockchainsList;
вынес

2022-12-06 08:12 UTC, ottebrut commented on src/app/features/swaps/shared/components/tokens-selector/services/tokens-selector-opener.service.ts
> +export class TokensSelectorOpenerService {
поправил

2022-12-06 08:13 UTC, ottebrut commented on src/app/features/swaps/shared/components/tokens-selector/services/tokens-selector-service/tokens-selector.service.ts
> +  public _formType: FormType;
private добавил, readonly добавить нельзя, потому что инициализируется не в конструкторе

2022-12-06 08:13 UTC, ottebrut commented on src/app/features/swaps/shared/components/tokens-selector/services/tokens-selector-service/tokens-selector.service.ts
> +  public _form: FormGroup<ISwapFormInput>;
аналогично тому, что выше

2022-12-07 11:21 UTC, kolebayevv requested changes

2022-12-07 11:21 UTC, kolebayevv commented on src/app/features/swaps/shared/components/tokens-selector/components/tokens-list/components/tokens-list-element/tokens-list-element.component.ts
> +  public loadingFavoriteToken: boolean = false;
можно без :boolean, hintShown тоже

2022-12-07 11:21 UTC, kolebayevv commented on src/app/features/swaps/shared/components/tokens-selector/components/tokens-list/tokens-list.component.ts
> +  public get noFrameLink(): string {
кажется тут можно убрать геттер

2022-12-07 11:21 UTC, kolebayevv commented on src/app/features/swaps/shared/components/tokens-selector/services/tokens-list-service/tokens-list-store.service.ts
> +      if (!blockchain) {
`filter(blockchain => Boolean(blockchain)).subsribe(...) `?

2022-12-07 11:21 UTC, kolebayevv commented on src/app/features/swaps/shared/components/tokens-selector/services/tokens-list-service/tokens-list.service.ts
> +    if (this.listScrollSubject$?.value) {
можно без `?`

2022-12-07 11:21 UTC, kolebayevv commented on src/app/features/swaps/shared/components/tokens-selector/services/tokens-selector-service/tokens-selector.service.ts
> +    if (this.selectorListType === 'blockchains') {
я бы сделал тернарным перезапись но тут как по кайфу )

2022-12-07 11:21 UTC, kolebayevv commented on src/app/core/services/widnow-width-service/models/window-size.ts
> +  MOBILE_SM_MIDDLE = 'mobile_ms_middle',
по идее эти значения в нижнем регистре можно не прописывать, 
`enum WindowSize { MOBILE_SM_MIDDLE, ... }` будет эквивалентно `enum WindowSize { MOBILE_SM_MIDDLE = 'MOBILE_SM_MIDDLE', ... }`

2022-12-07 11:21 UTC, kolebayevv commented on src/app/features/swaps/shared/components/tokens-selector/components/blockchains-aside/blockchains-aside.component.ts
> +        return 9;
почему 9?

2022-12-07 11:39 UTC, ottebrut commented on src/app/features/swaps/shared/components/tokens-selector/components/tokens-list/components/tokens-list-element/tokens-list-element.component.ts
> +  public loadingFavoriteToken: boolean = false;
поправил

2022-12-07 11:39 UTC, ottebrut commented on src/app/features/swaps/shared/components/tokens-selector/components/tokens-list/tokens-list.component.ts
> +  public get noFrameLink(): string {
поправил

2022-12-07 11:39 UTC, ottebrut commented on src/app/features/swaps/shared/components/tokens-selector/services/tokens-list-service/tokens-list.service.ts
> +    if (this.listScrollSubject$?.value) {
поправил

2022-12-07 11:39 UTC, ottebrut commented on src/app/core/services/widnow-width-service/models/window-size.ts
> +  MOBILE_SM_MIDDLE = 'mobile_ms_middle',
поправил

2022-12-07 11:53 UTC, ottebrut commented on src/app/features/swaps/shared/components/tokens-selector/components/blockchains-aside/blockchains-aside.component.ts
> +        return 9;
потому что по стилям так

2022-12-07 14:27 UTC, merged