Onramper
Cryptorubic/rubic-app pull request #1990
Opened 2022-12-09 20:27 UTC by ottebrut

2022-12-16 08:59 UTC, axtezy requested changes

2022-12-19 08:40 UTC, ottebrut commented on src/app/core/services/backend/onramper-api/models/onramp-api.ts
> +  out_amount: '0.095961760066900000';
исправил

2022-12-19 08:40 UTC, ottebrut commented on src/app/features/swaps/core/services/settings-service/models/settings-form-controls.ts
> +  autoSlippageTolerance: FormControl<boolean>;
добавил типы `FormControlType<T>` и `FormGroupType<T>`

2022-12-19 08:47 UTC, axtezy approved these changes

2022-12-19 10:51 UTC, axtezy approved these changes

2022-12-19 15:16 UTC, merged