Feature/1inch limit order
Cryptorubic/rubic-app pull request #2057
Opened 2023-01-18 07:59 UTC by ottebrut

2023-01-18 08:56 UTC, axtezy requested changes

2023-01-18 08:56 UTC, axtezy commented on src/app/features/swaps/shared/components/amount-input/components/token-amount-input/token-amount-input.component.scss
> +@use '../../../../../../../../scss/core' as *;
src точно не лучше?)

2023-01-18 14:18 UTC, ottebrut commented on src/app/features/swaps/shared/components/amount-input/components/token-amount-input/token-amount-input.component.scss
> +@use '../../../../../../../../scss/core' as *;
поправил

2023-01-23 08:45 UTC, axtezy approved these changes

2023-02-03 10:33 UTC, axtezy requested changes

2023-02-03 10:33 UTC, axtezy commented on src/app/features/swaps/features/limit-order/components/expiration-optional/expiration-optional.component.ts
> +  @Output() onStateChange = new EventEmitter<void>();
Не вижу эмита ни 1

2023-02-03 10:33 UTC, axtezy commented on src/app/features/swaps/features/limit-order/components/expires-in/expires-in.component.ts
> +        const hours = Math.floor(minutes / 60);
Код с такой логикой лучше выносить в отдельные методы, и читать проще, чем колбаса в pipe и протестить нормально можно

2023-02-03 10:33 UTC, axtezy commented on src/app/features/swaps/features/limit-order/components/order-rate/order-rate.component.scss
> +  --yellow: #f2994a;
вынеси лучше в глобальные переменные, и надо имена дать более осмысленные, типа error-color, warning-color и классы тоже переименовать чтобы семантику улучшить

2023-02-03 10:33 UTC, axtezy commented on src/app/features/swaps/features/limit-order/components/order-rate/order-rate.component.ts
> +  public isUnknown: boolean;
Не очень понятное название, приходится смотреть в место присваивания, чтобы понять для чего нужно

2023-02-03 10:33 UTC, axtezy commented on src/app/features/swaps/features/limit-order/services/limit-order-form.service.ts
> +            switchMap(async fromTokenAmount => {
убрать async
Да и в целом странная конструкция получается со switchMap, который ничего не возвращает, но как бы промис

2023-02-03 10:33 UTC, axtezy commented on src/app/features/swaps/features/limit-order/services/limit-order-form.service.ts
> +      setTimeout(() => this.updateBlockchains());
зачем таймаут?

2023-02-03 10:50 UTC, ottebrut commented on src/app/features/history/limit-orders/components/order-row/order-row.component.ts
> +    if (!this.showCancel) {
вынес

2023-02-03 10:50 UTC, ottebrut commented on src/app/features/history/limit-orders/styles/common.scss
> +@mixin assetImage {
вынес

2023-02-03 10:50 UTC, ottebrut commented on src/app/features/swaps/features/limit-order/components/expiration-optional/expiration-optional.component.ts
> +  @Output() onStateChange = new EventEmitter<void>();
удалил

2023-02-03 10:50 UTC, ottebrut commented on src/app/features/swaps/features/limit-order/components/expires-in/expires-in.component.ts
> +        const hours = Math.floor(minutes / 60);
вынес

2023-02-03 10:51 UTC, ottebrut commented on src/app/features/swaps/features/limit-order/components/order-rate/order-rate.component.scss
> +  --yellow: #f2994a;
вынес

2023-02-03 10:51 UTC, ottebrut commented on src/app/features/swaps/features/limit-order/components/order-rate/order-rate.component.ts
> +  public isUnknown: boolean;
переименовал

2023-02-03 10:52 UTC, ottebrut commented on src/app/features/swaps/features/limit-order/services/limit-order-form.service.ts
> +            switchMap(async fromTokenAmount => {
Внизу await, async не убрать.
switchMap нужен, потому что он отписывается от промиса при пересчете.

2023-02-03 10:54 UTC, ottebrut commented on src/app/features/swaps/features/limit-order/services/limit-order-form.service.ts
> +      setTimeout(() => this.updateBlockchains());
Дело в том, что updateBlockchains может поменять значение в инпуте, и так как работа подписчиков инпутов синхронная, получался неправильный порядок. Поэтому я засунул в таймаут, чтобы сделать код асинхронным и он отработал в следующей фазе.

2023-02-03 11:08 UTC, axtezy requested changes

2023-02-03 11:08 UTC, axtezy commented on src/app/features/swaps/features/limit-order/services/limit-order-form.service.ts
> +            switchMap(async fromTokenAmount => {
Так а зачем он там? Можно типо такого сделать
```
.pipe(
	tap(
            switchIif(
            	fromTokenAmount => {
            		return !this.prevFromTokenAmount ||
                		!compareTokens(this.prevFromTokenAmount, fromTokenAmount) ||
               		!this.prevFromTokenAmount.tokenAmount.eq(fromAmount)
            	},
		fromTokenAmount => this.sdkService.limitOrderManager.needApprove(
                  fromTokenAmount,
                  fromAmount
                ).pipe(tap(() => (this.prevFromTokenAmount = fromTokenAmount)),
                () => of()
            ),
            tap(() => {
            	this.calculating = false;
                if (this.isFormFilled) {
                  this.tradeStatus = this.needApprove
                  ? TRADE_STATUS.READY_TO_APPROVE
                  : TRADE_STATUS.READY_TO_SWAP;
              }
              this._displayApproveButton$.next(this.needApprove);
            })
);
```

2023-02-03 11:21 UTC, axtezy approved these changes

2023-02-03 11:21 UTC, ottebrut commented on src/app/features/swaps/features/limit-order/services/limit-order-form.service.ts
> +            switchMap(async fromTokenAmount => {
поправил

2023-02-03 11:21 UTC, merged