feature(token-security) Add GoPlus token security check
Cryptorubic/rubic-app pull request #2074
Opened 2023-01-31 15:24 UTC by lilchizh

2023-01-31 15:59 UTC, lilchizh commented on src/app/features/swaps/shared/components/assets-selector/components/tokens-list/components/tokens-list-element/tokens-list-element.component.ts
> +  public get isGoPlusAvailable(): boolean {
Согласен

2023-01-31 15:59 UTC, lilchizh commented on src/app/features/swaps/shared/components/assets-selector/components/tokens-list/components/tokens-list-element/tokens-list-element.component.ts
> +  public get isSecured(): boolean {
Согласен :)

2023-01-31 16:16 UTC, axtezy approved these changes

2023-02-02 02:00 UTC, lilchizh commented
Вернул поддерживаемые сети, потому что возникает ситуация, когда для нативки поддерживаемой сети бэкенд присылает такое же значение, как для любого токена в неподдерживаемой. Поэтому, без списка не получается задетектить нативку в неподдерживаемой сети.

2023-02-02 02:03 UTC, lilchizh commented
Вернул поддерживаемые сети, потому что возникает ситуация, когда для нативки поддерживаемой сети бэкенд присылает такое же значение, как для любого токена в неподдерживаемой. Поэтому, без списка не получается задетектить нативку в неподдерживаемой сети.

2023-02-03 09:17 UTC, axtezy approved these changes

2023-02-06 09:20 UTC, axtezy requested changes

2023-02-06 09:20 UTC, axtezy commented on src/app/features/swaps/shared/components/assets-selector/constants/go-plus-available-networks.ts
> +export const GO_PLUS_AVAILABLE_NETWORKS = [
Лучше сразу `export const GO_PLUS_AVAILABLE_NETWORKS: BlockchainName = [...]` писать, без приведения типов

2023-02-06 09:20 UTC, axtezy commented on src/app/shared/models/tokens/token-security.ts
> +  TRUST_LIST = 'trust-list',
Лучше здесь у енума статусы описать, чем в комментах метода

2023-02-06 10:24 UTC, lilchizh commented on src/app/core/services/tokens/tokens.service.ts
> +  public async fetchTokenSecurity(
Мне не очень нравится этот метод. Я пытался под имеющиеся методы его подстроить, но он как-будто бесполезный. Но если представить, что в будущем еще добавится какая-то логика, например поиск по символу, то пусть будет

2023-02-06 10:49 UTC, axtezy approved these changes

2023-02-06 10:49 UTC, axtezy commented on src/app/core/services/tokens/tokens.service.ts
> +  public async fetchTokenSecurity(
Да даже если не появится какой-то логики, то распределение между вызовами апи и получением инфы нужны

Можно еще `address.length >= 42;` заменить на метод из сдк `isAddressCorrect(address, blockchain);` здесь и в остальных методах в файле

2023-02-06 10:49 UTC, axtezy commented on src/app/shared/models/tokens/token-security.ts
>  export enum TokenSecurityStatus {
По JSDoc пояснением к идентификаторам енума над ними надо писать

```
export enum TokenSecurityStatus {
/**
 *  Network is not supported by Go+.
*/
UNSUPPORTED_BLOCKCHAIN = 'unsupported',
...
}
```

https://jsdoc.app/tags-enum.html

2023-02-06 11:41 UTC, merged