RUBIC-1078 fix menu
Cryptorubic/rubic-app pull request #2115
Opened 2023-02-14 14:52 UTC by Doctor-Cyclone

2023-02-15 08:23 UTC, axtezy requested changes

2023-02-15 08:23 UTC, axtezy commented on src/app/core/header/components/header/components/rubic-menu/rubic-menu.component.scss
> +@include b(1140) {
завести переменную, если нет такой

2023-02-16 09:15 UTC, Doctor-Cyclone commented on src/app/core/header/components/header/components/rubic-menu/rubic-menu.component.scss
> +@include b(1140) {
Done.

2023-02-22 10:58 UTC, axtezy approved these changes

2023-02-22 10:58 UTC, axtezy commented on src/app/core/services/wallets/wallet-connector-service/wallet-connector.service.ts
> +        // this.notificationsService.show(switchError.message, {
Убрать коммент

2023-02-22 11:02 UTC, Doctor-Cyclone commented on src/app/core/services/wallets/wallet-connector-service/wallet-connector.service.ts
> +        // this.notificationsService.show(switchError.message, {
Done.

2023-02-22 11:09 UTC, merged