Removed part of changeNow chains
Cryptorubic/rubic-app pull request #2119
Opened 2023-02-16 15:56 UTC by Doctor-Cyclone

2023-02-17 08:42 UTC, axtezy requested changes

2023-02-17 08:42 UTC, axtezy commented on src/app/core/recent-trades/components/trade-row/trade-row.component.ts
> +    this.changenowId = this.getChangenowId();
Можно сразу при инициализации, и сделай геттером

2023-02-17 08:42 UTC, axtezy commented on src/app/core/recent-trades/components/trade-row/trade-row.component.ts
> +    return '';
string | undefined и возвращать undefined

2023-02-17 08:42 UTC, axtezy commented on src/app/features/swaps/features/swap-form/swap-form.component.ts
> +  // public hideTokenSwitcher: boolean;
Убрать

2023-02-17 08:42 UTC, axtezy commented on src/app/features/swaps/features/swap-form/swap-form.component.ts
> +  public get showTokenSwitcher(): boolean {
Оставь @TODO убрать после и условие когда уберем

2023-02-17 08:42 UTC, axtezy commented on src/app/features/swaps/shared/components/assets-selector/services/blockchains-list-service/constants/blockchains-list.ts
> +  // BLOCKCHAIN_NAME.NEM,
Почему закоменчены?

2023-02-17 08:42 UTC, axtezy commented on src/app/features/swaps/shared/components/assets-selector/services/blockchains-list-service/constants/blockchains-list.ts
> +  BLOCKCHAIN_NAME.BITCOIN,
Почему биткоин не в nonEvm?

2023-02-17 08:55 UTC, Doctor-Cyclone commented on src/app/features/swaps/shared/components/assets-selector/services/blockchains-list-service/constants/blockchains-list.ts
> +  // BLOCKCHAIN_NAME.NEM,
Эти сети буду доступны позже.

2023-02-17 08:56 UTC, Doctor-Cyclone commented on src/app/features/swaps/shared/components/assets-selector/services/blockchains-list-service/constants/blockchains-list.ts
> +  BLOCKCHAIN_NAME.BITCOIN,
Этот массив для changeNow сетей, биткоин от туда же?

2023-02-17 09:04 UTC, Doctor-Cyclone commented on src/app/core/recent-trades/components/trade-row/trade-row.component.ts
> +    this.changenowId = this.getChangenowId();
Done.

2023-02-17 09:04 UTC, Doctor-Cyclone commented on src/app/core/recent-trades/components/trade-row/trade-row.component.ts
> +    return '';
Done.

2023-02-17 09:07 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/swap-form/swap-form.component.ts
> +  public get showTokenSwitcher(): boolean {
Done.

2023-02-17 09:11 UTC, axtezy commented on src/app/features/swaps/shared/components/assets-selector/services/blockchains-list-service/constants/blockchains-list.ts
> +  BLOCKCHAIN_NAME.BITCOIN,
Как константа у тебя называется? ChaingeNowNetworks или NotEvm? Биткоин не EVM сеть

2023-02-17 09:14 UTC, axtezy requested changes

2023-02-17 09:14 UTC, axtezy commented on src/app/features/swaps/features/swap-form/swap-form.component.ts
> +  // public hideTokenSwitcher: boolean;
коммент остался

2023-02-17 09:23 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/swap-form/swap-form.component.ts
> +  // public hideTokenSwitcher: boolean;
Done.

2023-02-20 10:50 UTC, axtezy requested changes

2023-02-20 10:50 UTC, axtezy commented on src/app/features/swaps/shared/components/assets-selector/components/tokens-list/components/tokens-list-element/tokens-list-element.component.ts
> +    this.allowCopy = this.token.address !== EMPTY_ADDRESS && this.token.address !== '';
Присвоение при инициализации давай сразу и от хука избавимся

2023-02-21 09:11 UTC, Doctor-Cyclone commented on src/app/features/swaps/shared/components/assets-selector/services/blockchains-list-service/constants/blockchains-list.ts
> +  BLOCKCHAIN_NAME.BITCOIN,
notEvmChangeNowBlockchainsList

2023-02-21 09:15 UTC, axtezy approved these changes

2023-02-21 09:15 UTC, axtezy commented on src/app/core/services/swaps/swap-form-query.service.ts
> +    // if (chainType && Web3Pure[chainType].isAddressCorrect(token)) {
удалить

2023-02-21 09:20 UTC, merged