Feature/native mobile UI
Cryptorubic/rubic-app pull request #2139
Opened 2023-03-07 09:10 UTC by Doctor-Cyclone

2023-03-13 09:48 UTC, axtezy requested changes
Нужно убрать все комменты еще добавленные перед релизом

2023-03-13 09:48 UTC, axtezy commented on src/app/core/header/components/header/components/settings-element/settings-element.component.ts
> +    this.isDark$ = this.themeService.theme$.pipe(map(theme => theme === 'dark'));
Можно сразу при инициализации

2023-03-13 09:48 UTC, axtezy commented on src/app/core/header/components/header/components/settings-toggler/settings-toggler.component.ts
> +    console.log(this.isSettingsOpened);
полезная функция

2023-03-13 09:48 UTC, axtezy commented on src/app/core/header/components/header/components/settings/settings.component.ts
> +  providers: [TuiDestroyService]
Не используется

2023-03-13 09:48 UTC, axtezy commented on src/app/core/modals/components/mobile-native-modal/mobile-native-modal.component.ts
> +    if (this.context.forceClose$) {
Вынести в метод

2023-03-13 09:48 UTC, axtezy commented on src/app/core/recent-trades/components/recent-crosschain-tx/recent-crosschain-tx.component.scss
> +
лишняя строка

2023-03-13 09:48 UTC, axtezy commented on src/app/core/recent-trades/styles/mobile-tx.scss
> +    @include font(14px, 17px, 500, #37373d);
Что а цвета? Использовать уже имеющиеся переменные или создать новые

2023-03-13 09:48 UTC, axtezy commented on src/app/core/services/limit-orders/limit-orders.service.ts
> +        console.log('ORDER', order.fromAmount.toString(), order.toAmount.toString());
Убрать

2023-03-13 09:48 UTC, axtezy commented on src/app/features/swaps/features/cross-chain/components/cross-chain-bottom-form/components/best-trade-panel/components/cross-chain-best-route-mobile/cross-chain-best-route-mobile.component.scss
> +    color: #00e28e;
что за цвет?

2023-03-13 09:48 UTC, axtezy commented on src/app/features/swaps/features/cross-chain/components/cross-chain-bottom-form/components/best-trade-panel/components/trades-list/trades-list.component.scss
> +        background: #00e28e26;
цвет?

2023-03-13 09:48 UTC, axtezy commented on src/app/features/swaps/features/instant-trade/components/providers-panels/components/provider-panel/panel-content/panel-content.component.ts
> +    console.log('trade', this.tradePanelData, this.providerPanelData);
убрать

2023-03-13 09:48 UTC, axtezy commented on src/app/features/swaps/features/instant-trade/components/providers-panels/components/provider-panel/provider-panel.component.ts
> +    if (changes.providerData) {
Лучше сеттер для providerData сделать вместо ngOnChanges

2023-03-13 09:48 UTC, axtezy commented on src/app/features/swaps/features/instant-trade/components/providers-panels/components/providers-panels-container/providers-panels-container.component.ts
> +  public get selectedProvider(): InstantTradeProviderData {
геттеры над конструктором должны быть

2023-03-13 09:48 UTC, axtezy commented on src/app/features/swaps/shared/components/assets-selector/components/asset-types-aside/asset-types-aside.component.html
> +  <div>Test template</div>
тест закончился?

2023-03-13 09:48 UTC, axtezy commented on src/app/features/swaps/shared/components/assets-selector/components/asset-types-aside/asset-types-aside.component.scss
> +        color: #00e28e;
переменная

2023-03-13 09:48 UTC, axtezy commented on src/app/features/swaps/shared/components/assets-selector/components/tokens-list/components/tokens-list-element/tokens-list-element.component.scss
> +        // display: none;
убрать

2023-03-13 09:48 UTC, axtezy commented on src/app/shared/decorators/polymorpheus-input.ts
> +}
новую строку в конце файла

2023-03-13 13:44 UTC, Doctor-Cyclone commented on src/app/core/header/components/header/components/mobile-menu/mobile-menu.component.scss
> +  background-color: #222425;
Done.

2023-03-14 08:31 UTC, Doctor-Cyclone commented on src/app/core/header/components/header/components/mobile-menu/mobile-menu.component.ts
> +    this.swapType$ = this.swapTypeService.swapMode$;
Done.

2023-03-14 08:31 UTC, Doctor-Cyclone commented on src/app/core/header/components/header/components/rubic-menu/models/navigation-list.ts
> +  ['Trade']: [
Done.

2023-03-14 08:32 UTC, Doctor-Cyclone commented on src/app/core/header/components/header/components/rubic-menu/rubic-menu.component.scss
> +      // display: block;
Done.

2023-03-14 08:33 UTC, Doctor-Cyclone commented on src/app/core/header/components/header/components/settings-element/settings-element.component.ts
> +    this.isDark$ = this.themeService.theme$.pipe(map(theme => theme === 'dark'));
Done.

2023-03-14 08:35 UTC, Doctor-Cyclone commented on src/app/core/header/components/header/components/settings-toggler/settings-toggler.component.ts
> +    console.log(this.isSettingsOpened);
Done.

2023-03-14 08:40 UTC, Doctor-Cyclone commented on src/app/core/modals/components/mobile-native-modal/mobile-native-modal.component.ts
> +    if (this.context.forceClose$) {
Done.

2023-03-14 08:40 UTC, Doctor-Cyclone commented on src/app/core/recent-trades/components/recent-crosschain-tx/recent-crosschain-tx.component.scss
> +
Done.

2023-03-14 08:41 UTC, Doctor-Cyclone commented on src/app/core/services/limit-orders/limit-orders.service.ts
> +        console.log('ORDER', order.fromAmount.toString(), order.toAmount.toString());
Done.

2023-03-14 08:41 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/instant-trade/components/providers-panels/components/provider-panel/panel-content/panel-content.component.ts
> +    console.log('trade', this.tradePanelData, this.providerPanelData);
Done.

2023-03-14 08:47 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/instant-trade/components/providers-panels/components/providers-panels-container/providers-panels-container.component.ts
> +  public get selectedProvider(): InstantTradeProviderData {
Done.

2023-03-14 08:47 UTC, Doctor-Cyclone commented on src/app/features/swaps/shared/components/assets-selector/components/asset-types-aside/asset-types-aside.component.html
> +  <div>Test template</div>
Done.

2023-03-14 08:48 UTC, Doctor-Cyclone commented on src/app/shared/decorators/polymorpheus-input.ts
> +}
Done.

2023-03-14 08:56 UTC, Doctor-Cyclone commented on src/app/core/header/components/header/components/mobile-user-profile/mobile-user-profile.component.scss
> +    background-color: #171919;
Done.

2023-03-14 08:56 UTC, Doctor-Cyclone commented on src/app/core/header/components/header/components/mobile-user-profile/mobile-user-profile.component.scss
> +    border: 1px solid #333535;
Done.

2023-03-14 08:58 UTC, Doctor-Cyclone commented on src/app/core/header/components/header/components/rubic-menu/rubic-menu.component.scss
> +      border-bottom: 1px solid #333535;
Done.

2023-03-14 08:59 UTC, Doctor-Cyclone commented on src/app/core/header/components/header/components/settings-element/settings-element.component.html
> +    <div style="display: flex; align-items: center; gap: 15px">
Done.

2023-03-14 09:15 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/cross-chain/components/cross-chain-bottom-form/components/best-trade-panel/components/cross-chain-best-route-mobile/cross-chain-best-route-mobile.component.scss
> +    color: #00e28e;
Done.

2023-03-14 09:16 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/cross-chain/components/cross-chain-bottom-form/components/best-trade-panel/components/trades-list/trades-list.component.scss
> +        background: #00e28e26;
Done.

2023-03-14 09:17 UTC, Doctor-Cyclone commented on src/app/features/swaps/shared/components/assets-selector/components/asset-types-aside/asset-types-aside.component.scss
> +        color: #00e28e;
Done.

2023-03-15 08:39 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/instant-trade/components/providers-panels/components/provider-panel/provider-panel.component.ts
> +    if (changes.providerData) {
Done.

2023-04-04 14:36 UTC, closed without merging