upd modal, added hints
Cryptorubic/rubic-app pull request #2155
Opened 2023-03-23 15:19 UTC by Doctor-Cyclone

2023-04-04 12:24 UTC, axtezy requested changes

2023-04-04 12:24 UTC, axtezy commented on src/app/features/swaps/features/instant-trade/services/instant-trade-service/instant-trade.service.ts
> +      // const userAddress = this.authService.userAddress;
Убрать комменты здесь и ниже

2023-04-04 12:24 UTC, axtezy commented on src/app/features/swaps/features/limit-order/components/expiration-optional/expiration-optional.component.ts
> +    // this.modalService.openExpirationalCustomModal(this.injector);
коммент?

2023-04-04 12:24 UTC, axtezy commented on src/app/features/swaps/features/swap-form/components/swap-info/styles/styles.scss
> +      border-top: 1px solid #2f3030;
что за цвет?

2023-04-04 12:24 UTC, axtezy commented on src/app/features/swaps/shared/components/assets-selector/components/asset-types-aside/asset-types-aside.component.ts
> +      // const asideHeight = this.window.innerHeight - 135;
коммент убрать

2023-04-04 12:24 UTC, axtezy commented on src/app/shared/models/fiats/fiat-asset.ts
> +  decimals?: number;
у `fiatAsset` не может быть decimals

2023-04-04 14:19 UTC, Doctor-Cyclone commented on src/app/core/header/components/header/components/mobile-live-chat/mobile-live-chat.component.ts
> +  // ngOnInit() {}
Done.

2023-04-04 14:19 UTC, Doctor-Cyclone commented on src/app/shared/models/fiats/fiat-asset.ts
> +  decimals?: number;
Done.

2023-04-04 14:19 UTC, Doctor-Cyclone commented on src/app/shared/components/success-modal/swap-and-earn-modal/swap-and-earn-modal.component.ts
> +  public idPrefix: string;
Done.

2023-04-04 14:19 UTC, Doctor-Cyclone commented on src/app/shared/components/success-modal/success-tx-modal/success-tx-modal.component.ts
> +    if (this.isSwapAndEarnSwap) {
Done.

2023-04-04 14:20 UTC, Doctor-Cyclone commented on src/app/shared/components/recent-cross-chain-table/trade-row/trade-row.component.html
> +    <!-- <div>
Done.

2023-04-04 14:20 UTC, Doctor-Cyclone commented on src/app/features/swaps/shared/components/amount-input/components/user-balance-container/user-balance-container.component.scss
> +        color: #00ffa0;
Done.

2023-04-04 14:20 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/limit-order/components/expiration-optional/expiration-optional.component.ts
> +    // this.modalService.openExpirationalCustomModal(this.injector);
Done.

2023-04-04 14:20 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/instant-trade/services/instant-trade-service/instant-trade.service.ts
> +      // const userAddress = this.authService.userAddress;
Done.

2023-04-04 14:20 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/instant-trade/components/providers-panels/components/provider-panel/panel-content/panel-content.component.ts
>      this.displayGas = this.tradePanelData?.blockchain === BLOCKCHAIN_NAME.ETHEREUM;
Done.

2023-04-04 14:20 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/cross-chain/components/swap-scheme-modal/swap-scheme-modal.component.ts
> +    if (this.isSwapAndEarnSwap) {
Done.

2023-04-04 14:20 UTC, Doctor-Cyclone commented on src/app/features/swap-and-earn/components/swap-and-earn-page/swap-and-earn-page.component.html
> +    <p
Done.

2023-04-04 14:20 UTC, Doctor-Cyclone commented on src/app/features/history/limit-orders/components/limit-orders-list/limit-orders-list.component.ts
> +    this.authService.currentUser$.subscribe(() => {
Done.

2023-04-04 14:20 UTC, Doctor-Cyclone commented on src/app/core/header/components/header/components/points-button/points-button.component.html
> +    <span [style]="(isAuth$ | async) ? 'color: #ffffff' : ''">{{ points$ | async }}</span>
Done.

2023-04-04 14:20 UTC, Doctor-Cyclone commented on src/app/core/header/components/header/components/mobile-user-profile/mobile-user-profile.component.ts
> +          map(balance => ({
Done.

2023-04-04 14:20 UTC, Doctor-Cyclone commented on src/app/core/header/components/header/components/mobile-user-profile/mobile-user-profile.component.ts
> +  CROSS_CHAIN,
Done.

2023-04-04 14:21 UTC, Doctor-Cyclone commented on src/app/core/recent-trades/services/recent-trades.service.ts
> +    const fromAmount = isCrossChainRecentTrade(trade)
Done.

2023-04-04 14:21 UTC, Doctor-Cyclone commented on src/app/core/modals/components/mobile-native-modal/mobile-native-modal.component.ts
> +    if (this.context.forceClose$) {
Done.

2023-04-04 14:21 UTC, Doctor-Cyclone commented on src/app/core/header/components/header/components/rubic-menu/models/navigation-list.ts
> +export const MOBILE_NAVIGATION_LIST: { [key in Section]: NavigationItem[] } = {
Done.

2023-04-04 14:21 UTC, Doctor-Cyclone commented on src/app/core/header/components/header/components/mobile-menu/mobile-menu.component.ts
> +    @Inject(DOCUMENT) private document: Document
Done.

2023-04-05 12:00 UTC, axtezy approved these changes

2023-04-05 12:01 UTC, merged