added gtm error counter
Cryptorubic/rubic-app pull request #2251
Opened 2023-04-24 14:34 UTC by Doctor-Cyclone

2023-04-25 14:03 UTC, axtezy requested changes

2023-04-25 14:03 UTC, axtezy commented on src/app/features/swaps/features/cross-chain/services/cross-chain-form-service/cross-chain-form.service.ts
>        }
Лучше тут в else занести просто
`this.gtmService.fireTransactionError('approve-cross-chain-swap-error', error.message);`

2023-04-25 14:05 UTC, axtezy requested changes

2023-04-25 14:05 UTC, axtezy commented on src/app/features/swaps/features/swap-form/components/swap-settings/iframe-settings/iframe-settings.component.ts
> +  public disablingToggleReceiverAddress(): void {
не используется в компоненте, заечм public?

2023-04-25 14:05 UTC, axtezy commented on src/app/features/swaps/features/swap-form/swap-form.component.ts
> +    this.swapFormService.toBlockchain$.subscribe(blockchainName => {
В отдельный метод

2023-04-25 14:08 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/cross-chain/services/cross-chain-form-service/cross-chain-form.service.ts
>        }
Done.

2023-04-25 14:08 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/swap-form/components/swap-settings/iframe-settings/iframe-settings.component.ts
> +  public disablingToggleReceiverAddress(): void {
Done.

2023-04-25 14:09 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/swap-form/swap-form.component.ts
> +    this.swapFormService.toBlockchain$.subscribe(blockchainName => {
Done.

2023-04-26 08:50 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/instant-trade/components/instant-trade-bottom-form/instant-trade-bottom-form.component.ts
> +        this.gtmService.fireTransactionError('approve-on-chain-wap-error', err.message);
Done.

2023-04-26 08:53 UTC, merged