upd debridge api
Cryptorubic/rubic-app pull request #2252
Opened 2023-04-25 13:42 UTC by Doctor-Cyclone

2023-04-28 09:15 UTC, axtezy approved these changes

2023-04-28 09:15 UTC, axtezy commented on src/app/core/services/backend/cross-chain-routing-api/constants/from-backend-cross-chain-providers.ts
> +  dln: CROSS_CHAIN_TRADE_TYPE.DEBRIDGE,
Со Стасом согласовали переименование провайдера на беке?

2023-05-05 08:26 UTC, Doctor-Cyclone commented on src/app/core/services/backend/cross-chain-routing-api/constants/from-backend-cross-chain-providers.ts
> +  dln: CROSS_CHAIN_TRADE_TYPE.DEBRIDGE,
Да.

2023-05-05 09:42 UTC, axtezy requested changes

2023-05-05 09:42 UTC, axtezy commented on src/app/features/swaps/features/cross-chain/services/cross-chain-form-service/cross-chain-form.service.ts
> +      this.errorsService.catch(new TooLowAmountError());
parsedError уже инстанса TooLowAmountError, не нужно ее еще раз создавать

2023-05-10 13:19 UTC, axtezy approved these changes

2023-05-10 14:32 UTC, merged