Eip 1559
Cryptorubic/rubic-app pull request #2297
Opened 2023-05-18 04:01 UTC by lilchizh

2023-05-18 09:11 UTC, axtezy requested changes

2023-05-22 05:54 UTC, lilchizh commented on src/app/core/services/gas-service/gas.service.ts
>          this.httpClient.get('https://ethgasstation.info/api/ethgasAPI.json').pipe(
Убрал этот запрос

2023-05-22 08:00 UTC, axtezy requested changes

2023-05-22 08:00 UTC, axtezy commented on src/app/features/approve-scanner/services/approve-scanner.service.ts
> +      const gasDetails = Boolean(maxPriorityFeePerGas)
`gasService.getGasInfo(blockchain);`

2023-05-25 15:44 UTC, axtezy approved these changes

2023-05-29 11:05 UTC, merged