Polygon bridge
Cryptorubic/rubic-app pull request #231
Opened 2021-04-15 15:47 UTC by ottebrut

2021-04-16 12:48 UTC, siandreev commented
Надо бы подпулиться

2021-04-19 12:16 UTC, siandreev commented
![image](https://user-images.githubusercontent.com/19926323/115234873-33813d80-a122-11eb-959e-1a0ade0f08fb.png)
RBC-<номер тикета>/<описание>

2021-04-19 12:22 UTC, siandreev commented
RBC должен быть первым в выпадающем списке

2021-04-19 12:24 UTC, siandreev commented
![image](https://user-images.githubusercontent.com/19926323/115235798-447e7e80-a123-11eb-9141-4ff7890a4d05.png)
on Matic explorer

2021-04-19 12:26 UTC, siandreev commented
Кнопики явно не `primary-button.component`. Анимацию включаем только после того, как нажмет ок в модальном окне
![Uploading image.png…]()

2021-04-19 12:29 UTC, siandreev commented
вторая сеть по умолчанию — BSC, а не Polygon
![image](https://user-images.githubusercontent.com/19926323/115236464-1188ba80-a124-11eb-80d7-5f1e1c918528.png)

2021-04-22 16:30 UTC, siandreev requested changes
пока посмотрел только bridge.service, сейчас отлучусь на iframe, и продолжу

2021-04-22 16:30 UTC, siandreev commented on src/app/features/bridge-page/services/bridge.service.ts
> +              .find(token => token.address.toLowerCase() === transaction.bscSymbol.toLowerCase())
`address === ethSymbol`?

2021-04-22 16:30 UTC, siandreev commented on src/app/features/bridge-page/services/bridge.service.ts
> +            ).blockchainToken[BLOCKCHAIN_NAME.ETHEREUM].symbol;
`address === symbol?`

2021-04-22 16:30 UTC, siandreev commented on src/app/features/bridge-page/services/bridge.service.ts
>    public async updateTransactionsList(): Promise<void> {
мне кажется, это стоит перенести в bridge-backend service. Не круто сравнивать блокчейны со строками в коде, на прямую не взаимодействующим с бэком

2021-04-23 08:49 UTC, ottebrut commented on src/app/features/bridge-page/services/bridge.service.ts
> +              .find(token => token.address.toLowerCase() === transaction.bscSymbol.toLowerCase())
Для полигона в поле ethSymbol лежит адрес токена в эфире, потому что, в отличии от панамы, в полигоне токены не уникальны по символам

2021-04-23 08:49 UTC, ottebrut commented on src/app/features/bridge-page/services/bridge.service.ts
> +            ).blockchainToken[BLOCKCHAIN_NAME.ETHEREUM].symbol;
ответил выше

2021-04-23 11:10 UTC, ottebrut commented on src/app/features/bridge-page/services/bridge.service.ts
>    public async updateTransactionsList(): Promise<void> {
Теперь парсинг в бэкенд сервисе

2021-04-26 11:04 UTC, siandreev commented on src/app/features/bridge-page/services/bridge.service.ts
> +              .find(token => token.address.toLowerCase() === transaction.bscSymbol.toLowerCase())
))))

2021-04-27 12:52 UTC, merged