TON promo
Cryptorubic/rubic-app pull request #2315
Opened 2023-05-29 08:12 UTC by Doctor-Cyclone

2023-05-29 10:07 UTC, axtezy requested changes

2023-05-29 10:07 UTC, axtezy commented on src/app/features/swaps/features/cross-chain/services/cross-chain-calculation-service/cross-chain-calculation.service.ts
> +    const getData = async (): Promise<SwapSchemeModalData> => {
```
const defaultData: SwapSchemeModalData = {
        fromToken,
        toToken,
        srcProvider: fromTradeProvider,
        dstProvider: toTradeProvider,
        crossChainProvider: calculatedTrade.tradeType,
        srcTxHash: txHash,
        bridgeType: bridgeProvider,
        viaUuid,
        rangoRequestId,
        timestamp,
        amountOutMin,
        changenowId,
	...(tonPromoTrade.isTonPromoTrade && {
		isTonPromoTrade: true,
		points: this.tonPromoService.getTonPromoPointsAmount(
			tonPromoTrade.totalUserConfirmedTrades
		)
	}),
	...(this.isSwapAndEarnSwap(calculatedTrade) && {
		isSwapAndEarnData: true,
		points: await firstValueFrom(this.swapAndEarnStateService.getSwapAndEarnPointsAmount())
	}),
      };
```

Либо 

```
const defaultData = {
        fromToken,
        toToken,
        srcProvider: fromTradeProvider,
        dstProvider: toTradeProvider,
        crossChainProvider: calculatedTrade.tradeType,
        srcTxHash: txHash,
        bridgeType: bridgeProvider,
        viaUuid,
        rangoRequestId,
        timestamp,
        amountOutMin,
        changenowId
}
```

и через ифы вставить в объект поинты

2023-05-29 10:07 UTC, axtezy commented on src/app/features/swaps/features/cross-chain/components/swap-scheme-modal/swap-scheme-modal.component.html
> +    <div class="point" *ngIf="isSwapAndEarnSwap || isTonPromoTrade">
Добавить `ng-container`, на него навесить `ngIf="points > 0"` и внутри уже будут `.point` и `. description_swapAndEarn`
Ну и для `description_swapAndEarn` надо другое название придумать, тк поинты теперь не только у swapAndEearn

2023-05-29 10:31 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/cross-chain/services/ton-promo-service/ton-promo.service.ts
> +    const { is_active, confirmed_rewards_amount } = await firstValueFrom(
Done.

2023-05-29 10:31 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/cross-chain/services/ton-promo-service/ton-promo.service.ts
> +    if (totalUserConfirmedTrades === 0) {
Done.

2023-05-29 10:31 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/cross-chain/components/swap-scheme-modal/swap-scheme-modal.component.html
> +    <div class="point" *ngIf="isSwapAndEarnSwap || isTonPromoTrade">
Done.

2023-05-29 10:31 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/cross-chain/services/cross-chain-calculation-service/cross-chain-calculation.service.ts
> +    const getData = async (): Promise<SwapSchemeModalData> => {
Done.

2023-05-29 10:31 UTC, Doctor-Cyclone commented on src/app/features/swap-and-earn/services/swap-and-earn-state.service.ts
> +        if (points.participant) {
Done.

2023-05-29 10:31 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/cross-chain/services/ton-promo-service/ton-promo.service.ts
> +      return { isTonPromoTrade: false, totalUserConfirmedTrades: 0 };
Done.

2023-05-29 10:45 UTC, axtezy requested changes

2023-05-29 10:45 UTC, axtezy commented on src/app/features/swaps/features/cross-chain/services/ton-promo-service/ton-promo.service.ts
> +  private readonly emptyTonPromoInfo: ShortTonPromoInfo = {
На уровне класса не используется, можно в методе getTonPromoInfo просто в константу поместить

2023-05-29 10:45 UTC, axtezy commented on src/app/features/swaps/features/cross-chain/services/ton-promo-service/ton-promo.service.ts
> +      console.log(
Убрать консоль логи

2023-05-29 10:51 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/cross-chain/services/ton-promo-service/ton-promo.service.ts
> +  private readonly emptyTonPromoInfo: ShortTonPromoInfo = {
Done.

2023-05-29 10:51 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/cross-chain/services/ton-promo-service/ton-promo.service.ts
> +      console.log(
Done.

2023-05-29 10:58 UTC, axtezy approved these changes

2023-05-31 08:13 UTC, axtezy approved these changes

2023-05-31 08:16 UTC, merged