Fix query params
Cryptorubic/rubic-app pull request #246
Opened 2021-04-19 15:20 UTC by axtezy

2021-04-19 16:57 UTC, siandreev requested changes
Надо бы еще в i`nterface QueryParams`
`/Users/siandrev/Documents/www/rubic/rubic_exchange/src/app/core/services/query-params/models/query-params.ts`
наверное стоит поставить `chain?: string;`

2021-04-19 16:57 UTC, siandreev commented on src/app/core/services/query-params/query-params.service.ts
>      };
Вместо хранения в переменных, включающих в свое название символ сети,  лучше хранить такие конфиги как массив объектов, идентифицируя их по названию сети (обязательно как enum `BLOCKCHAIN_NAME`). Либо вместо массива можно сделать объект с ключами = названиями сети.

2021-04-19 16:57 UTC, siandreev commented on src/app/core/services/query-params/query-params.service.ts
> +      }
Это все можно будет упростить, если хранить конфиги сетей в массиве

2021-04-20 08:29 UTC, ottebrut requested changes

2021-04-20 08:29 UTC, ottebrut commented on src/app/features/bridge-page/components/brifge-form/bridge-form.component.ts
> +      }
Это некорректно, так как chain и amount в квери параметрах не зависят от размера листа токенов. К тому же они должны быть настроены один раз в onInit, а не каждый раз, когда меняется массив токенов

2021-04-20 08:30 UTC, ottebrut requested changes

2021-04-20 08:30 UTC, ottebrut commented on src/app/core/services/query-params/query-params.service.ts
> +      chain: 'ethSymbol'
С чем это связано? Почему не поставить BLOCKCHAIN_NAME.ETHEREUM?

2021-04-20 14:22 UTC, siandreev commented on src/app/core/services/query-params/query-params.service.ts
>    public swapDefaultParams() {
а где это используется?

2021-04-20 14:22 UTC, siandreev commented on src/app/core/services/query-params/query-params.service.ts
> +    return token.length > 10 && token.slice(0, 2) === '0x';
в web3Public есть для этого метод

2021-04-20 14:57 UTC, axtezy commented on src/app/core/services/query-params/query-params.service.ts
>    public swapDefaultParams() {
При выборе токена, смене блокчейна. За счет этого url меняется.

2021-04-20 15:18 UTC, axtezy commented on src/app/core/services/query-params/query-params.service.ts
> +      chain: 'ethSymbol'
Заменил

2021-04-20 15:19 UTC, merged