Feature/airdrop retrodrop pages
Cryptorubic/rubic-app pull request #2557
Opened 2023-09-27 09:49 UTC by Doctor-Cyclone

2023-09-29 08:22 UTC, axtezy requested changes
Css когда переделываешь, сразу заменяй все padding/gap/border-radius на переменные

2023-09-29 08:22 UTC, axtezy commented on src/app/features/airdrop/components/points-container/points-container.component.ts
> +  public getButtonText(): Observable<string> {
Заменить на обычные поля, функция не нужна

2023-09-29 08:22 UTC, axtezy commented on src/app/features/airdrop/components/points-container/points-container.component.ts
> +    return this.points$.pipe(
Заменить на обычные поля, функция не нужна

2023-09-29 08:22 UTC, axtezy commented on src/app/features/airdrop/constants/airdrop-rounds.ts
> +    claimName: 'airdrop',
Здесь все airdrop, можно убрать

2023-09-29 08:22 UTC, axtezy commented on src/app/features/airdrop/services/airdrop-api.service.ts
> +@Injectable({ providedIn: 'root' })
На уровень Airdrop модуля перенести

2023-09-29 08:22 UTC, axtezy commented on src/app/features/retrodrop/components/retrodrop-page/retrodrop-page.component.scss
> +        gap: 5px;
tui-padding-xs

2023-09-29 08:22 UTC, axtezy commented on src/app/features/retrodrop/constants/retrodrop-rounds.ts
> +    claimName: 'retrodrop',
Все ретродропы, убрать

2023-09-29 08:22 UTC, axtezy commented on src/app/features/retrodrop/services/retrodrop-api.service.ts
> +@Injectable({ providedIn: 'root' })
На уровень ретродроп модуля

2023-09-29 08:22 UTC, axtezy commented on src/app/features/retrodrop/services/retrodrop.service.ts
> +@Injectable({
На уровень ретродроп модуля

2023-09-29 08:22 UTC, axtezy commented on src/app/features/retrodrop/services/retrodrop.service.ts
> +  private readonly _fetchError$ = new BehaviorSubject<boolean>(false);
Вычислить одинаковые с airdrop сервисом поля и методы и вынести в абстрактный класс

2023-09-29 08:22 UTC, axtezy commented on src/app/shared/components/claim-round-row/claim-round-row.component.scss
> +    padding: 5px;
Все padding, gap переделать на переменные tui

2023-09-29 08:22 UTC, axtezy commented on src/app/shared/components/claim-round-row/claim-round-row.component.ts
> +    claimData: ClaimTokensData;
В отдельный тип. В нескольких местах видел что фигурирует

2023-09-29 08:22 UTC, axtezy commented on src/app/shared/components/claim-round-row/claim-round-row.component.ts
> +    this.round = claimRound;
Вынести в функцию, в сеттере вызывать только ее

2023-09-29 08:22 UTC, axtezy commented on src/app/shared/services/token-distribution-services/claim-button-state.service.ts
> +@Injectable({
Сервис почти не взаимодействует со внешним миром, зачем его инжектить? Лучше просто utils класс сделать, не инжектить никуда, адрес прокидывать как параметр, все поля сделать статическими

2023-09-29 08:22 UTC, axtezy commented on src/app/shared/services/token-distribution-services/claim-web3.service.ts
> +    return !!isPaused;
Boolean(isPaused)

2023-09-29 08:22 UTC, axtezy commented on src/app/shared/services/token-distribution-services/claim.services.ts
> +  public readonly claimLoading$ = this._claimLoading$.asObservable();
Одинаковые стейт для retrodrop и airdrop получается. Вызываешь клейм на 1 странице, переходишь на другую, там тоже лоадинг будет, нужно переделать логику

2023-10-02 08:01 UTC, Doctor-Cyclone commented on src/app/features/airdrop/components/airdrop-page/airdrop-page.component.scss
> +  gap: 10px;
Done.

2023-10-02 08:01 UTC, Doctor-Cyclone commented on src/app/shared/services/token-distribution-services/claim.services.ts
> +  public readonly claimLoading$ = this._claimLoading$.asObservable();
Done.

2023-10-02 08:01 UTC, Doctor-Cyclone commented on src/app/shared/services/token-distribution-services/claim-web3.service.ts
> +    return !!isPaused;
Done.

2023-10-02 08:02 UTC, Doctor-Cyclone commented on src/app/shared/services/token-distribution-services/claim-button-state.service.ts
> +@Injectable({
Done.

2023-10-02 08:02 UTC, Doctor-Cyclone commented on src/app/shared/components/claim-round-row/claim-round-row.component.ts
> +    this.round = claimRound;
Done.

2023-10-02 08:02 UTC, Doctor-Cyclone commented on src/app/shared/components/claim-round-row/claim-round-row.component.ts
> +    claimData: ClaimTokensData;
Done.

2023-10-02 08:02 UTC, Doctor-Cyclone commented on src/app/shared/components/claim-round-row/claim-round-row.component.scss
> +    padding: 5px;
Done.

2023-10-02 08:02 UTC, Doctor-Cyclone commented on src/app/features/swaps/features/cross-chain/services/cross-chain-calculation-service/cross-chain-calculation.service.ts
> +    private readonly swapAndEarnStateService: AirdropService
Done.

2023-10-02 08:02 UTC, Doctor-Cyclone commented on src/app/features/retrodrop/services/retrodrop.service.ts
> +  private readonly _fetchError$ = new BehaviorSubject<boolean>(false);
Done.

2023-10-02 08:02 UTC, Doctor-Cyclone commented on src/app/features/retrodrop/services/retrodrop.service.ts
> +@Injectable({
Done.

2023-10-02 08:02 UTC, Doctor-Cyclone commented on src/app/features/retrodrop/services/retrodrop-api.service.ts
> +@Injectable({ providedIn: 'root' })
Done.

2023-10-02 08:02 UTC, Doctor-Cyclone commented on src/app/features/retrodrop/constants/retrodrop-rounds.ts
> +    claimName: 'retrodrop',
Done.

2023-10-02 08:02 UTC, Doctor-Cyclone commented on src/app/features/retrodrop/components/retrodrop-page/retrodrop-page.component.scss
>    gap: 15px;
Done.

2023-10-02 08:02 UTC, Doctor-Cyclone commented on src/app/features/retrodrop/components/retrodrop-page/retrodrop-page.component.scss
> +        gap: 5px;
Done.

2023-10-02 08:02 UTC, Doctor-Cyclone commented on src/app/features/airdrop/services/airdrop-api.service.ts
> +@Injectable({ providedIn: 'root' })
Done.

2023-10-02 08:02 UTC, Doctor-Cyclone commented on src/app/features/airdrop/constants/airdrop-rounds.ts
> +    claimName: 'airdrop',
Done.

2023-10-02 08:02 UTC, Doctor-Cyclone commented on src/app/features/airdrop/components/points-container/points-container.component.ts
> +    return this.points$.pipe(
Done.

2023-10-02 08:02 UTC, Doctor-Cyclone commented on src/app/features/airdrop/components/points-container/points-container.component.ts
> +  public getButtonText(): Observable<string> {
Done.

2023-10-02 08:03 UTC, Doctor-Cyclone commented on src/app/features/airdrop/components/points-container/points-container.component.scss
> +      gap: 10px;
Done.

2023-10-02 08:03 UTC, Doctor-Cyclone commented on src/app/features/airdrop/components/points-container/points-container.component.scss
> +    transition: all 0.1s ease-out;
Done.

2023-10-02 08:03 UTC, Doctor-Cyclone commented on src/app/features/airdrop/components/points-container/points-container.component.scss
> +      transition: all 0.1s ease-out;
Done.

2023-10-02 08:03 UTC, Doctor-Cyclone commented on src/app/features/airdrop/components/points-container/points-container.component.scss
> +      width: 15px;
Done.

2023-10-02 08:03 UTC, Doctor-Cyclone commented on src/app/features/airdrop/components/points-container/points-container.component.scss
> +      gap: 5px;
Done.

2023-10-02 08:03 UTC, Doctor-Cyclone commented on src/app/features/airdrop/components/points-container/points-container.component.scss
> +      width: 25px;
Done.

2023-10-02 08:03 UTC, Doctor-Cyclone commented on src/app/features/airdrop/components/points-container/points-container.component.scss
> +  gap: 20px;
Done.

2023-10-02 08:03 UTC, Doctor-Cyclone commented on src/app/features/airdrop/components/claim-container/claim-container.component.scss
>    gap: 15px;
Done.

2023-10-02 08:03 UTC, Doctor-Cyclone commented on src/app/features/airdrop/components/claim-container/claim-container.component.scss
> +        gap: 5px;
Done.

2023-10-02 08:03 UTC, Doctor-Cyclone commented on src/app/features/airdrop/components/airdrop-page/airdrop-page.component.scss
> +    padding-right: 12px;
Done.

2023-10-02 08:03 UTC, Doctor-Cyclone commented on src/app/features/airdrop/components/airdrop-page/airdrop-page.component.scss
> +  gap: 10px;
Done.

2023-10-02 08:34 UTC, axtezy requested changes

2023-10-02 08:34 UTC, axtezy commented on src/app/features/airdrop/components/points-container/points-container.component.ts
> +      if (points.requested_to_withdraw > 0 && !(points.confirmed >= 300)) {
Отрицание и сравнение  >= это 2 действия
Сравнение < это 1 действие

У юзеров пк конечно мощные, но лучше все таки делать эффективнее, особенно когда это ничего не стоит. Передалать здесь и сохранить в память

2023-10-02 08:34 UTC, axtezy commented on src/app/features/retrodrop/services/retrodrop-api.service.ts
> +      console.log('2 ', error);
Delete

2023-10-02 08:34 UTC, axtezy commented on src/app/features/retrodrop/services/retrodrop.service.ts
> +            this._fetchError$.next(true);
При отлове ошибки выставляешь в тру и сразу же в подписке выставляется фалс, не имеет смысла

2023-10-02 08:53 UTC, Doctor-Cyclone commented on src/app/features/airdrop/components/points-container/points-container.component.ts
> +      if (points.requested_to_withdraw > 0 && !(points.confirmed >= 300)) {
Done.

2023-10-02 08:53 UTC, Doctor-Cyclone commented on src/app/features/retrodrop/services/retrodrop-api.service.ts
> +      console.log('2 ', error);
Done.

2023-10-02 08:53 UTC, Doctor-Cyclone commented on src/app/features/retrodrop/services/retrodrop.service.ts
> +            this._fetchError$.next(true);
Done.

2023-10-02 08:56 UTC, axtezy approved these changes

2023-10-02 08:58 UTC, merged