RUBIC-424: Instant trades table
Cryptorubic/rubic-app pull request #266
Opened 2021-04-23 14:49 UTC by vlad3k

Добавил табличку. Работает пока что только GET

2021-04-27 08:24 UTC, axtezy commented on src/app/core/services/backend/instant-trades-api/instant-trades-api.service.ts
> +    return this.httpService.patch('instant_trades/', {}, hash);
Вынести все пути в отдельный файл с рутами

2021-04-27 14:41 UTC, ottebrut requested changes

2021-04-27 14:41 UTC, ottebrut commented on src/app/core/services/backend/instant-trades-api/types/trade-api.ts
> +  abi: object;
Нам точно не нужно принимать abi контракта. Надо обсудить с Даней

2021-04-27 14:41 UTC, ottebrut commented on src/app/features/swaps-page/instant-trades/components/instant-trades-table/instant-trades-table.component.ts
> +      this.instantTradesTableService.setQuoteTokenFilter(null);
Поменять base на from, quote - на to (описал проблему ниже)

2021-04-27 14:41 UTC, ottebrut commented on src/app/features/swaps-page/instant-trades/components/instant-trades-table/instant-trades-table.component.ts
> +  public refreshOrderBooks(): void {
refreshInstantTrades

2021-05-11 15:55 UTC, axtezy commented on src/app/core/services/backend/instant-trades-api/types/trade-api.ts
> +interface InstantTradesUser {
Уже есть подобынй интерфейс

2021-05-11 15:55 UTC, axtezy commented on src/app/features/swaps-page/instant-trades/components/instant-trades-table/instant-trades-table.component.ts
> +  public $hasData: Observable<boolean>;
readonly

2021-05-11 15:55 UTC, axtezy commented on src/app/features/swaps-page/models/trade-data.ts
> +export enum INTSTANT_TRADES_TRADE_STATUS {
Подобный интерфейс тоже где-то видел

2021-05-11 15:55 UTC, axtezy commented on src/app/shared/components/tokens-table/tokens-table.component.html
> +          {{ element.date.format('DD-MM-YYYY') }} <br />
Лучше в спаны обернуть

2021-05-11 15:55 UTC, axtezy commented on src/app/core/services/backend/instant-trades-api/instant-trades-api.service.ts
> +  public createTrade(tradeInfo: InstantTradesRequestApi): Observable<InstantTradesResponseApi> {
JSDoc добавить ко всем методам созданных сервисов

2021-05-12 09:57 UTC, siandreev requested changes

2021-05-12 09:57 UTC, siandreev commented on src/app/core/services/backend/instant-trades-api/instant-trades-api.service.ts
> +      })
```
map((swaps: InstantTradesResponseApi[]) => 
    swaps.map(swap => this.tradeApiToTradeData(swap)
)
```

либо можно
`map((swaps: InstantTradesResponseApi[]) => swaps.map(this.tradeApiToTradeData)`, но тогда не забыть объявить `tradeApiToTradeData` в "биндящем синтаксисе"

2021-05-12 09:57 UTC, siandreev commented on src/app/core/services/backend/instant-trades-api/types/trade-routes.ts
> +};
я бы внес это в сервис для наглядности

2021-05-12 09:57 UTC, siandreev commented on src/app/core/services/backend/instant-trades-api/instant-trades-api.service.ts
> +  public patchTrade(hash: string, status): Observable<InstantTradesResponseApi> {
тип `status`?

2021-05-12 09:57 UTC, siandreev commented on src/app/features/swaps-page/instant-trades/components/instant-trades-table/instant-trades-table.component.ts
> +    this.fetchSwaps();
в `ngOnInit`

2021-05-12 09:57 UTC, siandreev commented on src/app/features/swaps-page/instant-trades/components/instant-trades-table/instant-trades-table.component.ts
>  export class InstantTradesTableComponent {
забыл `implements AfterViewInit`

2021-05-12 09:59 UTC, siandreev commented
![image](https://user-images.githubusercontent.com/19926323/117956469-be201b80-b321-11eb-8643-bb00f4ec9063.png)

1.23e-16
13105.157368786181959316

суммы всех токенов обрезаем до 5 знака после запятой, либо до первых двух ненулевых знаков после запятой

2021-05-12 10:00 UTC, siandreev commented
По багам:
- Не работает сортировка
- Не работает мобильная версия

2021-05-12 10:01 UTC, siandreev commented
Еще не оч выглядит курсор pointer, лучше на дефолтный вернуть

2021-05-12 10:26 UTC, ottebrut commented
Сейчас в компоненте tokens-table используется тип OrderBooksTradeData - нужно заменить его на обобщенный тип

2021-05-20 20:41 UTC, siandreev requested changes

2021-05-20 20:41 UTC, siandreev commented on src/app/core/services/backend/instant-trades-api/instant-trades-api.service.ts
> +    this.web3PrivateService.onAddressChanges.subscribe(res => (this.walletAddress = res));
бесполезная строчка, как и поле `walletAddress`

2021-05-20 20:41 UTC, siandreev commented on src/app/features/swaps-page/instant-trades/components/instant-trades-form/services/instant-trades-form.service.ts
>    public onInstantTradesCreated: Subject<void> = new Subject();
мне кажется,  удачнее было бы хранить Subject с данными таблицы в `InstantTradesTableService` вызывая его метод на обновление когда прошел трейд, без синтетического события form-service, которое слушает table-component и вызывает того же table-service

2021-05-20 20:41 UTC, siandreev commented on src/app/features/swaps-page/instant-trades/components/instant-trades-form/services/instant-trades-form.service.ts
>    public onInstantTradesCreated: Subject<void> = new Subject();
Но не надо это сейчас исправлять, посмотрим после релиза

2021-05-20 20:41 UTC, siandreev commented on src/app/shared/components/tokens-table/tokens-table.component.ts
> +            'fromAmount' in a ? a.fromAmount.multipliedBy(a.token.from.price).toNumber() : 0,
Во-первых, не понял зачем тут in. Во-вторых, надо подстраховаться если price будет undefined (к сожалению, он автоматически не кастанется в 0). Кароче я бы сделал так:
`a. fromAmount  ? a.fromAmount.multipliedBy(a.token.from.price || 0).toNumber() : 0`

2021-05-21 09:28 UTC, siandreev commented
![image](https://user-images.githubusercontent.com/19926323/119115538-f1546000-ba2f-11eb-85bd-8ed59ebbebe8.png)
давай по умолчанию сортировка по дате, причем последние транзы сверху (сейчас вроде наоборот)

2021-05-21 09:34 UTC, siandreev commented
> ![image](https://user-images.githubusercontent.com/19926323/117956469-be201b80-b321-11eb-8643-bb00f4ec9063.png)
> 
> 1.23e-16
> 13105.157368786181959316
> 
> суммы всех токенов обрезаем до 5 знака после запятой, либо до первых двух ненулевых знаков после запятой

до 5 обрезается, но до двух не нулевых, если сумма меньше -- нет. Думаю, оставим это так, потому что даже в случае с битком это максимум 2.5 рубля

2021-05-21 16:32 UTC, merged