Upd wallets modal
Cryptorubic/rubic-app pull request #2801
Opened 2024-01-17 14:06 UTC by Doctor-Cyclone

2024-01-17 15:18 UTC, axtezy requested changes

2024-01-17 15:18 UTC, axtezy commented on src/app/core/services/store/models/store.ts
> +  RUBIC_AGREEMENT_WITH_RULES: boolean;
Добавь версию V1. Когда будет обновлять правила, поменяем на V2 чтобы сбросить у всех пользователей состояние

2024-01-17 15:18 UTC, axtezy commented on src/app/core/wallets-modal/components/wallets-modal/wallets-modal.component.scss
> +      padding-bottom: 32px;
Заменить на переменные tui
Пройтись заодно по всему файлу

2024-01-17 15:18 UTC, axtezy commented on src/app/core/wallets-modal/components/wallets-modal/wallets-modal.component.scss
> +    height: 50px;
Высоту 44 надо оставить у кнопки, соответственно размер иконки не должен ее превышать

2024-01-17 15:18 UTC, axtezy commented on src/app/core/wallets-modal/components/wallets-modal/wallets-modal.component.scss
> +    border-radius: 12px;
из переменной

2024-01-17 15:18 UTC, axtezy commented on src/app/core/wallets-modal/components/wallets-modal/wallets-modal.component.ts
> +  private readonly _enableWallets$ = new BehaviorSubject<boolean>(false);
Вместо Сабджекта использовать обсервабл на основе rulesCheckbox.valueChanges
в стор сохранять через tap

2024-01-18 10:51 UTC, Doctor-Cyclone commented on src/app/core/services/store/models/store.ts
> +  RUBIC_AGREEMENT_WITH_RULES: boolean;
Done.

2024-01-18 10:51 UTC, Doctor-Cyclone commented on src/app/core/wallets-modal/components/wallets-modal/wallets-modal.component.scss
> +      padding-bottom: 32px;
Done.

2024-01-18 10:51 UTC, Doctor-Cyclone commented on src/app/core/wallets-modal/components/wallets-modal/wallets-modal.component.scss
> +    height: 50px;
Done.

2024-01-18 10:51 UTC, Doctor-Cyclone commented on src/app/core/wallets-modal/components/wallets-modal/wallets-modal.component.scss
> +    border-radius: 12px;
Done.

2024-01-18 10:51 UTC, Doctor-Cyclone commented on src/app/core/wallets-modal/components/wallets-modal/wallets-modal.component.ts
> +  private readonly _enableWallets$ = new BehaviorSubject<boolean>(false);
Done.

2024-01-18 10:53 UTC, axtezy approved these changes

2024-01-18 13:56 UTC, merged