2236, Rootstock chain
Cryptorubic/rubic-app pull request #2886
Opened 2024-02-27 13:00 UTC by PseudoElement

2024-03-01 08:41 UTC, axtezy requested changes

2024-03-01 08:41 UTC, axtezy commented on src/app/core/header/components/header/components/user-profile/user-profile.component.html
> +              [class.rounded]="profile.needRoundBorder"
Класс по бем назвать

2024-03-01 08:41 UTC, axtezy commented on src/app/core/header/components/header/components/user-profile/user-profile.component.ts
> +  public hasSpaceIdAvatar$ = this.avatar$.pipe(
readonly

2024-03-01 08:41 UTC, axtezy commented on src/app/core/header/components/header/components/user-profile/user-profile.component.ts
> +    map(src => src.search(basePathBlockchainIcon) === -1)
includes вместо search

2024-03-01 08:41 UTC, axtezy commented on src/app/core/services/gas-service/gas.service.ts
> +  // @Cacheable({
Так нужен кастомный газ или нет? Если все ок то удалить

2024-03-01 08:46 UTC, PseudoElement commented on src/app/core/services/gas-service/gas.service.ts
> +  // @Cacheable({
Не нужен, забыл убрать

2024-03-27 10:37 UTC, axtezy requested changes

2024-03-27 10:37 UTC, axtezy commented on src/app/features/trade/components/preview-swap/preview-swap.component.ts
> +      state.label = this.isTradeWithPermit2Approve(tradeState) ? 'Permit and Swap' : state.label;
Отображаться не только у Idle должно, пересмотри логику

2024-03-27 10:37 UTC, axtezy commented on src/app/features/trade/components/transaction-state/transaction-state.component.ts
> +    if (value.needPermit2Approve) {
У тебя не тут пермит, и как шаг отдельный мы не обрабатываем

2024-03-27 10:37 UTC, axtezy commented on src/app/features/trade/services/on-chain/on-chain.service.ts
> +        await trade.approveOnPermit2(transactionOptions, true, amount);
Этого тут не должно быть

2024-03-27 10:37 UTC, axtezy commented on src/app/features/trade/services/preview-swap/models/swap-controller-service-types.ts
> +  DEFAULT: 'default',
Убрать

2024-03-27 10:37 UTC, axtezy commented on src/app/features/trade/services/preview-swap/preview-swap.service.ts
> +  public startPermit2Approve(): void {
Убрать весь этот функционал из аппа, это на уровне сдк исключительно должно быть

2024-03-27 10:45 UTC, axtezy requested changes

2024-03-27 10:45 UTC, axtezy commented on src/app/features/trade/services/on-chain/on-chain.service.ts
> +            timeout: 30_000,
Вернуть, тут не просто так 30 сек)

2024-04-01 12:24 UTC, axtezy requested changes

2024-04-01 12:24 UTC, axtezy commented on src/app/features/trade/components/preview-swap/preview-swap.component.ts
> +      state.label = this.isTradeWithPermit2Approve(tradeState) ? 'Permit and Swap' : state.label;
Если Permit происходит во время апрува, то тогда надо оставить label 'swap', измененный label будет только у апрува

2024-04-01 14:34 UTC, axtezy submitted a review, later dismissed

2024-04-01 14:45 UTC, axtezy approved these changes

2024-04-01 14:50 UTC, merged