Iframe warning fix
Cryptorubic/rubic-app pull request #294
Opened 2021-05-11 15:32 UTC by axtezy

2021-05-19 09:22 UTC, ottebrut requested changes

2021-05-19 09:22 UTC, ottebrut commented on src/app/features/swaps-page/instant-trades/components/instant-trades-form/instant-trades-form.component.ts
> +    this.$tokensSelectionDisabled = this.queryParamsService.$tokensSelectionDisabled;
Давай в ngOnInit

2021-05-19 09:22 UTC, ottebrut commented on src/app/shared/models/blockchain/BLOCKCHAINS.ts
> +export const BLOCKCHAINS = [
Этот файл я бы перенес в swaps-page - эта константа нигде больше использоваться не будет. Для бриджей используется другая модель.

2021-05-19 10:14 UTC, axtezy commented on src/app/features/swaps-page/instant-trades/components/instant-trades-form/instant-trades-form.component.ts
> +    this.$tokensSelectionDisabled = this.queryParamsService.$tokensSelectionDisabled;
Обычная инициализация поля класса идет, если никакой логики нет - используется конструктор, т.к. поле никак не зависит от этапа жизненного цикла компонента.

2021-05-21 12:42 UTC, siandreev requested changes

2021-05-21 12:42 UTC, siandreev commented on src/app/core/services/query-params/query-params.service.ts
> +            (acc: [string, string], curr: [string, string]) => {
`  acc: { [k in keyof Record<BLOCKCHAIN_NAME, string>]?: string[] }`

2021-05-21 12:42 UTC, siandreev commented on src/app/core/services/query-params/query-params.service.ts
> +            {} as any
с корректным типом не нужен as any

2021-05-21 12:42 UTC, siandreev commented on src/app/core/services/query-params/query-params.service.ts
> +                    rank: 3
давай в константу вынесем

2021-05-21 14:53 UTC, siandreev approved these changes

2021-05-21 14:57 UTC, merged