Rubic 440/get bnb
Cryptorubic/rubic-app pull request #303
Opened 2021-05-18 09:44 UTC by ottebrut

2021-05-19 08:23 UTC, axtezy commented on src/app/features/cross-chain-swaps-page/get-bnb-page/components/get-bnb-form/get-bnb-form.component.html
> +    <app-primary-button type="button" class="cross-chain-form__confirm-button" label="Get BNB">
Кнопка всегда раздизейблена?

2021-05-20 19:35 UTC, siandreev requested changes
Блин случайно на апрув нажал в прошлом ревью

2021-05-20 19:48 UTC, siandreev commented
по правкам и доделкам:
- надо добавить поле с fee (туда где у бриджей инфа о минимальной сумме перевода). Fee разное для эфира и токенов, думаю, получать ее следует прямо при инициализации сервиса (так будет минимальная задержка для пользователя. Пока лучше не париться с мультиколлом для двух токенов, главное к релизу успеть). Соответственно вызывать надо методы `depositFee` и `depositTokenFee`
- если выбран рубик надо добавить баннер о том, что благодаря выбору рубика комиссия уменьшена на X%, где X пока что берется из `content-loader.service`, причем баннер этот должен быть "позитивный". Если же выбран эфир, то баннер должен быть "негативным",  сообщать, что при выборе рубика можно будет уменьшить комиссию и иметь кнопку-ссылку "switch to RBC"

2021-05-20 19:57 UTC, siandreev commented
Кстати, эту иконку с тултипом впихнуть попытаться все-таки стоит. Очень неочевидно, что сумма BNB, которую ты получишь, может сильно отличаться от того что в форме
![image](https://user-images.githubusercontent.com/19926323/119041014-c7af2080-b9be-11eb-91c5-50ae6b548a20.png)

2021-05-20 20:16 UTC, siandreev commented
Нарисовал свое видение баннеров в 1007 и 1008

2021-05-24 16:23 UTC, siandreev approved these changes

2021-05-24 16:51 UTC, merged