Rubic 2463, add new selector
Cryptorubic/rubic-app pull request #3082
Opened 2024-05-20 09:39 UTC by IDIDOS

2024-05-20 09:49 UTC, axtezy requested changes

2024-05-20 09:49 UTC, axtezy commented on src/app/features/trade/components/assets-selector/services/blockchains-list-service/constants/blockchains-list.ts
> +    tag: BlockchainFilters.POPULAR
К 1 блокчейну может относиться несколько тегов (одновременно l2 и evm, так что нужно в существующий массив tags будет добавить

2024-05-21 09:45 UTC, axtezy requested changes

2024-05-21 09:45 UTC, axtezy commented on src/app/features/trade/components/assets-selector/components/blockchains-filter-list/models/BlockchainFilters.ts
> +  POPULAR = 'Popular',
Можно сделать тип BlockchainTags (и лучше его консантой, а не енумом)
А BlockchainFilters будет Omit<BlockchainTags, 'new'>

Тогда можно при проверке баджа будет использовать не строку

2024-05-21 09:45 UTC, axtezy commented on src/app/features/trade/components/assets-selector/components/search-bar/search-bar.component.ts
> +        : 'Search among 78 Chains'
Надо динамически число подтягивать, на основе количества блокчейнов

2024-05-21 09:45 UTC, axtezy commented on src/app/features/trade/components/assets-selector/services/blockchains-list-service/constants/blockchains-list.ts
> +  { name: BLOCKCHAIN_NAME.AVALANCHE, rank: 0.75, tags: ['AVAX', BlockchainFilters.POPULAR] },
Всем блокчейнам в этом спсике добавить тег 'EVM'

в notEvmChangeNowFormattedBlockchainsList в map в tags добавить всем блокчейнам 'NON_EVM'

2024-05-21 09:45 UTC, axtezy commented on src/app/features/trade/components/assets-selector/components/asset-types-aside/asset-types-aside.component.ts
> +    return blockchain.tags.reduce((accum, item) => {
some вместо reduce и возвращать boolean

2024-05-21 09:45 UTC, axtezy commented on src/app/features/trade/components/assets-selector/components/assets-selector-page/assets-selector-page.component.scss
> +    &__h-line {
развернуть имя селектора, а то совсем не понятно что такое h

2024-05-21 09:45 UTC, axtezy commented on src/app/features/trade/components/assets-selector/components/blockchains-filter-list/blockchains-filter-list.component.ts
> +    this.selectedFilterIndex = index;
Нужно не завязываться на индексах. Добавить
`public readonly currentFilter$ = this.filterQueryService.filterQuery$;`

Потом через асинк пайп в шаблоне сравнивать и выставлять параметры

2024-05-22 10:32 UTC, axtezy requested changes

2024-05-22 10:32 UTC, axtezy commented on src/app/features/trade/components/assets-selector/components/asset-types-aside/asset-types-aside.component.ts
> +      if (item === BlockchainTags.PROMO || item === BlockchainTags.NEW) {
Если одновременно PROMO и NEW будет, все сломается

2024-05-22 12:27 UTC, PseudoElement commented on src/app/features/trade/components/assets-selector/services/filter-query-service/filter-query.service.ts
> +  public set filterQuery(filter: BlockchainFilter) {
> Публичный сеттер и публичная функция-сеттер ровно одинаковый смысл семантический несут, если там всего 1 строчка кода `this._filterQuery$.next(filter);`, так что без разницы

Когда нажмешь на сеттер filterQuery внутри класса - ты не уувидишь места, где он используется за пределами класса и придется искать по поисковику все совпадения, а мало-ли таких filterQuery в других сервисах

2024-05-23 10:17 UTC, axtezy requested changes

2024-05-23 10:17 UTC, axtezy commented on src/app/features/trade/components/assets-selector/components/asset-types-aside/asset-types-aside.component.html
> +                <ng-container *ngIf="!isMobile && getBlockchainTag(blockchainItem) as tags">
2 тега у нас помещаются в UI? Если нет, надо приоритет отдать либо new либо promo и только 1 отображать

2024-06-21 10:33 UTC, axtezy approved these changes

2024-06-28 09:11 UTC, axtezy requested changes

2024-06-28 09:11 UTC, axtezy commented on src/app/features/trade/components/assets-selector/components/asset-types-aside/asset-types-aside.component.ts
> +    return tags.length > 1 ? this.blockchainTags.PROMO : tags[0];
Лучше отсортировать просто и взять tags[0], тк можем там потом уже появятся новые теги, которые нужно будет выводить

2024-06-28 09:11 UTC, axtezy commented on src/app/features/trade/components/assets-selector/components/blockchains-list/blockchains-list.component.ts
> +    return tags.length > 1 ? this.blockchainsTags.PROMO : tags[0];
Лучше отсортировать просто и взять tags[0], тк можем там потом уже появятся новые теги, которые нужно будет выводить

2024-06-28 13:06 UTC, axtezy requested changes

2024-06-28 13:06 UTC, axtezy commented on src/app/features/trade/components/assets-selector/components/search-bar/search-bar.component.ts
> +    this.searchQuery$ =
Лучше в конструкторе и как readonly пометить

2024-07-01 13:26 UTC, axtezy requested changes

2024-07-01 13:26 UTC, axtezy commented on src/app/core/services/tokens/tokens.service.ts
> +                    token.name.toLowerCase().includes('tether usd') &&
Просто tether

2024-07-01 14:09 UTC, axtezy approved these changes

2024-07-01 14:09 UTC, axtezy approved these changes

2024-07-01 14:10 UTC, merged