2615, TON
Cryptorubic/rubic-app pull request #3202
Opened 2024-07-05 15:28 UTC by PseudoElement

2024-07-10 10:04 UTC, axtezy commented on src/app/core/services/wallets/wallets-adapters/ton/utils/ton-utils.ts
> +export async function fetchFriendlyAddress(rawAddress: string): Promise<string> {
Занести в adapter, зачем тебе utils из одного метода на 3 строчки?

2024-07-10 10:09 UTC, axtezy commented on src/app/core/services/wallets/wallets-adapters/ton/ton-connect-adapter.ts
> +        }).call(this);
Зачем странная конструкция такая?
1) Можно было просто стрелочную функцию сделать
2) можно поток сделать из `this.tonConnect.onStatusChange` и через `switchMap` вызывать или `fetchFriendlyAddress(rawAddress)` или of(null) и в `subscribe` срузу вызывать `this.onAddressChanges$.next(address)`

2024-07-12 10:03 UTC, axtezy requested changes

2024-07-12 10:03 UTC, axtezy commented on src/app/core/services/wallets/wallets-adapters/ton/ton-connect-adapter.ts
> +        (async () => {
Вместо IIFE можем просто then юзать, с точки зрения логики будет то же самое

Вместо
```
(async () => {
          const rawAddress = walletAndwalletInfo.account.address;
          const friendlyAddress = await this.fetchFriendlyAddress(rawAddress);
          this.onAddressChanges$.next(friendlyAddress);
})();
```
Сделать
```
const rawAddress = walletAndwalletInfo.account.address;
this.fetchFriendlyAddress(rawAddress).then(
    friendlyAddress => this.onAddressChanges$.next(friendlyAddress)
);
```

2024-07-12 10:03 UTC, axtezy commented on src/app/core/services/wallets/wallets-adapters/ton/ton-connect-adapter.ts
> +    const res = (await (
Убрать await в скобках, разбить на переменные

2024-07-12 10:04 UTC, axtezy commented on src/app/core/services/wallets/wallets-adapters/ton/ton-connect-adapter.ts
> +      manifestUrl: `http://bubamainer.fvds.ru/api/v1/tonconnect/manifest/${ENVIRONMENT.environmentName}`
Может вообще удобнее через connector подключать будет? Чтобы не делать на каждый dev манифест и environmentName

2024-07-18 10:37 UTC, PseudoElement commented on src/app/core/services/wallets/wallets-adapters/ton/ton-connect-adapter.ts
> +        (async () => {
async await последовательнее смотрится, предлагаю отвечать стандартам ES5 в приложении и уходить от цепных промисов по возможности.

2024-07-18 12:20 UTC, axtezy requested changes

2024-07-18 12:20 UTC, axtezy commented on src/app/core/services/wallets/wallets-adapters/ton/ton-connect-adapter.ts
> +        (async () => {
IIFE это просто жесткий анархизм. Их использовали раньше для разделения областей видимости. Сейчас это в 99% не актуальная вещь, если не нравится .then надо другой способ поискать

2024-07-18 12:20 UTC, axtezy commented on src/app/core/services/tokens/tokens-store.service.ts
> +   *              and tokens from backend have high priority
Что то с форматированием

2024-07-18 13:03 UTC, axtezy requested changes

2024-07-18 13:03 UTC, axtezy commented on src/app/core/services/wallets/wallets-adapters/ton/ton-connect-adapter.ts
> +    console.log('FETCH_FRRRRRRRRR', { res, friendly });
del

2024-10-03 14:17 UTC, axtezy approved these changes

2024-10-15 13:09 UTC, axtezy submitted a review, later dismissed

2024-10-15 13:09 UTC, AleksandrArtyushenko submitted a review, later dismissed

2024-10-15 13:22 UTC, AleksandrArtyushenko approved these changes

2024-10-15 13:22 UTC, merged