Bug-fixes, fix bugs 2677, 2675, 2674, 2673
Cryptorubic/rubic-app pull request #3234
Opened 2024-07-19 14:41 UTC by PseudoElement

2024-07-24 15:01 UTC, axtezy commented on src/app/features/trade/components/route-element/route-element.component.ts
> +const BRIDGE_TO_ONCHAIN_KEY: Partial<Record<BridgeType, OnChainTradeType>> = {
Это не на уровне аппа, а на уровне сдк должно регулироваться

2024-07-24 15:02 UTC, axtezy commented on src/app/features/trade/components/route-element/route-element.component.ts
> +      image: 'assets/images/icons/coins/default-token-ico.svg'
assets/images/icons/unknown.svg

2024-07-24 15:02 UTC, axtezy commented on src/app/features/trade/components/route-element/route-element.component.ts
> +      name: 'unknown dex',
Unknown Dex

2024-07-24 15:49 UTC, axtezy requested changes
Нотификация еще для кода 1146 нужна

2024-07-25 08:17 UTC, axtezy requested changes

2024-07-25 08:26 UTC, AleksandrArtyushenko approved these changes

2024-07-25 08:45 UTC, axtezy approved these changes

2024-07-25 08:50 UTC, merged