fix hint delay for scroll event
Cryptorubic/rubic-app pull request #3240
Opened 2024-07-23 07:58 UTC by IDIDOS

2024-07-23 08:29 UTC, axtezy requested changes

2024-07-23 08:29 UTC, axtezy commented on src/app/features/trade/components/providers-list-general/providers-list-general.component.ts
> +  @ViewChild('tuiScrollBar') scrollBarElement: TuiScrollbarComponent;
Лучше scrollService заюзать
https://taiga-ui.dev/services/scroll-service#interactive

2024-07-23 08:29 UTC, axtezy commented on src/app/features/trade/services/provider-hint/provider-hint.service.ts
> +  private readonly _hideProviderHintOnScroll$ = new BehaviorSubject<boolean>(false);
Не обязательно к скроллу привязываться, в теории и для других случаев может понадобиться скрывать хинт
Так что такой нейминг лучше сделать
```
private readonly _hideProviderHint$ = new BehaviorSubject<boolean>(false);
public readonly hideProviderHint$ = this._hideProviderHint$.asObservable();

public hideHint(): void {
  this._hideProviderHint$.next(true);
  this._hideProviderHint$.next(false);
}
```

2024-07-23 08:29 UTC, axtezy commented on src/app/features/trade/trade.module.ts
> +    ProviderHintService
Лучше на уровень компонента добавить, чтобы сервис был уникален для каждого набора хинтов

2024-07-23 08:29 UTC, axtezy commented on src/app/features/trade/components/swap-data-element/swap-data-element.component.html
> +    [tuiHintHideDelay]="(hideHintOnScroll$ | async) === false ? 200 : 0"
Лучше где то ранее в шаблоне через `*ngLet="hideHint$ | async as hideHint"` объявить и дальше уже `hideHint ? 0 : 200` юзать

2024-07-23 11:28 UTC, axtezy requested changes

2024-07-23 11:28 UTC, axtezy commented on src/app/features/trade/components/swap-data-element/swap-data-element.component.html
> +    [tuiHintHideDelay]="!hideHint ? 200 : 0"
Лучше `hideHint ? 0 : 200`, тк отрицание - дополнительное действие

2024-07-23 11:28 UTC, axtezy commented on src/app/features/trade/services/provider-hint/provider-hint.service.ts
> +    return this._hideProviderHint$.pipe(distinctUntilChanged());
Просто полем, не get
```
public readonly hideProviderHint$ =  this._hideProviderHint$.pipe(distinctUntilChanged());
```

2024-07-23 11:28 UTC, axtezy commented on src/app/features/trade/components/provider-element/provider-element.component.ts
> +  public readonly hideHint$ = this.providerHintService.hideProviderHint$;
Порождаем много observables, лучш через input

2024-07-23 11:28 UTC, axtezy commented on src/app/features/trade/components/providers-list-general/providers-list-general.component.ts
> +        tap(() => this.hideProviderHintOnScroll(true)),
Не хочется просто так гонять переменные, нужно отптимизировать, чтобы observable отрабатывал только когда курсор на элементе с хинтом

2024-07-23 11:28 UTC, axtezy commented on src/app/features/trade/services/provider-hint/provider-hint.service.ts
> +  public hideHint(isScrollStart: boolean): void {
Логическая несостыкова получается, мы через hideHint можем назначить hideProviderHint - false
Нужно переименовать в setHintVisibility тогда

2024-07-23 11:28 UTC, axtezy commented on src/app/features/trade/components/provider-element/provider-element.component.html
> +      [hideHint$]="hideHint$"
Сразу hideHint можно передавать

2024-07-29 07:16 UTC, axtezy approved these changes

2024-07-29 07:18 UTC, AleksandrArtyushenko approved these changes

2024-07-29 07:19 UTC, merged