сypress at selectors
Cryptorubic/rubic-app pull request #3297
Opened 2024-09-06 15:30 UTC by IldarGabi

2024-09-09 10:23 UTC, axtezy requested changes

2024-09-09 10:23 UTC, axtezy commented on cypress/e2e/spec.cy.ts
> +    cy.get('[alt="Rubic logotype"]').should('exist'); // лого
На alt нельзя завязываться

2024-09-09 10:23 UTC, axtezy commented on cypress/e2e/spec.cy.ts
> +      .should('have.text', ' Подключить кошелек\n'); // кнопка подключения кошелька
Нельзя ориентироваться на русский текст

2024-09-09 10:23 UTC, axtezy commented on cypress/e2e/spec.cy.ts
> +    const swapCalc = cy.get('[class*=window]');
swapForm

2024-09-09 10:23 UTC, axtezy commented on cypress/e2e/spec.cy.ts
> +    swapCalc.get('[alt="Select token"]').eq(0).click();
На альтернетивный текст не завязываемся

2024-09-09 10:23 UTC, axtezy commented on cypress/e2e/spec.cy.ts
> +    swapCalc.get('[alt="Select token"]').eq(0).click();
Нужен более комплексный селектор, на индекс не завязываться

2024-09-09 10:23 UTC, axtezy commented on cypress/e2e/spec.cy.ts
> +    cy.get('[class*=asset-types] button').eq(0).should('have.text', 'EthereumPROMO');
Без привязки к индексу, если поменяется очередность - все поедет

2024-09-09 10:23 UTC, axtezy commented on cypress/e2e/spec.cy.ts
> +    swapCalc.get('[placeholder="Enter an Amount"]').click().type('1');
К плейсхолдеру и тексту внутри не привязываться

2024-09-09 10:23 UTC, axtezy commented on cypress/e2e/spec.cy.ts
> +    cy.get('[data-appearance="primary"] > [class="t-wrapper"]')
Это тоже общие классы, не уникальные. Нужно через более уникального родителя искать

2024-09-09 20:55 UTC, IldarGabi commented on cypress/e2e/spec.cy.ts
> +    cy.visit('https://app.rubic.exchange/');
Ок, исправлю)

2024-09-09 20:56 UTC, IldarGabi commented on cypress/e2e/spec.cy.ts
> +    cy.get('[alt="Rubic logotype"]').should('exist'); // лого
ок.
А почему?)

2024-09-09 20:58 UTC, IldarGabi commented on cypress/e2e/spec.cy.ts
> +    const swapCalc = cy.get('[class*=window]');
Соглашусь

2024-09-09 20:58 UTC, IldarGabi commented on cypress/e2e/spec.cy.ts
> +    swapCalc.get('[alt="Select token"]').eq(0).click();
Ок) Исправлю

2024-09-09 21:04 UTC, IldarGabi commented on cypress/e2e/spec.cy.ts
> +    swapCalc.get('[placeholder="Enter an Amount"]').click().type('1');
Здесь спорно. 
Так как этот текст "Enter an Amount" одинаков для любого языка.
Проверяем и инпут ввода суммы и текстовку, разве не валидный кейс?

2024-09-09 21:05 UTC, IldarGabi commented on cypress/e2e/spec.cy.ts
> +    cy.get('[data-appearance="primary"] > [class="t-wrapper"]')
Так мы же тут и проверяем только наличие самого блока калькуляции. Без списка провайдеров.

2024-09-09 21:26 UTC, IldarGabi commented on cypress/e2e/spec.cy.ts
> +    swapCalc.get('[alt="Select token"]').eq(0).click();
Тут без индекса вряд ли получится. Так как два идентичных элемента на странице (селектор для сор и целевого сетей/токенов)
data-id можем прикрутить))

2024-09-09 21:29 UTC, IldarGabi commented on cypress/e2e/spec.cy.ts
> +    cy.get('[class*=asset-types] button').eq(0).should('have.text', 'EthereumPROMO');
Ок. Получается, что просто проверим наличие инфы PROMO (строка выше)
Текущую дропну

2024-09-10 08:47 UTC, axtezy commented on cypress/e2e/spec.cy.ts
> +    cy.get('[alt="Rubic logotype"]').should('exist'); // лого
Он может быть с переводом

2024-09-10 08:52 UTC, axtezy commented on cypress/e2e/spec.cy.ts
> +    swapCalc.get('[placeholder="Enter an Amount"]').click().type('1');
Placeholder может меняться, раньше у нас просто было '0'
У этого инпута есть ID,  к нему и надо привязаться `token-amount-input-element`

2024-09-10 13:59 UTC, IldarGabi commented on cypress/e2e/spec.cy.ts
> +    cy.get('[alt="Rubic logotype"]').should('exist'); // лого
ок, я селектор заменил в коммите последнем)

2024-09-10 13:59 UTC, IldarGabi commented on cypress/e2e/spec.cy.ts
> +    swapCalc.get('[placeholder="Enter an Amount"]').click().type('1');
Хорошо. Поправил) Спасибо

2024-10-03 14:25 UTC, axtezy approved these changes

2024-10-03 14:25 UTC, merged