8305, feat alternative routes
Cryptorubic/rubic-app pull request #3305
Opened 2024-09-16 09:25 UTC by IDIDOS

2024-09-16 10:39 UTC, axtezy requested changes

2024-09-16 10:39 UTC, axtezy commented on src/app/features/trade/components/providers-list/providers-list.component.html
> -<ng-template #emptyContent>
Если нет токенов и маршрутов, этот текст должен отображаться

2024-09-16 10:39 UTC, axtezy commented on src/app/features/trade/components/alternative-routes-list/alternative-routes-list.component.html
> +    Most likely there will be no routes available. You can use networks below for intermediate swap.
Это тексты уже согласованные с маркетингом из таски или то что в дизайне было?

2024-09-24 08:52 UTC, axtezy requested changes

2024-09-24 08:52 UTC, axtezy commented on src/app/features/trade/services/alternative-route-api-service/alternative-routes.service.ts
> +      const usdPrice = this.swapFormService.inputValue.fromToken.price;
Может быть ситуация, когда у токена нет цены, тогда давай какое-то дефолтное значение подставлять (1000, например)

2024-10-03 14:22 UTC, axtezy requested changes

2024-10-03 14:22 UTC, axtezy commented on src/app/features/trade/services/alternative-route-api-service/alternative-routes.service.ts
> +      .get<AlternativeRouteDTO>('https://dev-tokens.rubic.exchange/api/v1/token_pairs', {
из env надо брать апи

2024-10-03 14:22 UTC, axtezy commented on src/app/features/trade/services/alternative-route-api-service/alternative-routes.service.ts
> +    return combineLatest([this.swapFormService.fromToken$, this.swapFormService.toToken$]).pipe(
forkJoin

2024-10-30 13:15 UTC, axtezy approved these changes

2024-10-30 13:18 UTC, AleksandrArtyushenko approved these changes

2024-10-30 13:18 UTC, merged