add SimpleSwap provider
Cryptorubic/rubic-app pull request #3371
Opened 2024-10-22 06:33 UTC by IDIDOS

2024-10-22 07:32 UTC, axtezy requested changes

2024-10-22 07:32 UTC, axtezy commented on src/app/features/trade/services/deposit/deposit.service.ts
> +  private readonly maxLatestTrades = 8;
Раз у нас теперь в 2 раза больше провайдеров, хорошо бы пагинацию сделать, прикинь сколько ее делать под эту таблицу, если не долго, давай сделаем. Если долго - увеличь просто до 10 и оставь todo pagination

2024-11-26 12:38 UTC, axtezy approved these changes

2024-11-26 12:38 UTC, usrbad approved these changes

2024-11-26 12:39 UTC, merged