xDai bridge
Cryptorubic/rubic-app pull request #344
Opened 2021-05-31 10:26 UTC by vlad3k

Add xDai bridge from ETH to xDai

2021-05-31 11:24 UTC, siandreev requested changes

2021-05-31 11:24 UTC, siandreev commented on src/app/features/cross-chain-swaps-page/bridge-page/components/brifge-form/bridge-form.component.html
> +            : 'https://www.xdaichain.com/'
сделать в ts компоненте объект по типу 
```
BLOCKCHAIN_DATA = {
    [BLOCKCHAIN_NAME.BSC]: {
        link: 'https://link',
        caption: 'Binance Smart Chain'
    },
    ...
}
```
соответственно тут и на 196-201 строчках брать из этого объекта  `BLOCKCHAIN_DATA[fromBlockchain]?.link || BLOCKCHAIN_DATA[toBlockchain]?.link `

2021-05-31 11:24 UTC, siandreev commented on src/app/features/cross-chain-swaps-page/bridge-page/services/blockchains-bridge-provider/ethereum-xdai-bridge-provider/ethereum-xdai-bridge-provider.service.ts
> +  }
Panama тут не при чем, из нее токены не будут браться даже в будущем, если мост зайдет. Пока просто вручную создаем список из одного токена

2021-05-31 11:24 UTC, siandreev commented on src/app/features/cross-chain-swaps-page/bridge-page/services/blockchains-bridge-provider/ethereum-xdai-bridge-provider/ethereum-xdai-bridge-provider.service.ts
> +    const depositAddress = '0x4aa42145Aa6Ebf72e164C9bBC74fbD3788045016';
в константу (писал выше)

2021-05-31 11:24 UTC, siandreev commented on src/app/features/cross-chain-swaps-page/bridge-page/services/blockchains-bridge-provider/ethereum-xdai-bridge-provider/ethereum-xdai-bridge-provider.service.ts
> +export class EthereumXdaiBridgeProviderService extends BlockchainsBridgeProvider {
Надо добавить в `BlockchainsBridgeProvider` JSDoc, а также заменить возвращаемый тип данный у метода `createTrade` на `TransactionReceipt`

2021-06-01 10:11 UTC, vlad3k commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +      walletDepositAddress: '0x4aa42145Aa6Ebf72e164C9bBC74fbD3788045016'
Поправил

2021-06-01 10:11 UTC, vlad3k commented on src/app/features/cross-chain-swaps-page/bridge-page/components/brifge-form/bridge-form.component.html
> +            : 'https://www.xdaichain.com/'
Поправил

2021-06-01 10:12 UTC, vlad3k commented on src/app/features/cross-chain-swaps-page/bridge-page/services/blockchains-bridge-provider/ethereum-xdai-bridge-provider/ethereum-xdai-bridge-provider.service.ts
> +  }
Поправил

2021-06-01 10:12 UTC, vlad3k commented on src/app/features/cross-chain-swaps-page/bridge-page/services/blockchains-bridge-provider/ethereum-xdai-bridge-provider/ethereum-xdai-bridge-provider.service.ts
> +    const depositAddress = '0x4aa42145Aa6Ebf72e164C9bBC74fbD3788045016';
Поправил

2021-06-01 10:12 UTC, vlad3k commented on src/app/features/cross-chain-swaps-page/bridge-page/services/blockchains-bridge-provider/ethereum-xdai-bridge-provider/ethereum-xdai-bridge-provider.service.ts
> +export class EthereumXdaiBridgeProviderService extends BlockchainsBridgeProvider {
Поправил

2021-06-02 10:27 UTC, vlad3k commented on src/app/features/cross-chain-swaps-page/bridge-page/services/blockchains-bridge-provider/ethereum-xdai-bridge-provider/ethereum-xdai-bridge-provider.service.ts
> +          symbol: 'DAI',
Поправил

2021-06-02 10:27 UTC, vlad3k commented on src/app/features/cross-chain-swaps-page/bridge-page/services/blockchains-bridge-provider/ethereum-xdai-bridge-provider/ethereum-xdai-bridge-provider.service.ts
> +          address: '0x44fA8E6f47987339850636F88629646662444217',
Поправил

2021-06-02 10:27 UTC, vlad3k commented on src/app/features/cross-chain-swaps-page/bridge-page/services/blockchains-bridge-provider/ethereum-xdai-bridge-provider/ethereum-xdai-bridge-provider.service.ts
> +          name: 'Dai',
Поправил

2021-06-02 10:27 UTC, vlad3k commented on src/app/shared/pipes/scanner-link.pipe.ts
>    }
Добавил поле nativeCoinUrl для всех чейнов

2021-06-03 14:38 UTC, siandreev approved these changes

2021-06-03 16:26 UTC, siandreev commented
@vlad3k пр-ы фич-веток создаем в develop, а не master

2021-06-03 16:26 UTC, closed without merging