730,  Spindl Ads
Cryptorubic/rubic-app pull request #3441
Opened 2024-12-02 13:12 UTC by PseudoElement

2024-12-11 12:59 UTC, axtezy requested changes

2024-12-11 12:59 UTC, axtezy commented on src/app/app.component.ts
> +      host: new URL(window.location.href).host
Через токен (this.window)

2024-12-11 12:59 UTC, axtezy commented on src/app/shared/components/spindle-banner/spindle-banner.component.ts
> +    else if (isMobile) return 'under_swap_mobile';
С else эта конструкция еще страннее выглядит)

Давай хотя бы
```
if (step === 'success') return 'post_swap';
if (isMobile) return 'under_swap_mobile';
return 'under_swap_desktop';
```

2024-12-13 14:34 UTC, axtezy submitted a review, later dismissed

2024-12-13 14:34 UTC, axtezy commented on src/app/app.component.ts
> +    this.spindlService.initSpindlAds().then();
пустой then

2024-12-16 11:44 UTC, AleksandrArtyushenko approved these changes

2024-12-16 12:02 UTC, merged