implement sendPreTradeInfo methods
Cryptorubic/rubic-app pull request #3445
Opened 2024-12-05 13:50 UTC by IDIDOS

2024-12-05 14:02 UTC, axtezy requested changes

2024-12-05 14:02 UTC, axtezy commented on src/app/features/trade/services/cross-chain/cross-chain.service.ts
> +    const preTradeId = await this.crossChainApiService.sendPreTradeInfo(trade);
в tryCatch обернуть и по дефолту выставть null значение, для ончейна тоже

2024-12-05 14:28 UTC, axtezy submitted a review, later dismissed

2024-12-10 07:26 UTC, usrbad approved these changes

2024-12-10 07:29 UTC, axtezy approved these changes

2024-12-10 07:31 UTC, merged