Order book refactoring
Cryptorubic/rubic-app pull request #42
Opened 2021-02-26 10:56 UTC by ottebrut

2021-03-01 11:17 UTC, siandreev requested changes

2021-03-01 11:17 UTC, siandreev commented on src/app/services/web3Api/web3-api.service.spec.ts
> +    expect(tokenBody.name === weenusBody.token_title);
.toBeTruthy();

2021-03-01 11:17 UTC, siandreev commented on src/app/services/web3Api/web3-api.service.spec.ts
> +    const weenusBody = coingeckoTestTokens.find(t => t.address === WEENUS.address);
Предлагаю добавить name в сам WEENUS

2021-03-01 12:04 UTC, siandreev requested changes

2021-03-01 12:04 UTC, siandreev commented on src/app/services/web3Api/web3-api.service.ts
> +   */
я бы использовал кэширующий декоратор, чтобы не хранить эти данные в самом сервисе (т.к. они нужны именно этой функции)
https://learn.javascript.ru/call-apply-decorators

2021-03-01 12:08 UTC, siandreev requested changes

2021-03-01 12:08 UTC, siandreev commented on src/app/services/provider/provider.service.ts
> +    [BLOCKCHAIN_NAMES.ETHEREUM]: 'https://mainnet.infura.io/v3/2e15c999e7854a6d9d95d7eb68b11ad6',
надо обновить ключ, создать чето типа .env.json (сразу в .gitignore) и туда занести ключ

2021-03-03 09:43 UTC, ottebrut commented on src/app/services/web3Api/web3-api.service.spec.ts
> +    expect(tokenBody.name === weenusBody.token_title);
поправил

2021-03-03 09:44 UTC, ottebrut commented on src/app/services/web3Api/web3-api.service.spec.ts
> +    const weenusBody = coingeckoTestTokens.find(t => t.address === WEENUS.address);
решили оставить в coingecko

2021-03-03 09:44 UTC, ottebrut commented on src/app/services/web3Api/web3-api.service.ts
> +    }
вынес

2021-03-03 09:44 UTC, ottebrut commented on src/app/services/web3Api/web3-api.service.ts
> +    });
поправил

2021-03-03 09:44 UTC, ottebrut commented on src/app/services/web3Api/web3-api.service.ts
> +    return new Promise((resolve, reject) => {
поправил

2021-03-03 09:44 UTC, ottebrut commented on src/app/services/web3Api/web3-api.service.ts
> +   */
поправил

2021-03-03 10:08 UTC, merged