UI-v3.1
Cryptorubic/rubic-app pull request #716
Opened 2021-08-31 12:49 UTC by vlad3k

Max button and error text instead switch network button

2021-09-01 10:06 UTC, siandreev requested changes
Пока не успел подробно посмотреть, досмотрю потом

2021-09-01 10:06 UTC, siandreev commented on src/app/shared/components/buttons/approve-button/swap-button.component.html
> +          (!errorType[ERROR_TYPE.WRONG_BLOCKCHAIN] || (isMobile$ | async)) &&
убираем повторные использования `!(isMobile$ | async)`. Лучше использовать на общем теге родителе `*ngLet="(isMobile$ | async) === false as isDesctop"`
Дальше в ифах можно использовать переменную `isDesctop`

2021-09-01 10:06 UTC, siandreev commented on src/app/shared/components/provider-panel/panel-content/panel-content.component.ts
> +  public isGasFeeShow: boolean = false;
указывать тип не надо при инициализации

2021-09-08 12:51 UTC, vlad3k commented on src/app/shared/components/buttons/approve-button/swap-button.component.html
> +          (!errorType[ERROR_TYPE.WRONG_BLOCKCHAIN] || (isMobile$ | async)) &&
Поправил

2021-09-08 12:52 UTC, vlad3k commented on src/app/shared/components/provider-panel/panel-content/panel-content.component.ts
> +  public isGasFeeShow: boolean = false;
Поправил

2021-09-08 13:02 UTC, axtezy requested changes

2021-09-08 13:02 UTC, axtezy commented on src/app/shared/components/buttons/approve-button/swap-button.component.ts
> +  public isMobile$: Observable<boolean>;
readonly

2021-09-08 13:02 UTC, axtezy commented on src/app/shared/components/provider-panel/panel-content/panel-content.component.ts
> +type InstantTradeBlockchain = Exclude<
Вынести тип в Shared

2021-09-08 14:00 UTC, vlad3k commented on src/app/features/bridge/services/bridge-service/blockchains-bridge-provider/blockchains-bridge-provider.ts
> +  public abstract getEstimatedGas(bridgeTrade?: BridgeTrade): Observable<BigNumber>;
Добавил

2021-09-08 14:00 UTC, vlad3k commented on src/app/features/bridge/services/bridge-service/blockchains-bridge-provider/binance-polygon-bridge-provider/binance-polygon-bridge-provider.service.ts
> +  public getEstimatedGas(): Observable<BigNumber> {
Добавил

2021-09-08 14:00 UTC, vlad3k commented on src/app/features/instant-trade/components/instant-trade-bottom-form/instant-trade-bottom-form.component.ts
> +    this.displayMaxButton.emit(!!this.toToken);
Поправил

2021-09-08 14:00 UTC, vlad3k commented on src/app/shared/components/buttons/approve-button/swap-button.component.ts
> +  public isMobile$: Observable<boolean>;
Поправил

2021-09-08 14:00 UTC, vlad3k commented on src/app/shared/components/provider-panel/panel-content/panel-content.component.ts
> +type InstantTradeBlockchain = Exclude<
Перенес

2021-09-13 13:29 UTC, siandreev requested changes

2021-09-13 13:29 UTC, siandreev commented on src/app/features/bridge/services/bridge-service/blockchains-bridge-provider/blockchains-bridge-provider.ts
> +  public abstract getEstimatedGas(bridgeTrade?: BridgeTrade): Observable<BigNumber>;
почему абстрактный?
зачем во всех сервисах делать 
```
public getEstimatedGas(): Observable<BigNumber> {
    return of(new BigNumber(0));
  }
```
лучше добавить в абстрактный класс реализацию по умолчанию, а из потомков убрать это

2021-09-13 13:29 UTC, siandreev commented on src/app/features/bridge/services/bridge-service/blockchains-bridge-provider/ethereum-polygon-bridge-provider/ethereum-polygon-bridge-provider.service.ts
> +import networks from '../../../../../../shared/constants/blockchain/networks';
какая грязь

2021-09-13 13:29 UTC, siandreev commented on src/app/features/bridge/services/bridge-service/blockchains-bridge-provider/ethereum-polygon-bridge-provider/ethereum-polygon-bridge-provider.service.ts
> +      return fromPromise(
`from`

2021-09-13 13:29 UTC, siandreev commented on src/app/features/bridge/services/bridge-service/blockchains-bridge-provider/ethereum-polygon-bridge-provider/ethereum-polygon-bridge-provider.service.ts
> +      ).pipe(catchError(() => of(this.defaultTransactionGas)));
название поля не соответствует реальности

2021-09-13 13:29 UTC, siandreev commented on src/app/features/bridge/services/bridge-service/bridge.service.ts
> +      })
лучше не `() => {return value}`, а `() => value`

2021-09-22 09:18 UTC, closed without merging