Hotfix styles widget
Cryptorubic/rubic-app pull request #745
Opened 2021-09-02 16:53 UTC by vlad3k

2021-09-03 10:07 UTC, siandreev requested changes

2021-09-03 10:07 UTC, siandreev commented on src/app/shared/components/token-amount-estimated/token-amount-estimated.component.scss
>  @import 'src/scss/vars';
в вертикальном проблема осталась
![image](https://user-images.githubusercontent.com/19926323/131988000-7807370b-ffb3-4973-bf79-314e2a3a6456.png)

2021-09-03 13:23 UTC, vlad3k commented on src/app/shared/components/rubic-tokens/rubic-tokens.component.scss
> +  @include iframe-horizontal {
Поправил

2021-09-03 13:24 UTC, vlad3k commented on src/app/shared/components/token-amount-estimated/token-amount-estimated.component.scss
>  @import 'src/scss/vars';
Поправил

2021-09-03 14:12 UTC, siandreev approved these changes

2021-09-06 11:31 UTC, axtezy approved these changes

2021-09-06 13:17 UTC, merged