Zrx and uniswap3 new
Cryptorubic/rubic-app pull request #755
Opened 2021-09-06 08:22 UTC by vlad3k

Перенес uniswap v3 и zrx провайдеры из старой ветки

2021-09-07 14:46 UTC, axtezy requested changes

2021-09-07 14:46 UTC, axtezy commented on src/app/core/interceptors/http-interceptor.ts
> +      let newRequest = req.clone({
Нужно разнести по нескольким интерцепторам функционал

2021-09-07 14:46 UTC, axtezy commented on src/app/core/services/blockchain/web3-public-service/Web3Public.ts
> +  public encodeFunctionCall(
JSDock в сервисах

2021-09-07 14:46 UTC, axtezy commented on src/app/core/services/blockchain/web3-public-service/Web3Public.ts
> +  public getContract(address: string, abi: AbiItem[]) {
JSDock в сервисах

2021-09-07 14:46 UTC, axtezy commented on src/app/features/instant-trade/services/instant-trade-service/providers/common/zrx/zrx.service.ts
> +import { Injectable } from '@angular/core';
Переписать с использованием абстрактного Uniswap сервиса

2021-09-07 14:46 UTC, axtezy commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/controllers/LiquidityPoolsController.ts
> +  public static isPoolWithTokens(pool: LiquidityPool, tokenA: string, tokenB: string): boolean {
Методы после конструктора

2021-09-07 14:46 UTC, axtezy commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/controllers/LiquidityPoolsController.ts
> +  public static getContractPoolsPath(pools: LiquidityPool[], initialTokenAddress: string): string {
Методы после конструктора

2021-09-07 14:46 UTC, axtezy commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/controllers/LiquidityPoolsController.ts
> +      this.feeAmounts.forEach(fee => {
map вместо foreach + push

2021-09-07 14:46 UTC, axtezy commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/controllers/LiquidityPoolsController.ts
> +    this.feeAmounts.forEach(fee => {
map вместо foreach + push

2021-09-07 14:46 UTC, axtezy commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/controllers/LiquidityPoolsController.ts
> +    return (await Promise.all(poolsPromises)).filter(pool => !!pool);
filter(Boolean)

2021-09-07 14:46 UTC, axtezy commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/controllers/LiquidityPoolsController.ts
> +    const recGraphVisitor = (
Описывать функцию в методе (если это не маленький калбек) - не очень хорошая идея, лучше отдельный метод сделать

2021-09-07 14:46 UTC, axtezy commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/controllers/LiquidityPoolsController.ts
> +        pools.forEach(pool => {
Map вместо foreach + push

2021-09-07 14:46 UTC, axtezy commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/uni-swap-v3.service.ts
> +  private static getSwapRouterExactInputMethodParams(
Методы идут после конструктора

2021-09-07 15:07 UTC, siandreev commented
Нейминг ветки нужно поменять `feature/<description>` или `RUBIC-<task_number>/<description>`

2021-09-08 12:59 UTC, closed without merging

2021-09-09 09:26 UTC, vlad3k commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/uni-swap-v3.service.ts
> +  private static getSwapRouterExactInputMethodParams(
Поправил

2021-09-09 09:26 UTC, vlad3k commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/controllers/LiquidityPoolsController.ts
> +        pools.forEach(pool => {
Поправил

2021-09-09 09:27 UTC, vlad3k commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/controllers/LiquidityPoolsController.ts
> +    const recGraphVisitor = (
Поправил

2021-09-09 09:27 UTC, vlad3k commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/controllers/LiquidityPoolsController.ts
> +    return (await Promise.all(poolsPromises)).filter(pool => !!pool);
Поправил

2021-09-09 09:27 UTC, vlad3k commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/controllers/LiquidityPoolsController.ts
> +  public static getContractPoolsPath(pools: LiquidityPool[], initialTokenAddress: string): string {
Поправил

2021-09-09 09:27 UTC, vlad3k commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/controllers/LiquidityPoolsController.ts
> +  public static isPoolWithTokens(pool: LiquidityPool, tokenA: string, tokenB: string): boolean {
Поправил

2021-09-09 09:27 UTC, vlad3k commented on src/app/core/services/blockchain/web3-public-service/Web3Public.ts
> +  public getContract(address: string, abi: AbiItem[]) {
Поправил

2021-09-09 09:27 UTC, vlad3k commented on src/app/core/services/blockchain/web3-public-service/Web3Public.ts
> +  public encodeFunctionCall(
Поправил

2021-09-09 16:10 UTC, vlad3k commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/controllers/LiquidityPoolsController.ts
> +      this.feeAmounts.forEach(fee => {
решили оставить

2021-09-09 16:10 UTC, vlad3k commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/controllers/LiquidityPoolsController.ts
> +    this.feeAmounts.forEach(fee => {
Решили оставить