Rubic 59
Cryptorubic/rubic-app pull request #760
Opened 2021-09-07 13:59 UTC by axtezy

2021-09-14 15:35 UTC, siandreev requested changes

2021-09-14 15:35 UTC, siandreev commented on src/app/features/tokens-select/components/tokens-list-element/tokens-list-element.component.ts
> +    event.stopImmediatePropagation();
лучше в шаблоне `(click.stop)="toggleFavorite()"`
https://github.com/TinkoffCreditSystems/ng-event-plugins

2021-09-14 15:35 UTC, siandreev commented on src/app/features/tokens-select/components/tokens-select/tokens-select.component.html
> +      [icon]="listType === 'default' ? 'assets/images/icons/star.svg' : 'assets/images/icons/back.svg'"
торчат края под бордером; имхо очень не хватает анимаций для кликательных штук: например, можно уменьшать размер иконки при клике. Для звездочек в списке я бы добавил заливку

2021-09-14 15:35 UTC, siandreev commented on src/app/features/tokens-select/services/tokens-select.service.ts
> +    tokens: BehaviorSubject<AvailableTokenAmount[]>,
зачем?

2021-09-14 15:35 UTC, siandreev commented on src/app/shared/constants/blockchain/BACKEND_BLOCKCHAINS.ts
> +export type BackendBlockchainObject<T> = {
`export type BackendBlockchainObject<T> = Record<BackendBlockchain, T>`
кстати этот тип нигде не используется, надо удалить

2021-09-14 15:35 UTC, siandreev commented on src/app/shared/models/tokens/TokenAmount.ts
> +  favorite?: boolean;
почему необязательное свойство? Думаю лучше false по дефолту

2021-09-15 09:41 UTC, axtezy commented on src/app/features/tokens-select/services/tokens-select.service.ts
> +    tokens: BehaviorSubject<AvailableTokenAmount[]>,
Чтобы следить за изменениями. Из RubicTokensComponent передается через setter обычным списком, а не через Observable и чтобы отслеживать изменения не переписывая половину кода токенов - создаю сабджект.

2021-09-22 09:35 UTC, siandreev requested changes

2021-09-22 09:35 UTC, siandreev commented on src/app/core/errors/errors.service.ts
> +    const otherRPCError = EIP_1474.find(findRPCError);
`return EIP_1474.some(findRPCError);`

2021-09-22 09:35 UTC, siandreev commented on src/app/core/header/components/header/header.component.html
> +    *noFrame="'any'"
просто `*noFrame`

2021-09-22 09:35 UTC, siandreev commented on src/app/core/models/navigator.ts
> +);
в тинькоф либе есть уже этот токен вроде

2021-09-22 09:35 UTC, siandreev commented on src/app/features/tokens-select/components/tokens-list/tokens-list.component.ts
> +
подписать бы

2021-09-22 09:35 UTC, siandreev commented on src/app/features/tokens-select/components/tokens-search-bar/tokens-search-bar.component.html
> +  [tuiTextfieldSize]="'s'"
зачем так?

2021-09-22 09:35 UTC, siandreev commented on src/app/features/tokens-select/services/tokens-select.service.ts
> +    tokens: BehaviorSubject<AvailableTokenAmount[]>,
надо будет потом отрефакторить это. Добавь в код `// TODO: <comment>`, пожалуйста

2021-09-22 10:07 UTC, ottebrut requested changes

2021-09-22 10:08 UTC, ottebrut commented
Убрать все @description и добавить окончания глаголам (Get -> Gets)

2021-09-22 12:32 UTC, ottebrut approved these changes

2021-09-22 12:33 UTC, siandreev approved these changes

2021-09-22 12:34 UTC, merged