Перенес uniswap v3 и zrx провайдеров из старой ветки
Cryptorubic/rubic-app pull request #763
Opened 2021-09-08 13:00 UTC by vlad3k

2021-09-28 15:03 UTC, siandreev commented on src/app/core/services/blockchain/web3-public-service/Web3Public.ts
> +    const methodSignature = contractAbi.find(abiItem => abiItem.name === methodName);
Давай тут проверку на methodSignature !== undefined, и throw иначе. В идеале это можно средствами ts сделать, но сложноватно

2021-09-28 15:06 UTC, siandreev commented on src/app/core/services/blockchain/web3-public-service/Web3Public.ts
> +    });
зачем это?

2021-09-28 15:16 UTC, siandreev commented on src/app/core/services/blockchain/web3-public-service/Web3Public.ts
> +      });
лучше вложенный цикл (а еще лучше map), чем flat и работа с индексами. Очень трудно понять, что тут происходит

2021-09-28 15:18 UTC, siandreev commented on src/app/core/services/gas-service/gas.service.ts
> +    return !!supportedBlockchains.find(supBlockchain => supBlockchain === blockchain);
`return  supportedBlockchains.some(supBlockchain => supBlockchain === blockchain);`

2021-09-28 15:21 UTC, siandreev commented on src/app/core/services/tokens/tokens.service.ts
> +    if (!this.isTestingMode || (this.isTestingMode && tokens.size < 50)) {
почему 50? давай в константу

2021-09-28 15:23 UTC, siandreev commented on src/app/features/instant-trade/components/instant-trade-bottom-form/instant-trade-bottom-form.component.ts
> +            map(({ tradeData, approveData }) => {
надо переделать параллельно в соответствии с тем, что обсудили сегодня

2021-09-28 15:25 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/constants/estimatedGas.ts
> +  new BigNumber(310_000)
надо уточнить (возможно реквест к Иллиане), имхо выглядит завышенным

2021-09-28 15:44 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/common/zrx/zrx.service.ts
> +    );
`return supportedZrxBlockchains.find(supportedBlockchain => supportedBlockchain === blockchain);`

2021-09-28 15:46 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/common/zrx/zrx.service.ts
> +        this.providerConnectorService.address,
this.walletAddress

2021-09-28 15:50 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/common/zrx/zrx.service.ts
> +    return this.web3PrivateService.sendTransaction(this.currentTradeData.to, amount, {
`trySendTransaction`

2021-09-28 15:51 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/common/zrx/zrx.service.ts
> +    this.currentTradeData = await this.fetchTrade(params);
имхо не оч таким образом передавать данные в `createTrade`. Сейчас лучше вряд ли можно сделать, надо в будущем переработать для всех ИТ провайдеров это

2021-09-28 15:51 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/common/zrx/constants/ZRX_API_ADDRESS.ts
> +  // [BLOCKCHAIN_NAME.POLYGON]: 'https://polygon.api.0x.org/'
почему их отключили

2021-09-28 15:52 UTC, siandreev commented
@ottebrut, также не забудь про JSDoc

2021-09-28 17:45 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/utils/liquidity-pool-controller/LiquidityPoolsController.ts
> +        ) {
давно пора

2021-09-28 17:52 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/uni-swap-v3.service.ts
> +    gasPriceInUsd?: BigNumber
чтобы не считать gasPrice дважды

2021-09-28 17:52 UTC, ottebrut commented on src/app/core/services/blockchain/web3-public-service/Web3Public.ts
> +    });
Там же передается несколько методов и для каждого будет своя сигнатура

2021-09-28 17:52 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/uni-swap-v3.service.ts
> +    gasPriceInUsd?: BigNumber
чтобы не считать gasPrice дважды

2021-09-28 17:53 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/constants/estimatedGas.ts
> +  new BigNumber(310_000)
на самом деле заниженным

2021-09-29 07:37 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/utils/liquidity-pool-controller/LiquidityPoolsController.ts
> +    }
библиотека плохо работает с ts

2021-09-29 07:39 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/uni-swap-v3.service.ts
> +    const deadline = Math.floor(Date.now() / 1000) + 60 * this.settings.deadline;
Добавил коммент для settings.deadline, что оно в минутах считается. А так видно, что это преобразование в секунды.

2021-09-29 08:39 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/uni-swap-v3.service.ts
> +  private readonly blockchain: BLOCKCHAIN_NAME;
Мне кажется, такие поля лучше присваивать в конструкторе. Если это была бы какая нибудь константа, зависящая от внешнего ресурса (как адрес апи), то можно было бы захардкодить. Но тут значение, которое настраивается для конкретного класса, и удобнее разграничить объявление и присваивание.

2021-09-29 08:39 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/utils/liquidity-pool-controller/LiquidityPoolsController.ts
> +  private static getQuoterMethodData(
Мне кажется, это не критично и никак не путает

2021-09-29 08:40 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/utils/liquidity-pool-controller/LiquidityPoolsController.ts
> +    this.feeAmounts = [500, 3000, 10000];
написал выше

2021-09-29 08:41 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/uni-swap-v3.service.ts
> +    await this.web3Public.checkBalance(trade.from.token, trade.from.amount, this.walletAddress);
tryExecute должен упасть, если недостаточно баланса или нет аппрува, поэтому по сути можно убрать и то, и то. Но у нас уже есть специальная обработка ошибки баланса, поэтому ее можно оставить.

2021-09-29 08:41 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/common/zrx/constants/ZRX_API_ADDRESS.ts
> +  // [BLOCKCHAIN_NAME.POLYGON]: 'https://polygon.api.0x.org/'
очень популярных токенов

2021-09-29 09:40 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/utils/liquidity-pool-controller/LiquidityPoolsController.ts
> +    this.feeAmounts = [500, 3000, 10000];
имхо это константа и она должна быть сразу видна при объявлении поля

2021-09-29 09:41 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/uni-swap-v3.service.ts
> +  private readonly blockchain: BLOCKCHAIN_NAME;
во-первых, это увеличивает код конструктора, а во-вторых, лучше, когда такие штуки сразу видны. В данном случае это поле -- константа а константам присваивается значение при определении

2021-09-29 09:43 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/utils/liquidity-pool-controller/LiquidityPoolsController.ts
> +export class LiquidityPoolsController {
Зачем его через new создавать? Почему бы не воспользоваться DI?

2021-09-29 09:47 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/uni-swap-v3.service.ts
> +    gasPriceInUsd?: BigNumber
предлагаю в газ сервисе сделать геттер (помимо геттера в формате потока) текущего газа в формате числа, и геттер для этого значения в $

2021-09-29 09:48 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/uni-swap-v3.service.ts
> +    gasPriceInUsd?: BigNumber
можно отложить это в бэклог, потому что надо бы коингеко сервис еще переделать под это

2021-09-29 09:49 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/uni-swap-v3.service.ts
> +    await this.web3Public.checkBalance(trade.from.token, trade.from.amount, this.walletAddress);
> Но у нас уже есть специальная обработка ошибки баланса, поэтому ее можно оставить.
оно разве не в swap button проверяется?

2021-09-29 09:50 UTC, siandreev commented on src/app/core/services/blockchain/web3-public-service/Web3Public.ts
> +    });
и что происходит с результатом map-а?

2021-09-29 09:51 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/constants/estimatedGas.ts
> +  new BigNumber(310_000)
отпиши, как Иллиана проверит

2021-09-29 09:55 UTC, siandreev requested changes

2021-09-29 09:55 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/utils/liquidity-pool-controller/LiquidityPoolsController.ts
> +            LiquidityPool.isPoolWithTokens(pool, methodArguments.tokenA, methodArguments.tokenB) &&
я имел в виду перенести метод, который был статическим)
тут теперь в статический метод класса `LiquidityPool` передается экземпляр `LiquidityPool`. Метод лучше сделать обычным: `pool.isPoolWithTokens(methodArguments.tokenA, methodArguments.tokenB)`
для второго метода, про который я писал, аналогично

2021-09-29 09:58 UTC, siandreev requested changes

2021-09-29 09:58 UTC, siandreev commented on src/app/core/services/blockchain/web3-public-service/Web3Public.ts
> +        outputIndex++;
почему бы не использовать индекс-аргумент внутри второго мапа?

2021-09-29 09:58 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/utils/liquidity-pool-controller/LiquidityPoolsController.ts
> +    const quoterMethodsData = [...Array(routeMaxTransitPools + 1)]
не хочешь все-таки либу подключить ту? Крайне полезной выглядит

2021-09-29 09:58 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/utils/liquidity-pool-controller/LiquidityPoolsController.ts
> +    const quoterMethodsData = [...Array(routeMaxTransitPools + 1)]
чтобы не писать [...Array(number)]

2021-09-29 09:58 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/utils/liquidity-pool-controller/LiquidityPoolsController.ts
> +    const quoterMethodsData = [...Array(routeMaxTransitPools + 1)]
если не хочешь, то резольвь комент)

2021-09-29 10:02 UTC, siandreev requested changes

2021-09-29 10:02 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/utils/liquidity-pool-controller/LiquidityPoolsController.ts
> +            !Utils.compareAddresses(toTokenAddress, routerTokenAddress)
давай это лучше сделаем просто модулем с функциями (как `web3-utils`). То есть не класс, а просто 
```
export function compareAddresses() {
...
}
```
чтобы не писать везде `Utils.compareAddresses`, а писать просто `compareAddresses`

2021-09-29 10:02 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/utils/liquidity-pool-controller/LiquidityPoolsController.ts
> +            !Utils.compareAddresses(toTokenAddress, routerTokenAddress)
к тому же этот класс (Utils) будет обладать только статическими функциями, поэтому от класса смысла нет особо

2021-09-29 10:40 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/uni-swap-v3.service.ts
> +    await this.web3Public.checkBalance(trade.from.token, trade.from.amount, this.walletAddress);
Проверяется и в целом можно убрать везде эту проверку. Просто если что то пойдет не так, то пользователь сразу увидит ошибку.

2021-09-29 10:41 UTC, ottebrut commented on src/app/core/services/blockchain/web3-public-service/Web3Public.ts
> +    });
Случайно продублировал

2021-09-29 10:42 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/utils/liquidity-pool-controller/LiquidityPoolsController.ts
> +            LiquidityPool.isPoolWithTokens(pool, methodArguments.tokenA, methodArguments.tokenB) &&
Второй метод неудобно переносить, там к самому пулу относятся 3 строчки

2021-09-29 10:43 UTC, ottebrut commented on src/app/core/services/blockchain/web3-public-service/Web3Public.ts
> +        outputIndex++;
Потому что он не соответствует нужному индексу в outputs

2021-09-29 10:43 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/utils/liquidity-pool-controller/LiquidityPoolsController.ts
> +    const quoterMethodsData = [...Array(routeMaxTransitPools + 1)]
Я подключал, в ней нет проверки типов

2021-09-29 10:44 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/utils/liquidity-pool-controller/LiquidityPoolsController.ts
> +    const quoterMethodsData = [...Array(routeMaxTransitPools + 1)]
И подключается она только через require()

2021-09-29 10:45 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/uni-swap-v3.service.ts
> +  private readonly blockchain: BLOCKCHAIN_NAME;
Мне лично лучше видно, когда эти поля первыми присваиваются в конструкторе. Можно спросить у других.

2021-09-29 10:48 UTC, ottebrut commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/utils/liquidity-pool-controller/LiquidityPoolsController.ts
> +export class LiquidityPoolsController {
Во первых, он используется лишь в одном сервисе в качестве utils и не нужен всему проекту. Во вторых, зачем писать больше кода и передавать другие сервисы в конструктор, когда с помощью new я сразу передам конкретные значения.

2021-09-30 06:59 UTC, siandreev commented on src/app/core/services/blockchain/web3-public-service/Web3Public.ts
> +        outputIndex++;
не очень понял. Разве так не получится?

```
return contractsData.map(contractData =>
      contractData.methodsData.map((methodData, outputIndex) => {
        const methodOutputAbi = contractAbi.find(
          funcSignature => funcSignature.name === methodData.methodName
        ).outputs;
        const output = outputs[outputIndex];

        return {
          success: output.success,
          output: output.success
            ? (this.web3.eth.abi.decodeParameters(methodOutputAbi, output.returnData) as Output)
            : null
        };
      })
    );
```

2021-09-30 08:15 UTC, ottebrut commented on src/app/core/services/blockchain/web3-public-service/Web3Public.ts
> +        outputIndex++;
outputIndex завиит и от contractData, а у тебя нет

2021-09-30 11:07 UTC, siandreev commented on src/app/core/services/blockchain/web3-public-service/Web3Public.ts
> +        outputIndex++;
ага, не заметил, ок

2021-09-30 11:13 UTC, siandreev approved these changes
Осталось только дать комент/референс на объяснение/структуру в контракте на эзерскане в методе `getEncodedPoolsPath` и уточнить у Иллианы по газу. Остальное ок

2021-10-01 15:19 UTC, merged