Gas price APIs for ethereum are updated
Cryptorubic/rubic-app pull request #800
Opened 2021-09-20 11:50 UTC by ottebrut

2021-09-20 13:26 UTC, vlad3k approved these changes

2021-09-20 15:20 UTC, axtezy requested changes

2021-09-20 15:20 UTC, axtezy commented on src/app/core/services/gas-service/gas.service.ts
>     * @description Fetch gas in current network.
Удалить `@description`

2021-09-21 07:28 UTC, ottebrut commented on src/app/core/services/gas-service/gas.service.ts
>     * @description Fetch gas in current network.
поправил

2021-09-21 09:33 UTC, axtezy approved these changes

2021-09-21 09:33 UTC, merged