[FEATURE] Rubic 125/fantom
Cryptorubic/rubic-app pull request #879
Opened 2021-10-18 08:09 UTC by vlad3k

2021-11-11 10:25 UTC, axtezy approved these changes

2021-11-12 09:06 UTC, siandreev requested changes

2021-11-12 09:06 UTC, siandreev commented on src/app/core/services/backend/instant-trades-api/instant-trades-api.service.ts
> +
надо бы удалить

2021-11-12 09:06 UTC, siandreev commented on src/app/core/services/blockchain/constants/multicall-addresses.ts
> +  [BLOCKCHAIN_NAME.FANTOM]: '0x22D4cF72C45F8198CfbF4B568dBdB5A85e8DC0B5',
это точно мультикол? На эксплорере он не верифицирован. Откуда ты взял его адрес?

2021-11-12 09:12 UTC, vlad3k commented on src/app/core/services/backend/instant-trades-api/instant-trades-api.service.ts
> +
Готово

2021-11-12 09:17 UTC, vlad3k commented on src/app/core/services/blockchain/constants/multicall-addresses.ts
> +  [BLOCKCHAIN_NAME.FANTOM]: '0x22D4cF72C45F8198CfbF4B568dBdB5A85e8DC0B5',
Брал отсюда https://github.com/sushiswap/sushiswap-sdk/blob/canary/src/constants/addresses.ts

2021-11-16 11:40 UTC, axtezy approved these changes

2021-11-16 11:58 UTC, siandreev approved these changes

2021-11-18 13:20 UTC, merged