Rubic 146/bugs
Cryptorubic/rubic-app pull request #896
Opened 2021-10-26 14:45 UTC by vlad3k

2021-11-01 07:50 UTC, vlad3k commented on src/app/core/errors/errors.service.ts
> +  public findRPCError(
Поправил

2021-11-01 07:50 UTC, vlad3k commented on src/app/core/errors/errors.service.ts
> +    let providerRPCError: boolean;
Поправил

2021-11-01 07:50 UTC, vlad3k commented on src/scss/_taiga-slyles.scss
> +tui-badge.notification-counter {
Поправил

2021-11-02 13:56 UTC, axtezy requested changes

2021-11-02 13:56 UTC, axtezy commented on src/app/features/my-trades/components/my-trades/components/table/table.component.ts
> +  private isPrimarySort = true;
`isFirstView`

2021-11-02 13:56 UTC, axtezy commented on src/app/features/my-trades/components/my-trades/components/table/table.component.ts
> +        map((dir, index) => {
`tap`

2021-11-02 13:56 UTC, axtezy commented on src/scss/_taiga-slyles.scss
> +
Пробелы лишние

2021-11-02 13:56 UTC, axtezy commented on src/scss/_taiga-slyles.scss
> +  tui-badge.notification-counter {
Вынести на уровень компонента

2021-11-02 14:12 UTC, vlad3k commented on src/app/features/my-trades/components/my-trades/components/table/table.component.ts
> +  private isPrimarySort = true;
Поправил

2021-11-02 14:12 UTC, vlad3k commented on src/app/features/my-trades/components/my-trades/components/table/table.component.ts
> +        map((dir, index) => {
Решили так

2021-11-02 14:12 UTC, vlad3k commented on src/scss/_taiga-slyles.scss
> +
Удалил

2021-11-02 14:12 UTC, vlad3k commented on src/scss/_taiga-slyles.scss
> +  tui-badge.notification-counter {
Удалил, оказался лишний код

2021-11-02 14:13 UTC, axtezy approved these changes

2021-11-02 14:20 UTC, siandreev requested changes

2021-11-02 14:20 UTC, siandreev commented on src/app/shared/components/notification-badge/notification-badge.component.ts
> +@Component({
jsdoc

2021-11-02 14:20 UTC, siandreev commented on src/app/shared/components/notification-badge/notification-badge.component.ts
> +
jsdoc

2021-11-02 14:20 UTC, siandreev commented on src/assets/i18n/es.json
> +    "insufficientFunds1inch": "You have not enough amount of {{ nativeToken }} for transfer and gas fee. For transaction enter less amount or top up your {{ nativeToken }} balance.",
не похоже на испанский)

2021-11-02 14:20 UTC, siandreev commented on src/assets/i18n/ko.json
> +    "insufficientFunds1inch": "You have not enough amount of {{ nativeToken }} for transfer and gas fee. For transaction enter less amount or top up your {{ nativeToken }} balance.",
перевод

2021-11-02 14:20 UTC, siandreev commented on src/assets/i18n/ru.json
> +    "insufficientFunds1inch": "You have not enough amount of {{ nativeToken }} for transfer and gas fee. For transaction enter less amount or top up your {{ nativeToken }} balance.",
перевод

2021-11-02 14:20 UTC, siandreev commented on src/assets/i18n/zh.json
> +    "insufficientFunds1inch": "You have not enough amount of {{ nativeToken }} for transfer and gas fee. For transaction enter less amount or top up your {{ nativeToken }} balance.",
перевод

2021-11-02 14:40 UTC, siandreev approved these changes

2021-11-02 14:40 UTC, vlad3k commented on src/app/shared/components/notification-badge/notification-badge.component.ts
> +@Component({
Добавил

2021-11-02 14:40 UTC, vlad3k commented on src/app/shared/components/notification-badge/notification-badge.component.ts
> +
Добавил

2021-11-02 14:40 UTC, vlad3k commented on src/assets/i18n/es.json
> +    "insufficientFunds1inch": "You have not enough amount of {{ nativeToken }} for transfer and gas fee. For transaction enter less amount or top up your {{ nativeToken }} balance.",
Добавил

2021-11-02 14:41 UTC, vlad3k commented on src/assets/i18n/zh.json
> +    "insufficientFunds1inch": "You have not enough amount of {{ nativeToken }} for transfer and gas fee. For transaction enter less amount or top up your {{ nativeToken }} balance.",
Добавил

2021-11-02 14:47 UTC, merged