Rubic-199 binance bridge upd
Cryptorubic/rubic-app pull request #921
Opened 2021-11-03 11:28 UTC by vlad3k

2021-11-03 11:40 UTC, axtezy requested changes

2021-11-03 11:40 UTC, axtezy commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +    return this.httpService.post('bridges/transactions', body).toPromise() as Promise<void>;
`return this.httpService.post<void>('bridges/transactions', body).toPromise();`

2021-11-03 11:40 UTC, axtezy commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +    return this.httpService.post('bridges/transactions', body).toPromise() as Promise<void>;
`return this.httpService.post<void>('bridges/transactions', body).toPromise();`

2021-11-03 11:40 UTC, axtezy commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +    return this.httpService.post('bridges/transactions', body).toPromise() as Promise<void>;
См. выше

2021-11-03 11:40 UTC, axtezy commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +    return this.httpService
`.patch<void>`

2021-11-03 11:40 UTC, axtezy commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +    return this.httpService.post('bridges/transactions', body).toPromise() as Promise<void>;
`.post<void>`

2021-11-03 11:40 UTC, axtezy commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +    return this.httpService.post('bridges/transactions', body).toPromise() as Promise<void>;
`.post<void>`

2021-11-03 11:40 UTC, axtezy commented on src/app/core/services/backend/bridge-api/models/BridgeTableTradeApi.ts
> +  fromTransactionHash: string;
А `toTransactionHash`?

2021-11-03 11:40 UTC, axtezy commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +          return of([]);
Мне кажется это не оч хорошо, что если бек тупит, мы просто пустую таблицу выводим, юзеры будут жаловаться что не могут свои транзакции найти

2021-11-03 11:40 UTC, axtezy commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +      transactionHash: trade.fromTransactionHash,
А `toTransactionHash` вообще не будет использоваться?

2021-11-03 11:43 UTC, vlad3k commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +      transactionHash: trade.fromTransactionHash,
Как я понял, что он особо и не нужен. 
Саша М. сказал что не может быть такого, что придет только from или to. Они либо оба придут либо будут пустые. А для отправки они не требуются ни на какой endpoint

2021-11-03 11:50 UTC, siandreev commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +          return of([]);
давайте уведомление добавим

2021-11-03 11:50 UTC, siandreev commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +          return of([]);
но при этом чтобы все остальное в май трейдс не падало

2021-11-03 12:52 UTC, vlad3k commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +          return of([]);
Хорошо, добавляю)

2021-11-03 12:53 UTC, vlad3k commented on src/app/core/services/backend/bridge-api/models/BridgeTableTradeApi.ts
> +  fromTransactionHash: string;
Ответил ниже

2021-11-03 14:05 UTC, vlad3k commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +    return this.httpService.post('bridges/transactions', body).toPromise() as Promise<void>;
Поправил

2021-11-03 14:06 UTC, vlad3k commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +    return this.httpService.post('bridges/transactions', body).toPromise() as Promise<void>;
Поправил

2021-11-03 14:06 UTC, vlad3k commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +    return this.httpService.post('bridges/transactions', body).toPromise() as Promise<void>;
Поправил

2021-11-03 14:06 UTC, vlad3k commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +    return this.httpService
поправил

2021-11-03 14:06 UTC, vlad3k commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +    return this.httpService.post('bridges/transactions', body).toPromise() as Promise<void>;
Поправил

2021-11-03 14:10 UTC, vlad3k commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +    return this.httpService.post('bridges/transactions', body).toPromise() as Promise<void>;
Поправил

2021-11-03 14:10 UTC, vlad3k commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +          return of([]);
Добавил

2021-11-03 15:41 UTC, axtezy requested changes

2021-11-03 15:41 UTC, axtezy commented on src/app/shared/models/my-trades/TableTrade.ts
>    transactionId?: string;
А transactionId зачем теперь в таблице?

2021-11-03 15:52 UTC, ottebrut requested changes

2021-11-03 15:52 UTC, ottebrut commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +        timeout(3000),
Зачем?

2021-11-03 15:52 UTC, ottebrut commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +   * Makes POST request for add transaction to database.
for add -> to add

2021-11-03 15:52 UTC, ottebrut commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +   * Makes POST request for add transaction to database.
for add -> to add

2021-11-03 15:52 UTC, ottebrut commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +   * Makes POST request for add transaction to database.
for add -> to add

2021-11-03 15:52 UTC, ottebrut commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +   * Makes PATCH request for update polygon bridge transaction in database.
for update -> to update

2021-11-03 15:52 UTC, ottebrut commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +   * Makes POST request for add transaction to database.
for add -> to add

2021-11-03 15:52 UTC, ottebrut commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +   * Makes POST request for add transaction to database.
for add -> to add

2021-11-03 15:52 UTC, ottebrut commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +   * Makes POST request for notify bridge bot.
for notify -> to notify

2021-11-03 15:52 UTC, ottebrut commented on src/app/features/my-trades/components/my-trades/components/abstract-table-data-component.ts
> +      : trade.fromToken.blockchain;
удали пустую строку

2021-11-03 15:52 UTC, ottebrut commented on src/app/features/my-trades/components/my-trades/my-trades.component.ts
> +        takeUntil(this.destroy$),
takeUntil должен быть последним

2021-11-03 15:52 UTC, ottebrut commented on src/app/features/my-trades/components/my-trades/my-trades.component.ts
> +          console.error(e);
зачем, если внутри errorsService есть console.debug?

2021-11-03 15:53 UTC, siandreev approved these changes
Переводы, а так ок

2021-11-03 15:54 UTC, vlad3k commented on src/app/shared/models/my-trades/TableTrade.ts
>    transactionId?: string;
Поменял

2021-11-03 16:06 UTC, axtezy approved these changes

2021-11-09 09:25 UTC, vlad3k commented on src/app/core/services/backend/bridge-api/bridge-api.service.ts
> +        timeout(3000),
Убрал

2021-11-09 12:38 UTC, ottebrut approved these changes

2021-11-11 13:16 UTC, axtezy approved these changes

2021-11-11 16:50 UTC, merged