Rubic 194/favorite-tokens + linter rule
Cryptorubic/rubic-app pull request #939
Opened 2021-11-09 10:20 UTC by axtezy

2021-11-16 11:37 UTC, ottebrut requested changes

2021-11-16 11:37 UTC, ottebrut commented on src/app/core/services/query-params/query-params.service.ts
> +        switchMap(fetchedToken => this.getTokenWithBalance(fetchedToken))
Тут можно избавиться от извлечения баланса, потому что в `swaps.service` уже прописана логика, что, когда выбирается новый токен в форме и его баланс не посчитан, то считается баланс

2021-11-16 11:37 UTC, ottebrut commented on src/app/core/services/query-params/query-params.service.ts
> +          switchMap(fetchedToken => this.getTokenWithBalance(fetchedToken))
Написал выше

2021-11-16 11:37 UTC, ottebrut commented on src/app/core/services/tokens/tokens.service.ts
> +   * @param tokensWithoutBalance Favorite token list.
favorite token -> favorite tokens

2021-11-16 11:37 UTC, ottebrut commented on src/app/core/services/tokens/tokens.service.ts
> +  public async calculateFavoriteTokensBalances(
А нельзя `favoriteTokens` вставить как подмножество в общий массив `tokens` и не разделять одинаковую логику подсчета баланса? Единственная разница будет в поле `favorite: true / false`.

2021-11-16 11:37 UTC, ottebrut commented on src/app/features/swaps/components/swaps-form/swaps-form.component.ts
> +  private setAvailableFavoriteTokens(tokenType: TokenType): void {
Написал выше про объединение массивов токенов, пока что вот эта и похожие функции кажутся слишком излишними

2021-11-16 13:23 UTC, axtezy commented on src/app/features/swaps/components/swaps-form/swaps-form.component.ts
> +  private setAvailableFavoriteTokens(tokenType: TokenType): void {
Поправил

2021-11-16 13:23 UTC, axtezy commented on src/app/core/services/tokens/tokens.service.ts
> +  public async calculateFavoriteTokensBalances(
Поправил

2021-11-17 09:59 UTC, ottebrut requested changes

2021-11-17 09:59 UTC, ottebrut commented on src/app/core/services/query-params/query-params.service.ts
> +  private getTokenWithBalance(fetchedToken: Token): Observable<TokenAmount> {
Эта функция уже нигде не используется

2021-11-17 09:59 UTC, ottebrut commented on src/app/core/services/tokens/tokens.service.ts
> +    const newTokens = this.setDefaultTokensParams(tokens, type === 'default');
type === 'favorite'

2021-11-17 09:59 UTC, ottebrut commented on src/app/core/services/tokens/tokens.service.ts
> +  public async getTokensWithBalance(tokens: List<TokenAmount>): Promise<TokenAmount[]> {
Можно снова сделать private

2021-11-17 09:59 UTC, ottebrut commented on src/app/features/cross-chain-routing/components/cross-chain-routing-bottom-form/cross-chain-routing-bottom-form.component.ts
> +          await this.tokensService.calculateTokensBalances('favorite');
Может быть сделать две функции: `calculateTokensBalances` и `calculateTokensBalancesByType`. Компоненты будут вызывать `calculateTokensBalances`, и внутри нее будет два раза вызываться `calculateTokensBalancesByType`.

2021-11-17 09:59 UTC, ottebrut commented on src/app/features/tokens-select/components/tokens-list/tokens-list.component.ts
> +    public readonly authService: AuthService,
public? надо бы все таки отдельный observable `user$`

2021-11-17 09:59 UTC, ottebrut commented on src/app/features/swaps/services/swaps-service/swaps.service.ts
> +      const updatedBridgeFavoriteTokenPairsByBlockchainsArray =
Логику для `updatedBridgeFavoriteTokenPairsByBlockchainsArray` и `updatedBridgeTokenPairsByBlockchainsArray` можно засунуть в одну функцию (я бы сделал локальную функцию)

2021-11-17 09:59 UTC, ottebrut commented on src/app/features/tokens-select/components/tokens-select/tokens-select.component.ts
> +  private tokensToShowSubject$: BehaviorSubject<AvailableTokenAmount[]>;
tokensToShowSubject$ -> _ tokensToShow$
Инициализацию для таких переменных можно делать при объявлении

2021-11-17 09:59 UTC, ottebrut commented on src/app/features/tokens-select/components/tokens-select/tokens-select.component.ts
> +    this.searchQuery$.pipe(debounceTime(500), takeUntil(this.destroy$)).subscribe(() => {
Почему убрал skip(1)? Первый вызов бесполезен.

2021-11-17 09:59 UTC, ottebrut commented on src/app/features/tokens-select/components/tokens-select/tokens-select.component.ts
> +    this.updateTokensByQuerySubscription$ = this.updateTokensByQuery$
Я бы добавил в начале проверку 
`if (this.updateTokensByQuerySubscription$) return;`

2021-11-17 09:59 UTC, ottebrut commented on src/app/features/tokens-select/components/tokens-select/tokens-select.component.ts
> +  private tokensToShowSubject$: BehaviorSubject<AvailableTokenAmount[]>;
Можно еще добавить геттер
```
get tokensToShow():AvailableTokenAmount[] {
    return this.tokensToShowSubject$.getValue()
}
```

2021-11-17 09:59 UTC, ottebrut commented on src/app/features/tokens-select/components/tokens-select/tokens-select.component.ts
> +      this.cdr.detectChanges();
markForCheck

2021-11-17 09:59 UTC, ottebrut commented on src/app/features/tokens-select/components/tokens-select/tokens-select.component.ts
> +    this.favoriteTokens$.subscribe(favoriteTokens => {
тут не нужно `.pipe(first())`?

2021-11-17 09:59 UTC, ottebrut commented on src/app/features/tokens-select/components/tokens-select/tokens-select.component.ts
> +   * Map default tokens list with favorite.
Maps

2021-11-17 09:59 UTC, ottebrut commented on src/app/features/tokens-select/components/tokens-select/tokens-select.component.ts
> +      .pipe(takeUntil(this.destroy$))
Зачем `takeUntil(this.destroy$) `, если до этого уже прописаны `pipe(first())`? 
`forkJoin` сразу завершится

2021-11-17 11:45 UTC, axtezy commented on src/app/features/cross-chain-routing/components/cross-chain-routing-bottom-form/cross-chain-routing-bottom-form.component.ts
> +          await this.tokensService.calculateTokensBalances('favorite');
Да, имеет смысл

2021-11-17 13:38 UTC, ottebrut requested changes

2021-11-17 13:38 UTC, ottebrut commented on src/app/features/bridge/components/bridge-bottom-form/bridge-bottom-form.component.ts
> +            this.tokensService.calculateTokensBalancesByType('favorite')
`this.tokensService.calculateTokensBalances()`

2021-11-17 13:38 UTC, ottebrut commented on src/app/features/bridge/components/bridge-bottom-form/bridge-bottom-form.component.ts
> +            this.tokensService.calculateTokensBalancesByType('favorite')
`this.tokensService.calculateTokensBalances()`

2021-11-17 13:50 UTC, siandreev requested changes

2021-11-17 13:50 UTC, siandreev commented on src/app/core/services/tokens/tokens.service.ts
> +      oldTokens || (type === 'favorite' ? this._favoriteTokens$.value : this._tokens$.value);
`oldTokens || subject$.value;`

2021-11-17 13:50 UTC, siandreev commented on src/app/core/services/tokens/tokens.service.ts
> +  public removeFavoriteToken(token: TokenAmount, callback: () => void): void {
я бы тут и везде в остальных подобных местах переименовал это в `onError`

2021-11-17 13:50 UTC, siandreev commented on src/app/features/bridge/components/bridge-bottom-form/bridge-bottom-form.component.ts
> +        ),
давай это в отдельную функцию, оно дублируется снизу

2021-11-17 13:50 UTC, siandreev commented on src/app/features/swaps/components/swaps-form/swaps-form.component.ts
> +        }
давай это тоже в отдельную функцию

2021-11-17 13:50 UTC, siandreev commented on src/app/features/swaps/services/swaps-service/swaps.service.ts
> +    }
имхо это неочевидно, что функция с названием get... будет мутировать один из аргументов. Лучше тогда сделать еще одну функцию getAndPush... которая будет использовать эту + изменять массив

2021-11-17 13:55 UTC, axtezy commented on src/app/core/services/tokens/tokens.service.ts
> +  public removeFavoriteToken(token: TokenAmount, callback: () => void): void {
Переименую в `onComplete`, потому что колбэк срабатывает и если нет ошибки

2021-11-17 14:36 UTC, axtezy commented on src/app/features/swaps/services/swaps-service/swaps.service.ts
> +    }
Соглы, но так было уже написано. Изначально был метод на 150 строк с функциями внутри, я вынес отдельно метод, но мутация данных `updatedTokensAmount` еще с `subscribeOnTokens` начинается. Я пока переименую просто, чтобы было понятно что там мутации, но нужно переписать эти методы

2021-11-17 15:47 UTC, siandreev requested changes

2021-11-17 15:47 UTC, siandreev commented on src/app/core/services/tokens/tokens.service.ts
> +  public removeFavoriteToken(token: TokenAmount, callback: () => void): void {
Почему бы тогда не возвращать observable?

2021-11-17 16:00 UTC, axtezy commented on src/app/core/services/tokens/tokens.service.ts
> +  public removeFavoriteToken(token: TokenAmount, callback: () => void): void {
Действительно, исправил

2021-11-17 16:19 UTC, ottebrut requested changes

2021-11-17 16:19 UTC, ottebrut commented on src/app/features/tokens-select/components/tokens-select/tokens-select.component.ts
> +  private favoriteTokensToShowSubject$: BehaviorSubject<AvailableTokenAmount[]>;
_favoriteTokensToShow$

2021-11-17 16:19 UTC, ottebrut commented on src/app/features/tokens-select/components/tokens-select/tokens-select.component.ts
> +  }
Давай инициализировать при объявлении. И вместо геттера обычное поле (тоже инициализировать при объявлении).
С `favoriteTokens` тоже самое.

2021-11-17 16:19 UTC, ottebrut commented on src/app/features/tokens-select/components/tokens-select/tokens-select.component.ts
> +    if (this.updateTokensByQuerySubscription$) return;
Давай все таки с фигурными скобками и пустой строкой после

2021-11-17 16:19 UTC, ottebrut commented on src/app/shared/components/rubic-tokens/rubic-tokens.component.ts
> +  public favoriteTokensSubject$: BehaviorSubject<AvailableTokenAmount[]>;
```
private _tokens$
private _favoriteTokens$
```

2021-11-19 10:58 UTC, ottebrut approved these changes

2021-11-19 11:17 UTC, siandreev approved these changes

2021-11-19 11:18 UTC, merged