Feaure/transaction info
Cryptorubic/rubic-app pull request #941
Opened 2021-11-10 14:00 UTC by ottebrut

2021-11-10 15:57 UTC, siandreev requested changes
Посмотрел что успел

2021-11-10 15:57 UTC, siandreev commented on src/app/core/services/blockchain/web3/web3-public-service/Web3Public.ts
> +};
Record

2021-11-10 15:57 UTC, siandreev commented on src/app/core/services/blockchain/web3/web3-public-service/Web3Public.ts
> +    const tokensSymbolsCache: { [address: string]: string } = {};
почему не @Cacheable?

2021-11-10 15:57 UTC, siandreev commented on src/app/core/services/price-impact/price-impact.service.ts
> +  }
почему не сеттер?

2021-11-10 15:57 UTC, siandreev commented on src/app/features/instant-trade/services/instant-trade-service/providers/ethereum/uni-swap-v3-service/uni-swap-v3.service.ts
> +    });
почему не map?

2021-11-10 15:57 UTC, siandreev commented on src/app/features/swaps/components/swap-info/components/cross-chain-swap-info/components/bridge-swap-info/bridge-swap-info.component.ts
> +          return this.bridgeService.getBridgeTrade().pipe(
лишние скобки и return

2021-11-10 15:57 UTC, siandreev commented on src/app/features/swaps/components/swap-info/components/cross-chain-swap-info/components/ccr-swap-info/ccr-swap-info.component.scss
> +@import '../../../../styles/styles';
😯

2021-11-10 15:57 UTC, siandreev commented on src/app/features/swaps/components/swap-info/components/cross-chain-swap-info/components/ccr-swap-info/ccr-swap-info.component.ts
> +
Предлагаю разбить это на функции, очень большая функция тут

2021-11-10 15:57 UTC, siandreev commented on src/app/features/swaps/components/swap-info/components/cross-chain-swap-info/components/ccr-swap-info/ccr-swap-info.component.ts
> +      });
лучше `watch(this.cdr)` пайп оператор из тайги

2021-11-10 15:57 UTC, siandreev commented on src/app/features/swaps/components/swap-info/components/cross-chain-swap-info/cross-chain-swap-info.component.scss
> +@import '../../styles/styles';
?

2021-11-10 15:57 UTC, siandreev commented on src/app/features/swaps/components/swap-info/components/cross-chain-swap-info/cross-chain-swap-info.component.ts
> +    )}`;
есть `short-address.pipe`

2021-11-10 15:57 UTC, siandreev commented on src/app/features/swaps/components/swap-info/components/swap-info-container/swap-info-container.component.ts
> +    });
watch и destroy

2021-11-10 16:18 UTC, axtezy requested changes

2021-11-10 16:18 UTC, axtezy commented on src/app/features/swaps/components/swap-info/components/cross-chain-swap-info/cross-chain-swap-info.component.scss
> +@import '../../styles/styles';
Зачем?

2021-11-10 16:18 UTC, axtezy commented on src/app/shared/components/buttons/swap-button-container/components/swap-button/swap-button.component.html
> -    'button-swap_warning-high': priceImpact >= PRICE_IMPACT.HIGH
Мне не оч нравятся всякие сложные условия в шаблонах, мб вынести в метод получение классов?

2021-11-10 16:18 UTC, axtezy commented on src/app/shared/components/buttons/swap-button-container/components/swap-button/swap-button.component.html
> +      ? 'Swap Anyway'
Так prettier сделал? Кажется тут на 1 там вперед должно быть

2021-11-10 16:18 UTC, axtezy commented on src/app/shared/components/buttons/swap-button-container/components/swap-button/swap-button.component.scss
> +  &_warning-yellow {
Имена классов должны отражать объективные параметры, а не полагаться на стилистику.
Лучше было бы использовать `warning-serious` вместо `warning-red `, потому что важная ошибка может быть и не красной, теоретически

2021-11-10 16:18 UTC, axtezy commented on src/app/shared/components/token-amount-estimated/token-amount-estimated.component.ts
> +    this.swapFormService.outputValueChanges.pipe(takeUntil(this.destroy$)).subscribe(form => {
Разбить бы то что в ngOnInit на разные методы

2021-11-10 16:18 UTC, axtezy commented on src/app/shared/components/token-amount-estimated/token-amount-estimated.component.ts
> +  private getUsdPrice() {
return value type

2021-11-10 18:44 UTC, ottebrut commented on src/app/core/services/blockchain/web3/web3-public-service/Web3Public.ts
> +    const tokensSymbolsCache: { [address: string]: string } = {};
@Cacheable работает так: если ты вызовешь функцию с другим параметром, то предидущее значение он затирает. Мне нужно было, чтобы он запоминал все значения.

2021-11-10 18:45 UTC, ottebrut commented on src/app/core/services/price-impact/price-impact.service.ts
> +  }
Мне кажется,  у сервиса вызов метода более привычен, чем вызов сеттера.

2021-11-10 18:49 UTC, ottebrut commented on src/app/features/swaps/components/swap-info/components/cross-chain-swap-info/components/ccr-swap-info/ccr-swap-info.component.scss
> +@import '../../../../styles/styles';
А как иначе? Если что это не главный styles

2021-11-10 18:49 UTC, ottebrut commented on src/app/features/swaps/components/swap-info/components/cross-chain-swap-info/components/ccr-swap-info/ccr-swap-info.component.ts
> +      });
watch вызывает cdr.detectChanges() - нам же лучше вызывать markForCheck()

2021-11-10 18:54 UTC, ottebrut commented on src/app/core/services/blockchain/web3/web3-public-service/Web3Public.ts
> +  private getTokenSymbolCachingDecorator(): (tokenAddress: string) => Promise<string> {
Ответил выше на коммент @siandreev

2021-11-10 19:27 UTC, ottebrut commented on src/app/features/instant-trade/components/providers-panels/components/providers-panels-container/providers-panels-container.component.html
> +    {{ !allProvidersShown ? 'Show more providers' : 'Hide providers' }}
Мне кажется, когда перевод понадобиться, тебе прямо скажут, какую строчку переводить)

2021-11-10 19:37 UTC, ottebrut commented on src/app/features/swaps/components/swap-info/components/cross-chain-swap-info/components/bridge-swap-info/bridge-swap-info.component.html
> +        >When receiving tokens on the Ethereum network, you will need to pay for gas</span
Ответил выше. Когда переводы понадобятся, кто то и начнет с этим работу.

2021-11-10 19:38 UTC, ottebrut commented on src/app/features/swaps/components/swap-info/components/cross-chain-swap-info/cross-chain-swap-info.component.scss
> +@import '../../styles/styles';
ответил @siandreev

2021-11-10 19:56 UTC, ottebrut commented on src/app/features/swaps/components/swap-info/components/swap-info-container/swap-info-container.component.ts
> +    });
destroy добавил, по watch выше написал

2021-11-10 19:57 UTC, ottebrut commented on src/app/features/cross-chain-routing/services/cross-chain-routing-service/cross-chain-routing.service.ts
> +   * @param walletAddress Wallet address.
Описал, как смог, формат лучше не придумал

2021-11-10 19:58 UTC, ottebrut commented on src/app/shared/components/buttons/swap-button-container/components/swap-button/swap-button.component.html
> +      ? 'Swap Anyway'
Так сделал eslint, можешь позже поменять это правило

2021-11-10 20:47 UTC, axtezy approved these changes

2021-11-10 21:05 UTC, siandreev commented on src/app/core/services/blockchain/web3/web3-public-service/Web3Public.ts
> +    const tokensSymbolsCache: { [address: string]: string } = {};
Тогда можно tuiPure

2021-11-10 21:06 UTC, siandreev commented on src/app/features/swaps/components/swap-info/components/cross-chain-swap-info/components/ccr-swap-info/ccr-swap-info.component.ts
> +      });
Посмотрел их сурс, вроде там Марк фор чек https://github.com/TinkoffCreditSystems/taiga-ui/blob/main/projects/cdk/observables/watch.ts

2021-11-10 21:22 UTC, siandreev commented on src/app/core/services/blockchain/web3/web3-public-service/Web3Public.ts
> +    const tokensSymbolsCache: { [address: string]: string } = {};
tuiPure ведет себя как @Cacheable
по возможности я бы заменил эту кастомную функцию на синатксис с @, можно потом переиспользовать будет. Что-то типа @Memory, например

2021-11-11 08:06 UTC, siandreev approved these changes

2021-11-11 08:10 UTC, merged