Rename cross-chain to multichain, add buy movr
Cryptorubic/rubic-app pull request #959
Opened 2021-11-16 13:57 UTC by axtezy

2021-11-16 15:32 UTC, ottebrut requested changes

2021-11-16 15:32 UTC, ottebrut commented on src/app/shared/components/buy-token/buy-token.component.ts
> +          token => token.address === fromToken.address && token.blockchain === fromToken.blockchain
compareAddresses

2021-11-16 15:45 UTC, ottebrut commented on src/app/shared/components/buy-token/buy-token.component.ts
> +          token => token.address === fromToken.address && token.blockchain === fromToken.blockchain
Даже лучше - compareTokens

2021-11-16 16:42 UTC, siandreev requested changes
+ к комменту Андрея

2021-11-16 16:42 UTC, siandreev commented on src/app/core/header/components/header/header.component.ts
> +    };
давай в отдельный метод

2021-11-17 08:33 UTC, axtezy commented on src/app/core/header/components/header/header.component.ts
> +    };
Сделал отдельный компонент под баннер и обработку клика по ссылке в баннере

2021-11-17 13:32 UTC, ottebrut approved these changes

2021-11-17 13:35 UTC, siandreev approved these changes

2021-11-18 07:45 UTC, merged