Add my-trades error handling
Cryptorubic/rubic-app pull request #960
Opened 2021-11-17 11:47 UTC by axtezy

2021-11-17 13:31 UTC, ottebrut requested changes

2021-11-17 13:31 UTC, ottebrut commented on src/app/features/my-trades/components/my-trades/components/accordion/accordion.component.ts
> +    this.tableDataSubscription$.unsubscribe();
Можно сразу добавить takeUntil вместо этого

2021-11-17 13:31 UTC, ottebrut commented on src/app/features/my-trades/components/my-trades/components/table/table.component.ts
> +  private readonly sorterSubject$ = new BehaviorSubject<TuiComparator<TableRow>>(this.sorters.Date);
_sorter$ и с остальными так же

2021-11-17 13:31 UTC, siandreev commented on src/app/features/my-trades/components/my-trades/components/accordion/accordion.component.ts
> +  @Input() tableData$!: Observable<TableRow[]>;
зачем `!` ?

2021-11-17 13:32 UTC, siandreev commented on src/app/features/my-trades/components/my-trades/components/accordion/accordion.component.ts
> +  @Input() tableData$!: Observable<TableRow[]>;
зачем `!` ?

2021-11-17 14:06 UTC, axtezy commented on src/app/features/my-trades/components/my-trades/components/abstract-table-data-component.ts
> +  public abstract onReceivePolygonBridgeTrade: EventEmitter<TableTrade>;
Чтобы избавиться от поведения Angular сущностей (`@Output`) в не Angular сущностях (в абстрактном классе), и перенести эту логику в другую Angular сущность (Компонент). Я убрал `@Directive` у абстрактного компонента, потому что выглядело как костыль.

2021-11-17 14:08 UTC, axtezy commented on src/app/features/my-trades/components/my-trades/components/table/table.component.html
> +            (sorter$ | async) === sorters[column.value] && (direction$ | async) === -1
Хотел так сделать, но нельзя несколько структурных директив повесить на 1 родителя, и список тоже не прокатит: `*tuiLet="odin$ | async as odin; dva$ | async as dva"`
Можно на разных родителей повесить, но как-то не оч выглядит

2021-11-17 16:18 UTC, axtezy commented on src/app/features/my-trades/components/my-trades/components/accordion/accordion.component.ts
> +  @Input() tableData$!: Observable<TableRow[]>;
Подумал, так можно было бы помечать обязательные `@Input` поля

2021-11-18 09:38 UTC, axtezy commented on src/app/features/my-trades/components/my-trades/components/table/table.component.ts
> +  @Input() tableData$!: Observable<TableRow[]>;
Отписал выше

2021-11-19 10:07 UTC, siandreev commented on src/app/features/my-trades/components/my-trades/components/accordion/accordion.component.ts
> +  @Input() tableData$!: Observable<TableRow[]>;
если честно, выглядит не оч понятно, может лучше это JSDoc-ом помечать?

2021-11-19 10:25 UTC, axtezy commented on src/app/features/my-trades/components/my-trades/components/accordion/accordion.component.ts
> +  @Input() tableData$!: Observable<TableRow[]>;
`@requires` в `JSDoc` значит другое, так что можно префиксом `[REQUIRES]` обозначать в описании поля

2021-11-19 11:42 UTC, siandreev commented on src/app/features/my-trades/components/my-trades/components/accordion/accordion.component.ts
> +  @Input() tableData$!: Observable<TableRow[]>;
думаю, `REQUIRED` будет лучше

2021-11-19 13:43 UTC, axtezy commented on src/app/features/my-trades/components/my-trades/components/table/table.component.html
> +            (sorter$ | async) === sorters[column.value] && (direction$ | async) === -1
Решил не запариваться с переписыванием директивы, просто в `*ngLet` объект передал:
```
*ngLet="{
    sorter: sorter$ | async,
    direction: direction$ | async,
    visibleData: visibleData$ | async,
    data: tableData$ | async,
    totalSize: total$ | async
  } as table"ble
 ...
  [sorter]="table.sorter"
```

2021-11-19 13:49 UTC, axtezy commented on src/app/features/my-trades/components/my-trades/components/accordion/accordion.component.ts
> +  @Input() tableData$!: Observable<TableRow[]>;
да, переименовал

2021-11-22 14:06 UTC, ottebrut requested changes

2021-11-22 14:06 UTC, ottebrut commented on src/app/features/my-trades/components/my-trades/components/accordion/accordion.component.ts
> +  @Input() tableData$: Observable<TableRow[]>;
Давай сначала Input, потом Output. И в TableComponent тоже самое.

2021-11-22 19:28 UTC, ottebrut requested changes

2021-11-22 19:28 UTC, ottebrut commented on src/app/features/my-trades/components/my-trades/components/table/table.component.ts
> +  @Input() tableData$: Observable<TableRow[]>;
тут забыл

2021-11-23 09:34 UTC, siandreev requested changes

2021-11-23 09:34 UTC, siandreev commented on src/app/features/my-trades/components/my-trades/my-trades.component.ts
> +  get tableData$(): Observable<TableRow[]> {
Поле, а не геттер

2021-11-26 18:29 UTC, siandreev approved these changes

2021-11-29 08:20 UTC, ottebrut approved these changes

2021-11-29 08:22 UTC, merged