[FEATURE] Add separate trust wallet provider
Cryptorubic/rubic-app pull request #970
Opened 2021-11-22 13:28 UTC by axtezy

2021-11-22 14:23 UTC, ottebrut requested changes

2021-11-22 14:23 UTC, ottebrut commented on src/app/core/services/blockchain/providers/common/wallet-connect-abstract.ts
> +  public readonly onNetworkChanges$: BehaviorSubject<IBlockchain>;
Их можно сделать приватными, тогда не нужно отключать eslint

2021-11-22 14:23 UTC, ottebrut commented on src/app/core/services/blockchain/providers/common/wallet-connect-abstract.ts
> +      this.isEnabled && BlockchainsInfo.getBlockchainById(this.selectedChain as BLOCKCHAIN_NAME)
`as BLOCKCHAIN_NAME` тут лишний, потому что `this.selectedChain` это blockchain id. Кстати, можно переименовать в `selectedChainId`, чтобы не путаться.

2021-11-22 14:23 UTC, ottebrut commented on src/app/core/services/blockchain/providers/private-provider/trust-wallet/trust-wallet-provider.ts
> +   * Subscribes to wallet connect deep link url and redirect after getting.
redirect -> redirects
Уже походит немного на троллинг, но я не троллю))

2021-11-22 14:23 UTC, ottebrut commented on src/app/core/wallets/components/wallets-modal/models/providers.ts
> +export const PROVIDERS_LIST = [
По моему, лучше писать `PROVIDERS_LIST: ReadonlyArray<WalletProvider>`, чем `as ReadonlyArray<WalletProvider>`

2021-11-22 19:27 UTC, ottebrut approved these changes

2021-11-26 18:29 UTC, siandreev approved these changes

2021-11-29 08:41 UTC, merged